# HydroSOS - Persistence and Hydrological Analogues method

In this notebook, we explore the Persistance and Hydrological Analogue method

## Import the python libraries

In [1]:
%reset -f

In [2]:
# Importing the libraries
import pandas as pd
import seaborn as sns
import numpy as np
import calendar
import datetime
import matplotlib.pyplot as plt
import math
from scipy import stats
plt.style.use('classic')
%matplotlib inline

from IPython.display import HTML

sns.set()

In [3]:
# install a conda package in the current Jupyter kernel
#import sys
#!conda install --yes --prefix {sys.prefix} missingno

In [4]:
# import missingno

### We create function for percentile definition

In [5]:
# Quantile Function Definitions
def q1(x):
    return x.quantile(0.28)

def q2(x):
    return x.median()

def q3(x):
    return x.quantile(0.72)

def q5(x):
    return x.quantile(0.05)

def q95(x):
    return x.quantile(0.95)

def q87(x):
    return x.quantile(0.87)

def q13(x):
    return x.quantile(0.13)

We create a function called add_month that add the number of months based on an input date. This will be used in the Jack-Knife Validation

In [6]:
def add_months(sourcedate, months):
    month = sourcedate.month - 1 + months
    year = sourcedate.year + month // 12
    month = month % 12 + 1
    day = min(sourcedate.day, calendar.monthrange(year,month)[1])
    return datetime.date(year, month, day)

the monthly anomalies of the most recently past months are compared with all possible historical sequences of anomalies covering the same months of the year. That is, if the recent past covers, say, the months February to July, then potential analogues are sought only in the February to July sequences of the historical record

Define a Root Mean Square Error Function. This function will be used to select the analogues years

In [7]:
def rmse(predictions,targets):
    return np.around(((predictions - targets) ** 2).mean() ** 0.5,4)

## Import Data

In this example we import the daily discharge data from Fray Marcos station, from 01 Jan 1980 to 31 Jan 2023. We import and then visualize head and tail of dataframe, plot timeseries and also make boxplot for daily discharge grouped by month.

In [8]:
MONTHLY_ANOMALY = pd.read_csv('../data/santalucia_caudales_abr2023_MA.csv',parse_dates=['Month'],index_col="Month",na_values="")

In [9]:
MONTHLY_ANOMALY

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Month,,,,,,,,,,,,,,,,,,,,,
1,-2.123750,-0.308179,-1.551073,-0.796712,0.727208,-1.244110,-0.670261,-0.504405,0.818331,-1.280020,...,NaN,0.204800,0.814189,0.200969,0.324539,NaN,-0.385739,-0.230398,1.141266,-0.810341
2,0.316909,0.511895,0.235052,0.100800,2.454052,-1.259258,-0.370705,-0.773939,0.187623,-1.368724,...,NaN,-0.394508,-0.887051,0.577828,-0.659732,NaN,-0.742382,0.860497,-0.252152,-0.951652
3,1.120851,-0.362955,-0.375811,-0.951718,1.193772,0.744396,-0.898463,0.402005,1.742555,-0.994765,...,NaN,-0.677517,-1.096631,-0.545900,0.112274,-0.449993,-1.059530,0.710564,-0.389803,-1.550890
4,1.200881,-0.162872,-0.336847,-0.364767,-0.160803,0.583685,-0.569182,-0.573368,0.695763,-0.983002,...,NaN,NaN,2.118149,-0.969378,-0.979009,-1.319303,-1.188353,0.670950,-0.613546,-1.664257
5,1.373637,1.804841,0.930711,-0.734193,0.722645,0.782769,0.315669,-0.976373,-0.788636,-1.846345,...,NaN,-1.283716,0.049850,0.107734,-0.537679,0.053286,-1.607545,-0.087954,-0.178636,NaN
6,0.796236,-0.163576,1.175735,0.284660,1.159690,0.689027,0.508366,-1.715410,-1.236878,-2.084692,...,NaN,-1.814261,-0.301783,-0.850826,-0.520173,1.715769,0.585062,1.115231,-1.331390,NaN
7,0.669569,0.327620,0.605223,-0.332697,1.575762,0.619012,0.095685,-0.033314,-0.667932,-1.610597,...,NaN,-2.458694,1.464433,0.166312,0.883619,-0.018995,-0.531656,-0.129605,0.197415,NaN
8,0.585540,0.927440,0.726022,1.307074,-0.886873,0.710619,2.020854,-0.018238,-0.082788,-0.035092,...,NaN,0.983076,0.589616,1.700595,NaN,0.098847,-0.737193,-0.005090,-1.282212,NaN
9,-0.481964,0.523972,0.384146,1.468819,-0.124697,0.380196,0.927865,-0.596046,-1.185904,-1.516816,...,NaN,-1.124536,0.693663,1.629718,NaN,0.482405,0.104265,0.059747,-1.975643,NaN
10,0.640823,-0.748537,NaN,1.573028,0.291037,0.794642,0.913218,0.584085,-1.280330,-1.961382,...,NaN,-0.102707,-0.580942,-0.108481,NaN,1.729348,-0.961647,-1.006693,-1.762722,NaN
11,-0.107321,-1.188138,NaN,1.199867,1.158132,0.633891,1.610914,-0.415193,-0.544928,-1.405065,...,1.227963,-1.188595,-0.514190,-0.337047,NaN,-0.157611,-1.797352,-1.153155,-1.097971,NaN
12,0.958023,0.398420,NaN,-0.256680,-0.942096,-0.750703,0.498030,-0.413689,-1.010211,-0.226197,...,NaN,0.400305,-0.312370,-0.803140,NaN,-0.782450,-1.398219,-1.154836,-1.063870,NaN

In [12]:
DISCHARGE_MONTHLY = pd.read_csv('../data/santalucia_caudales_abr2023_DA.csv',parse_dates=['Fecha'],index_col="Fecha",na_values="")

In [13]:
DISCHARGE_MONTHLY

             Discharge  Year  Month  water_year  Q_to_log  Anomaly_Qlog
Fecha
1980-01-31    1.198613  1980      1        1980  0.181165     -2.123750
1980-02-29   28.386414  1980      2        1980  3.345911      0.316909
1980-03-31   86.782323  1980      3        1980  4.463403      1.120851
1980-04-30  172.187367  1980      4        1981  5.148583      1.200881
1980-05-31  275.560258  1980      5        1981  5.618806      1.373637
...                ...   ...    ...         ...       ...           ...
2022-12-31    5.969037  2022     12        2023  1.786586     -1.063870
2023-01-31    5.419419  2023      1        2023  1.689989     -0.810341
2023-02-28    5.557464  2023      2        2023  1.715142     -0.951652
2023-03-31    3.336120  2023      3        2023  1.204808     -1.550890
2023-04-30    2.693037  2023      4        2024  0.990670     -1.664257

[520 rows x 6 columns]

In [14]:
YEAR_HINDCAST_SELECTED = np.unique(DISCHARGE_MONTHLY['Year'])
# rename columns change str for int
MONTHLY_ANOMALY.columns = YEAR_HINDCAST_SELECTED

In [26]:
YEAR_HINDCAST_SELECTED

array([1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990,
       1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023],
      dtype=int64)

In [31]:
range_analysis = range(YEAR_HINDCAST_SELECTED[0],YEAR_HINDCAST_SELECTED[-1])

In [32]:
LOG_DISCHARGE_MONTHLY_PIVOT = pd.pivot_table(DISCHARGE_MONTHLY, index=['Month'],columns=['Year'], values=['Q_to_log'],dropna=False)
LOG_DISCHARGE_MONTHLY_PIVOT.columns = YEAR_HINDCAST_SELECTED

In [33]:
LOG_DISCHARGE_MONTHLY_PIVOT

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Month,,,,,,,,,,,,,,,,,,,,,
1,0.181165,2.266864,0.839047,1.705645,3.456299,1.191681,1.850911,2.041442,3.560980,1.150429,...,NaN,2.856166,3.556222,2.851765,2.993721,NaN,2.177764,2.356218,3.931962,1.689989
2,3.345911,3.596570,3.240681,3.068096,6.093265,1.319706,2.461964,1.943596,3.179709,1.178985,...,NaN,2.431365,1.798187,3.681329,2.090412,NaN,1.984164,4.044708,2.614367,1.715142
3,4.463403,2.653676,2.637997,1.935590,4.552342,4.004259,2.000542,3.586661,5.221666,1.883088,...,NaN,2.270020,1.758847,2.430547,3.233290,2.547520,1.804097,3.962996,2.620931,1.204808
4,5.148583,3.169494,2.917019,2.876502,3.172495,4.252904,2.579853,2.573778,4.415552,1.979313,...,NaN,NaN,6.479732,1.999085,1.985108,1.491270,1.681306,4.379543,2.515471,0.990670
5,5.618806,6.181355,5.040966,2.868932,4.769523,4.847961,4.238582,2.552985,2.797907,1.418020,...,NaN,2.152025,3.891795,3.967311,3.125305,3.896278,1.729558,3.712016,3.593711,NaN
6,5.431652,4.226532,5.908143,4.789328,5.887999,5.297043,5.070209,2.278081,2.878916,1.814417,...,NaN,2.153965,4.053002,3.363635,3.778796,6.586199,5.166506,5.832176,2.760248,NaN
7,5.315642,4.974052,5.251364,4.314426,6.220885,5.265138,4.742359,4.613495,3.979544,3.037866,...,NaN,2.190658,6.109673,4.812913,5.529467,4.627800,4.115676,4.517306,4.843983,NaN
8,5.119868,5.464556,5.261496,5.847285,3.635448,5.245967,6.566886,4.511166,4.446090,4.494176,...,NaN,5.520645,5.123977,6.244016,NaN,4.629206,3.786349,4.524422,3.236886,NaN
9,4.117590,5.092622,4.957092,6.008443,4.463882,4.953263,5.484107,4.007013,3.435276,3.114530,...,NaN,3.494759,5.257100,6.164399,NaN,5.052332,4.685809,4.642659,2.669799,NaN
10,4.931459,3.168846,NaN,6.114101,4.487702,5.126601,5.277033,4.859478,2.494186,1.630170,...,NaN,3.988180,3.381466,3.980854,NaN,6.312417,2.898484,2.841336,1.882200,NaN
11,3.681058,2.351966,NaN,5.288520,5.237198,4.592534,5.793989,3.302464,3.142927,2.085208,...,5.323071,2.351404,3.180727,3.398562,NaN,3.619216,1.602809,2.394985,2.462846,NaN
12,4.098310,3.458490,NaN,2.709484,1.925816,2.144644,3.572378,2.529967,1.847937,2.744337,...,NaN,3.460645,2.645811,2.084690,NaN,2.108346,1.404309,1.682580,1.786586,NaN

In [34]:
ANOMALY_ANALOGUES = MONTHLY_ANOMALY[range_analysis]
QLOG_ANALOGUES = LOG_DISCHARGE_MONTHLY_PIVOT[range_analysis]
HTML(ANOMALY_ANALOGUES.to_html())

In [35]:
ANOMALY_ANALOGUE_TS = pd.melt(ANOMALY_ANALOGUES.reset_index(), id_vars='Month',var_name=['Year'],ignore_index = True)
ANOMALY_ANALOGUE_TS.columns = ['Month','Year','Anomaly_Qlog']
HTML(ANOMALY_ANALOGUE_TS.head(6).to_html())

In [36]:
QLOG_ANALOGUE_TS = pd.melt(QLOG_ANALOGUES.reset_index(), id_vars='Month',var_name=['Year'],ignore_index = True)
QLOG_ANALOGUE_TS.columns = ['Month','Year','Qlog']
HTML(QLOG_ANALOGUE_TS.head(6).to_html())

In [37]:
ANOMALY_ANALOGUE_TS['DATE'] = pd.to_datetime(ANOMALY_ANALOGUE_TS[['Year', 'Month']].assign(DAY=1))
HTML(ANOMALY_ANALOGUE_TS.head(6).to_html(index=False))

In [38]:
######## PARTE CENTRAL

## HINDCAST PARA FORECAST_LENGHT EN MESES

In [39]:
## define Dana last months of observation
DANA = 9
## define forecast lenght in months
FORECAST_LENGTH = 3
##

In [40]:
##
# Toma como argumentos
# range_analysis - > YEAR_ANALYSIS
# QLOG_ANALOGUES
# QLOG_ANALOGUE_TS
# ANOMALY_ANALOGUES
# ANOMALY_ANALOGUE_TS
# MONTH_ANALYSIS
# DANA
# FORECAST_LENGTH
##


YEAR_ANALYSIS = range_analysis # definir al menos para tener DANA meses para atras con datos..

MONTH_ANALYSIS = range(1,13,1)
df = pd.DataFrame()
ANOMALY_HISTORICAL = pd.DataFrame()
RMSE = []
ANO_TARG = []
ANO_PRED = []
MON_TARG = []
MON_PRED = []
TARG = []
PRED = []
OBS_ANOM = []

MEAN_ANOM_HIND = []
STD_ANOM_HIND = []
Q1_ANOM_HIND = []
Q3_ANOM_HIND = []

MEAN_QLOG_HIND = []
STD_QLOG_HIND = []

##
print('Dana selected: ',DANA, 'months')
print('Forecast length selected: ', FORECAST_LENGTH , 'months')
##


for y in YEAR_ANALYSIS:    
            
    
    for m in MONTH_ANALYSIS:
        
        print('Year:',y,"-","End-Month of observation:",m)
        # define end month and year based on the for-loop
        END_DATE_HIST = datetime.date.today().replace(year=y, month=m, day=1)

        # define initial date according to Dana past months of observation
        FIRST_DATE_HIST = add_months(END_DATE_HIST,-DANA)
        
        # Define forecast date
        FORECAST_DATE = add_months(END_DATE_HIST,FORECAST_LENGTH)       
        print('Forecast Year:',FORECAST_DATE.year,"-"," Forecast Month:",FORECAST_DATE.month)

        
        if FORECAST_DATE.year <= YEAR_ANALYSIS[-1]:
            # From the Qlog values, drop the monthly values for the year of analysis and mantain the remaining years. 
            # This is the Qlog hindcast series
            # print('Dropping year:',y,"-","End-Month:",m)
            print('Dropping year:',y," - get series for analysis.")
            QLOG_HINDCAST_TARG_ANALOGUE = QLOG_ANALOGUES.drop([FORECAST_DATE.year],axis=1)
            QLOG_HINDCAST_TARG_ANALOGUE_TS = QLOG_ANALOGUE_TS[QLOG_ANALOGUE_TS['Year'] != FORECAST_DATE.year]

            # From the monthly anomaly values, drop the monthly values for the year of analysis and mantain the remaining years. 
            # This is the anomaly hindcast series
            ANOMALY_HINDCAST_TARG_ANALOGUE = ANOMALY_ANALOGUES.drop([FORECAST_DATE.year],axis=1)
            ANOMALY_HINDCAST_TARG_ANALOGUE_TS = ANOMALY_ANALOGUE_TS[ANOMALY_ANALOGUE_TS['Year'] != FORECAST_DATE.year]
        
        else:
            print('Forecast Year out of range')
            break

            
        
        # query in the original anomaly time serie the first date and end_date
        ANOMALY_TARGET = ANOMALY_ANALOGUE_TS.query('DATE > @FIRST_DATE_HIST & DATE <= @END_DATE_HIST')
        print(ANOMALY_TARGET)
        
        # Check if there are enough months in the past
        if ANOMALY_TARGET.index.size < DANA:
            print('There are not enough months in the past')
            print('')
        
        else:
            print('There are enough months in the past')
            print(f"Target period: {add_months(FIRST_DATE_HIST,1).strftime('%m-%Y')} to {(END_DATE_HIST.strftime('%m-%Y'))}")
            
            # Define a list with the targets months
            MONTHS_TARG = pd.date_range(add_months(FIRST_DATE_HIST,1),add_months(END_DATE_HIST,1),freq='M').month.to_list()
            
            # Get the anomaly hindcast target series
            ANOMALY_HINDCAST_TARG = ANOMALY_ANALOGUE_TS.drop(ANOMALY_TARGET.index)
            ANOMALY_HINDCAST_TARG = ANOMALY_HINDCAST_TARG.query('Month == @MONTHS_TARG').reset_index()
            
            # Get the anomaly target series
            df['target'] = ANOMALY_TARGET["Anomaly_Qlog"].values.round(5)

            # Adjust anomaly hindcast target series index
            if MONTHS_TARG[0]>=MONTHS_TARG[-1]:
                print('Target period includes two years')
                print('')
                if ANOMALY_HINDCAST_TARG['Month'][0] != MONTHS_TARG[0]:
                    ANOMALY_HINDCAST_TARG.drop([*range(0,ANOMALY_HINDCAST_TARG[ANOMALY_HINDCAST_TARG['Month']==MONTHS_TARG[0]].index.min())],inplace=True)
                    ANOMALY_HINDCAST_TARG.reset_index(drop=True)
                    # print(len(ANOMALY_HINDCAST_TARG.index)/DANA)

            else:
                print('Target period includes only one year')
                print('')
                pass

            # Iterate over de anomaly hindcast target where are the potential analogues
            for i in range(0, int(len(ANOMALY_HINDCAST_TARG.index)/DANA)):

                
                # create a dataframe (df) for the "preditec" (analogue) and "target" (current year)
                df['predicted'] = ANOMALY_HINDCAST_TARG.iloc[i*DANA:(i+1)*DANA,1:-1]["Anomaly_Qlog"].values.round(5)
                
                # save month and year value of target series
                ANO_TARG.append(f"{str(ANOMALY_HINDCAST_TARG.iloc[i*DANA:(i+1)*DANA,1:-1]['Year'].tolist()[0])}-{str(ANOMALY_HINDCAST_TARG.iloc[i*DANA:(i+1)*DANA,1:-1]['Year'].tolist()[-1])}")
                MON_TARG.append(MONTHS_TARG)
                
                # save month and year value of predicted series
                ANO_PRED.append(add_months(END_DATE_HIST, FORECAST_LENGTH).year)
                MON_PRED.append(add_months(END_DATE_HIST, FORECAST_LENGTH).month)            

                # define the date to get the anomaly value of the actual month of the potential analogue
                DATE_DANA=datetime.date.today().replace(year=ANOMALY_HINDCAST_TARG.iloc[i*DANA:(i+1)*DANA]['Year'].values[-1], month=ANOMALY_HINDCAST_TARG.iloc[i*DANA:(i+1)*DANA]['Month'].values[-1], day=1)
                
                # get the anomaly value of the following month of the potential analogue
                ANOMALY_OBS = ANOMALY_ANALOGUE_TS.query('DATE == @add_months(@DATE_DANA,@FORECAST_LENGTH)')['Anomaly_Qlog'].values
                # print(ANOMALY_OBS)
                
                # get the mean and standard deviation of monthly anomaly series use for hindcast necessary for rescale de forecast
                MEAN_ANOM_HIND.append(ANOMALY_HINDCAST_TARG_ANALOGUE.loc[add_months(DATE_DANA,FORECAST_LENGTH).month].mean())
                STD_ANOM_HIND.append(ANOMALY_HINDCAST_TARG_ANALOGUE.loc[add_months(DATE_DANA,FORECAST_LENGTH).month].std())           
                
                # get statistic of monthly anomaly serie use for hindcast necesary contingency tables
                Q1_ANOM_HIND.append(q1(ANOMALY_HINDCAST_TARG_ANALOGUE.loc[add_months(DATE_DANA,FORECAST_LENGTH).month]))
                Q3_ANOM_HIND.append(q3(ANOMALY_HINDCAST_TARG_ANALOGUE.loc[add_months(DATE_DANA,FORECAST_LENGTH).month]))  
                
                # get the mean and standard deviation of monthly qlog series use for hindcast 
                MEAN_QLOG_HIND.append(QLOG_HINDCAST_TARG_ANALOGUE.loc[add_months(DATE_DANA,FORECAST_LENGTH).month].mean())
                STD_QLOG_HIND.append(QLOG_HINDCAST_TARG_ANALOGUE.loc[add_months(DATE_DANA,FORECAST_LENGTH).month].std())

                
                try:
                    if math.isnan(ANOMALY_OBS):
                        #print('Next month to end-month is nan')
                        RMSE_val = np.nan
                        RMSE.append(RMSE_val)
                        TARG.append(df['target'].values.tolist())
                        PRED.append(df['predicted'].values.tolist())
                        OBS_ANOM.append(np.nan)
                    else:
                        #print('Next month to end-month is not empty')
                        if df['predicted'].isnull().values.any() == False:
                            # calculate the RMSE
                            RMSE_val = rmse(df['predicted'],df['target'])
                            # append in the empty lists
                            RMSE.append(RMSE_val)
                            TARG.append(df['target'].values.tolist())
                            PRED.append(df['predicted'].values.tolist())
                            OBS_ANOM.append(ANOMALY_OBS.round(5)[0])
                        else:
                            RMSE_val = np.nan
                            RMSE.append(RMSE_val)
                            TARG.append(df['target'].values.tolist())
                            PRED.append(df['predicted'].values.tolist())
                            OBS_ANOM.append(np.nan)
                except:
                    if ANOMALY_OBS.size == 0:
                        #print('Next month to end-month is empty')
                        RMSE_val = np.nan
                        RMSE.append(RMSE_val)
                        TARG.append(df['target'].values.tolist())
                        PRED.append(df['predicted'].values.tolist())
                        OBS_ANOM.append(np.nan)

Dana selected:  9 months
Forecast length selected:  3 months
Year: 1980 - End-Month of observation: 1
Forecast Year: 1980 -  Forecast Month: 4
Dropping year: 1980  - get series for analysis.
   Month  Year  Anomaly_Qlog       DATE
0      1  1980      -2.12375 1980-01-01
There are not enough months in the past

Year: 1980 - End-Month of observation: 2
Forecast Year: 1980 -  Forecast Month: 5
Dropping year: 1980  - get series for analysis.
   Month  Year  Anomaly_Qlog       DATE
0      1  1980     -2.123750 1980-01-01
1      2  1980      0.316909 1980-02-01
There are not enough months in the past

Year: 1980 - End-Month of observation: 3
Forecast Year: 1980 -  Forecast Month: 6
Dropping year: 1980  - get series for analysis.
   Month  Year  Anomaly_Qlog       DATE
0      1  1980     -2.123750 1980-01-01
1      2  1980      0.316909 1980-02-01
2      3  1980      1.120851 1980-03-01
There are not enough months in the past

Year: 1980 - End-Month of observation: 4
Forecast Year: 1980 -  Forecast Month: 7
Dropping year: 1980  - get series for analysis.
   Month  Year  Anomaly_Qlog       DATE
0      1  1980     -2.123750 1980-01-01
1      2  1980      0.316909 1980-02-01
2      3  1980      1.120851 1980-03-01
3      4  1980      1.200881 1980-04-01
There are not enough months in the past

Year: 1980 - End-Month of observation: 5
Forecast Year: 1980 -  Forecast Month: 8
Dropping year: 1980  - get series for analysis.
   Month  Year  Anomaly_Qlog       DATE
0      1  1980     -2.123750 1980-01-01
1      2  1980      0.316909 1980-02-01
2      3  1980      1.120851 1980-03-01
3      4  1980      1.200881 1980-04-01
4      5  1980      1.373637 1980-05-01
There are not enough months in the past

Year: 1980 - End-Month of observation: 6
Forecast Year: 1980 -  Forecast Month: 9
Dropping year: 1980  - get series for analysis.
   Month  Year  Anomaly_Qlog       DATE
0      1  1980     -2.123750 1980-01-01
1      2  1980      0.316909 1980-02-01
2      3  1980      1.120851 1980-03-01
3      4  1980      1.200881 1980-04-01
4      5  1980      1.373637 1980-05-01
5      6  1980      0.796236 1980-06-01
There are not enough months in the past

Year: 1980 - End-Month of observation: 7
Forecast Year: 1980 -  Forecast Month: 10
Dropping year: 1980  - get series for analysis.
   Month  Year  Anomaly_Qlog       DATE
0      1  1980     -2.123750 1980-01-01
1      2  1980      0.316909 1980-02-01
2      3  1980      1.120851 1980-03-01
3      4  1980      1.200881 1980-04-01
4      5  1980      1.373637 1980-05-01
5      6  1980      0.796236 1980-06-01
6      7  1980      0.669569 1980-07-01
There are not enough months in the past

Year: 1980 - End-Month of observation: 8
Forecast Year: 1980 -  Forecast Month: 11
Dropping year: 1980  - get series for analysis.
   Month  Year  Anomaly_Qlog       DATE
0      1  1980     -2.123750 1980-01-01
1      2  1980      0.316909 1980-02-01
2      3  1980      1.120851 1980-03-01
3      4  1980      1.200881 1980-04-01
4      5  1980      1.373637 1980-05-01
5      6  1980      0.796236 1980-06-01
6      7  1980      0.669569 1980-07-01
7      8  1980      0.585540 1980-08-01
There are not enough months in the past

Year: 1980 - End-Month of observation: 9
Forecast Year: 1980 -  Forecast Month: 12
Dropping year: 1980  - get series for analysis.
   Month  Year  Anomaly_Qlog       DATE
0      1  1980     -2.123750 1980-01-01
1      2  1980      0.316909 1980-02-01
2      3  1980      1.120851 1980-03-01
3      4  1980      1.200881 1980-04-01
4      5  1980      1.373637 1980-05-01
5      6  1980      0.796236 1980-06-01
6      7  1980      0.669569 1980-07-01
7      8  1980      0.585540 1980-08-01
8      9  1980     -0.481964 1980-09-01
There are enough months in the past
Target period: 01-1980 to 09-1980
Target period includes only one year

Year: 1980 - End-Month of observation: 10
Forecast Year: 1981 -  Forecast Month: 1
Dropping year: 1980  - get series for analysis.
   Month  Year  Anomaly_Qlog       DATE
1      2  1980      0.316909 1980-02-01
2      3  1980      1.120851 1980-03-01
3      4  1980      1.200881 1980-04-01
4      5  1980      1.373637 1980-05-01
5      6  1980      0.796236 1980-06-01
6      7  1980      0.669569 1980-07-01
7      8  1980      0.585540 1980-08-01
8      9  1980     -0.481964 1980-09-01
9     10  1980      0.640823 1980-10-01
There are enough months in the past
Target period: 02-1980 to 10-1980
Target period includes only one year

Year: 1980 - End-Month of observation: 11
Forecast Year: 1981 -  Forecast Month: 2
Dropping year: 1980  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
2       3  1980      1.120851 1980-03-01
3       4  1980      1.200881 1980-04-01
4       5  1980      1.373637 1980-05-01
5       6  1980      0.796236 1980-06-01
6       7  1980      0.669569 1980-07-01
7       8  1980      0.585540 1980-08-01
8       9  1980     -0.481964 1980-09-01
9      10  1980      0.640823 1980-10-01
10     11  1980     -0.107321 1980-11-01
There are enough months in the past
Target period: 03-1980 to 11-1980
Target period includes only one year

Year: 1980 - End-Month of observation: 12
Forecast Year: 1981 -  Forecast Month: 3
Dropping year: 1980  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
3       4  1980      1.200881 1980-04-01
4       5  1980      1.373637 1980-05-01
5       6  1980      0.796236 1980-06-01
6       7  1980      0.669569 1980-07-01
7       8  1980      0.585540 1980-08-01
8       9  1980     -0.481964 1980-09-01
9      10  1980      0.640823 1980-10-01
10     11  1980     -0.107321 1980-11-01
11     12  1980      0.958023 1980-12-01
There are enough months in the past
Target period: 04-1980 to 12-1980
Target period includes only one year

Year: 1981 - End-Month of observation: 1
Forecast Year: 1981 -  Forecast Month: 4
Dropping year: 1981  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
4       5  1980      1.373637 1980-05-01
5       6  1980      0.796236 1980-06-01
6       7  1980      0.669569 1980-07-01
7       8  1980      0.585540 1980-08-01
8       9  1980     -0.481964 1980-09-01
9      10  1980      0.640823 1980-10-01
10     11  1980     -0.107321 1980-11-01
11     12  1980      0.958023 1980-12-01
12      1  1981     -0.308179 1981-01-01
There are enough months in the past
Target period: 05-1980 to 01-1981
Target period includes two years

Year: 1981 - End-Month of observation: 2
Forecast Year: 1981 -  Forecast Month: 5
Dropping year: 1981  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
5       6  1980      0.796236 1980-06-01
6       7  1980      0.669569 1980-07-01
7       8  1980      0.585540 1980-08-01
8       9  1980     -0.481964 1980-09-01
9      10  1980      0.640823 1980-10-01
10     11  1980     -0.107321 1980-11-01
11     12  1980      0.958023 1980-12-01
12      1  1981     -0.308179 1981-01-01
13      2  1981      0.511895 1981-02-01
There are enough months in the past
Target period: 06-1980 to 02-1981
Target period includes two years

Year: 1981 - End-Month of observation: 3
Forecast Year: 1981 -  Forecast Month: 6
Dropping year: 1981  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
6       7  1980      0.669569 1980-07-01
7       8  1980      0.585540 1980-08-01
8       9  1980     -0.481964 1980-09-01
9      10  1980      0.640823 1980-10-01
10     11  1980     -0.107321 1980-11-01
11     12  1980      0.958023 1980-12-01
12      1  1981     -0.308179 1981-01-01
13      2  1981      0.511895 1981-02-01
14      3  1981     -0.362955 1981-03-01
There are enough months in the past
Target period: 07-1980 to 03-1981
Target period includes two years

Year: 1981 - End-Month of observation: 4
Forecast Year: 1981 -  Forecast Month: 7
Dropping year: 1981  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
7       8  1980      0.585540 1980-08-01
8       9  1980     -0.481964 1980-09-01
9      10  1980      0.640823 1980-10-01
10     11  1980     -0.107321 1980-11-01
11     12  1980      0.958023 1980-12-01
12      1  1981     -0.308179 1981-01-01
13      2  1981      0.511895 1981-02-01
14      3  1981     -0.362955 1981-03-01
15      4  1981     -0.162872 1981-04-01
There are enough months in the past
Target period: 08-1980 to 04-1981
Target period includes two years

Year: 1981 - End-Month of observation: 5
Forecast Year: 1981 -  Forecast Month: 8
Dropping year: 1981  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
8       9  1980     -0.481964 1980-09-01
9      10  1980      0.640823 1980-10-01
10     11  1980     -0.107321 1980-11-01
11     12  1980      0.958023 1980-12-01
12      1  1981     -0.308179 1981-01-01
13      2  1981      0.511895 1981-02-01
14      3  1981     -0.362955 1981-03-01
15      4  1981     -0.162872 1981-04-01
16      5  1981      1.804841 1981-05-01
There are enough months in the past
Target period: 09-1980 to 05-1981
Target period includes two years

Year: 1981 - End-Month of observation: 6
Forecast Year: 1981 -  Forecast Month: 9
Dropping year: 1981  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
9      10  1980      0.640823 1980-10-01
10     11  1980     -0.107321 1980-11-01
11     12  1980      0.958023 1980-12-01
12      1  1981     -0.308179 1981-01-01
13      2  1981      0.511895 1981-02-01
14      3  1981     -0.362955 1981-03-01
15      4  1981     -0.162872 1981-04-01
16      5  1981      1.804841 1981-05-01
17      6  1981     -0.163576 1981-06-01
There are enough months in the past
Target period: 10-1980 to 06-1981
Target period includes two years

Year: 1981 - End-Month of observation: 7
Forecast Year: 1981 -  Forecast Month: 10
Dropping year: 1981  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
10     11  1980     -0.107321 1980-11-01
11     12  1980      0.958023 1980-12-01
12      1  1981     -0.308179 1981-01-01
13      2  1981      0.511895 1981-02-01
14      3  1981     -0.362955 1981-03-01
15      4  1981     -0.162872 1981-04-01
16      5  1981      1.804841 1981-05-01
17      6  1981     -0.163576 1981-06-01
18      7  1981      0.327620 1981-07-01
There are enough months in the past
Target period: 11-1980 to 07-1981
Target period includes two years

Year: 1981 - End-Month of observation: 8
Forecast Year: 1981 -  Forecast Month: 11
Dropping year: 1981  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
11     12  1980      0.958023 1980-12-01
12      1  1981     -0.308179 1981-01-01
13      2  1981      0.511895 1981-02-01
14      3  1981     -0.362955 1981-03-01
15      4  1981     -0.162872 1981-04-01
16      5  1981      1.804841 1981-05-01
17      6  1981     -0.163576 1981-06-01
18      7  1981      0.327620 1981-07-01
19      8  1981      0.927440 1981-08-01
There are enough months in the past
Target period: 12-1980 to 08-1981
Target period includes two years

Year: 1981 - End-Month of observation: 9
Forecast Year: 1981 -  Forecast Month: 12
Dropping year: 1981  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
12      1  1981     -0.308179 1981-01-01
13      2  1981      0.511895 1981-02-01
14      3  1981     -0.362955 1981-03-01
15      4  1981     -0.162872 1981-04-01
16      5  1981      1.804841 1981-05-01
17      6  1981     -0.163576 1981-06-01
18      7  1981      0.327620 1981-07-01
19      8  1981      0.927440 1981-08-01
20      9  1981      0.523972 1981-09-01
There are enough months in the past
Target period: 01-1981 to 09-1981
Target period includes only one year

Year: 1981 - End-Month of observation: 10
Forecast Year: 1982 -  Forecast Month: 1
Dropping year: 1981  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
13      2  1981      0.511895 1981-02-01
14      3  1981     -0.362955 1981-03-01
15      4  1981     -0.162872 1981-04-01
16      5  1981      1.804841 1981-05-01
17      6  1981     -0.163576 1981-06-01
18      7  1981      0.327620 1981-07-01
19      8  1981      0.927440 1981-08-01
20      9  1981      0.523972 1981-09-01
21     10  1981     -0.748537 1981-10-01
There are enough months in the past
Target period: 02-1981 to 10-1981
Target period includes only one year

Year: 1981 - End-Month of observation: 11
Forecast Year: 1982 -  Forecast Month: 2
Dropping year: 1981  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
14      3  1981     -0.362955 1981-03-01
15      4  1981     -0.162872 1981-04-01
16      5  1981      1.804841 1981-05-01
17      6  1981     -0.163576 1981-06-01
18      7  1981      0.327620 1981-07-01
19      8  1981      0.927440 1981-08-01
20      9  1981      0.523972 1981-09-01
21     10  1981     -0.748537 1981-10-01
22     11  1981     -1.188138 1981-11-01
There are enough months in the past
Target period: 03-1981 to 11-1981
Target period includes only one year

Year: 1981 - End-Month of observation: 12
Forecast Year: 1982 -  Forecast Month: 3
Dropping year: 1981  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
15      4  1981     -0.162872 1981-04-01
16      5  1981      1.804841 1981-05-01
17      6  1981     -0.163576 1981-06-01
18      7  1981      0.327620 1981-07-01
19      8  1981      0.927440 1981-08-01
20      9  1981      0.523972 1981-09-01
21     10  1981     -0.748537 1981-10-01
22     11  1981     -1.188138 1981-11-01
23     12  1981      0.398420 1981-12-01
There are enough months in the past
Target period: 04-1981 to 12-1981
Target period includes only one year

Year: 1982 - End-Month of observation: 1
Forecast Year: 1982 -  Forecast Month: 4
Dropping year: 1982  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
16      5  1981      1.804841 1981-05-01
17      6  1981     -0.163576 1981-06-01
18      7  1981      0.327620 1981-07-01
19      8  1981      0.927440 1981-08-01
20      9  1981      0.523972 1981-09-01
21     10  1981     -0.748537 1981-10-01
22     11  1981     -1.188138 1981-11-01
23     12  1981      0.398420 1981-12-01
24      1  1982     -1.551073 1982-01-01
There are enough months in the past
Target period: 05-1981 to 01-1982
Target period includes two years

Year: 1982 - End-Month of observation: 2
Forecast Year: 1982 -  Forecast Month: 5
Dropping year: 1982  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
17      6  1981     -0.163576 1981-06-01
18      7  1981      0.327620 1981-07-01
19      8  1981      0.927440 1981-08-01
20      9  1981      0.523972 1981-09-01
21     10  1981     -0.748537 1981-10-01
22     11  1981     -1.188138 1981-11-01
23     12  1981      0.398420 1981-12-01
24      1  1982     -1.551073 1982-01-01
25      2  1982      0.235052 1982-02-01
There are enough months in the past
Target period: 06-1981 to 02-1982
Target period includes two years

Year: 1982 - End-Month of observation: 3
Forecast Year: 1982 -  Forecast Month: 6
Dropping year: 1982  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
18      7  1981      0.327620 1981-07-01
19      8  1981      0.927440 1981-08-01
20      9  1981      0.523972 1981-09-01
21     10  1981     -0.748537 1981-10-01
22     11  1981     -1.188138 1981-11-01
23     12  1981      0.398420 1981-12-01
24      1  1982     -1.551073 1982-01-01
25      2  1982      0.235052 1982-02-01
26      3  1982     -0.375811 1982-03-01
There are enough months in the past
Target period: 07-1981 to 03-1982
Target period includes two years

Year: 1982 - End-Month of observation: 4
Forecast Year: 1982 -  Forecast Month: 7
Dropping year: 1982  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
19      8  1981      0.927440 1981-08-01
20      9  1981      0.523972 1981-09-01
21     10  1981     -0.748537 1981-10-01
22     11  1981     -1.188138 1981-11-01
23     12  1981      0.398420 1981-12-01
24      1  1982     -1.551073 1982-01-01
25      2  1982      0.235052 1982-02-01
26      3  1982     -0.375811 1982-03-01
27      4  1982     -0.336847 1982-04-01
There are enough months in the past
Target period: 08-1981 to 04-1982
Target period includes two years

Year: 1982 - End-Month of observation: 5
Forecast Year: 1982 -  Forecast Month: 8
Dropping year: 1982  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
20      9  1981      0.523972 1981-09-01
21     10  1981     -0.748537 1981-10-01
22     11  1981     -1.188138 1981-11-01
23     12  1981      0.398420 1981-12-01
24      1  1982     -1.551073 1982-01-01
25      2  1982      0.235052 1982-02-01
26      3  1982     -0.375811 1982-03-01
27      4  1982     -0.336847 1982-04-01
28      5  1982      0.930711 1982-05-01
There are enough months in the past
Target period: 09-1981 to 05-1982
Target period includes two years

Year: 1982 - End-Month of observation: 6
Forecast Year: 1982 -  Forecast Month: 9
Dropping year: 1982  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
21     10  1981     -0.748537 1981-10-01
22     11  1981     -1.188138 1981-11-01
23     12  1981      0.398420 1981-12-01
24      1  1982     -1.551073 1982-01-01
25      2  1982      0.235052 1982-02-01
26      3  1982     -0.375811 1982-03-01
27      4  1982     -0.336847 1982-04-01
28      5  1982      0.930711 1982-05-01
29      6  1982      1.175735 1982-06-01
There are enough months in the past
Target period: 10-1981 to 06-1982
Target period includes two years

Year: 1982 - End-Month of observation: 7
Forecast Year: 1982 -  Forecast Month: 10
Dropping year: 1982  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
22     11  1981     -1.188138 1981-11-01
23     12  1981      0.398420 1981-12-01
24      1  1982     -1.551073 1982-01-01
25      2  1982      0.235052 1982-02-01
26      3  1982     -0.375811 1982-03-01
27      4  1982     -0.336847 1982-04-01
28      5  1982      0.930711 1982-05-01
29      6  1982      1.175735 1982-06-01
30      7  1982      0.605223 1982-07-01
There are enough months in the past
Target period: 11-1981 to 07-1982
Target period includes two years

Year: 1982 - End-Month of observation: 8
Forecast Year: 1982 -  Forecast Month: 11
Dropping year: 1982  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
23     12  1981      0.398420 1981-12-01
24      1  1982     -1.551073 1982-01-01
25      2  1982      0.235052 1982-02-01
26      3  1982     -0.375811 1982-03-01
27      4  1982     -0.336847 1982-04-01
28      5  1982      0.930711 1982-05-01
29      6  1982      1.175735 1982-06-01
30      7  1982      0.605223 1982-07-01
31      8  1982      0.726022 1982-08-01
There are enough months in the past
Target period: 12-1981 to 08-1982
Target period includes two years

Year: 1982 - End-Month of observation: 9
Forecast Year: 1982 -  Forecast Month: 12
Dropping year: 1982  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
24      1  1982     -1.551073 1982-01-01
25      2  1982      0.235052 1982-02-01
26      3  1982     -0.375811 1982-03-01
27      4  1982     -0.336847 1982-04-01
28      5  1982      0.930711 1982-05-01
29      6  1982      1.175735 1982-06-01
30      7  1982      0.605223 1982-07-01
31      8  1982      0.726022 1982-08-01
32      9  1982      0.384146 1982-09-01
There are enough months in the past
Target period: 01-1982 to 09-1982
Target period includes only one year

Year: 1982 - End-Month of observation: 10
Forecast Year: 1983 -  Forecast Month: 1
Dropping year: 1982  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
25      2  1982      0.235052 1982-02-01
26      3  1982     -0.375811 1982-03-01
27      4  1982     -0.336847 1982-04-01
28      5  1982      0.930711 1982-05-01
29      6  1982      1.175735 1982-06-01
30      7  1982      0.605223 1982-07-01
31      8  1982      0.726022 1982-08-01
32      9  1982      0.384146 1982-09-01
33     10  1982           NaN 1982-10-01
There are enough months in the past
Target period: 02-1982 to 10-1982
Target period includes only one year

Year: 1982 - End-Month of observation: 11
Forecast Year: 1983 -  Forecast Month: 2
Dropping year: 1982  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
26      3  1982     -0.375811 1982-03-01
27      4  1982     -0.336847 1982-04-01
28      5  1982      0.930711 1982-05-01
29      6  1982      1.175735 1982-06-01
30      7  1982      0.605223 1982-07-01
31      8  1982      0.726022 1982-08-01
32      9  1982      0.384146 1982-09-01
33     10  1982           NaN 1982-10-01
34     11  1982           NaN 1982-11-01
There are enough months in the past
Target period: 03-1982 to 11-1982
Target period includes only one year

Year: 1982 - End-Month of observation: 12
Forecast Year: 1983 -  Forecast Month: 3
Dropping year: 1982  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
27      4  1982     -0.336847 1982-04-01
28      5  1982      0.930711 1982-05-01
29      6  1982      1.175735 1982-06-01
30      7  1982      0.605223 1982-07-01
31      8  1982      0.726022 1982-08-01
32      9  1982      0.384146 1982-09-01
33     10  1982           NaN 1982-10-01
34     11  1982           NaN 1982-11-01
35     12  1982           NaN 1982-12-01
There are enough months in the past
Target period: 04-1982 to 12-1982
Target period includes only one year

Year: 1983 - End-Month of observation: 1
Forecast Year: 1983 -  Forecast Month: 4
Dropping year: 1983  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
28      5  1982      0.930711 1982-05-01
29      6  1982      1.175735 1982-06-01
30      7  1982      0.605223 1982-07-01
31      8  1982      0.726022 1982-08-01
32      9  1982      0.384146 1982-09-01
33     10  1982           NaN 1982-10-01
34     11  1982           NaN 1982-11-01
35     12  1982           NaN 1982-12-01
36      1  1983     -0.796712 1983-01-01
There are enough months in the past
Target period: 05-1982 to 01-1983
Target period includes two years

Year: 1983 - End-Month of observation: 2
Forecast Year: 1983 -  Forecast Month: 5
Dropping year: 1983  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
29      6  1982      1.175735 1982-06-01
30      7  1982      0.605223 1982-07-01
31      8  1982      0.726022 1982-08-01
32      9  1982      0.384146 1982-09-01
33     10  1982           NaN 1982-10-01
34     11  1982           NaN 1982-11-01
35     12  1982           NaN 1982-12-01
36      1  1983     -0.796712 1983-01-01
37      2  1983      0.100800 1983-02-01
There are enough months in the past
Target period: 06-1982 to 02-1983
Target period includes two years

Year: 1983 - End-Month of observation: 3
Forecast Year: 1983 -  Forecast Month: 6
Dropping year: 1983  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
30      7  1982      0.605223 1982-07-01
31      8  1982      0.726022 1982-08-01
32      9  1982      0.384146 1982-09-01
33     10  1982           NaN 1982-10-01
34     11  1982           NaN 1982-11-01
35     12  1982           NaN 1982-12-01
36      1  1983     -0.796712 1983-01-01
37      2  1983      0.100800 1983-02-01
38      3  1983     -0.951718 1983-03-01
There are enough months in the past
Target period: 07-1982 to 03-1983
Target period includes two years

Year: 1983 - End-Month of observation: 4
Forecast Year: 1983 -  Forecast Month: 7
Dropping year: 1983  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
31      8  1982      0.726022 1982-08-01
32      9  1982      0.384146 1982-09-01
33     10  1982           NaN 1982-10-01
34     11  1982           NaN 1982-11-01
35     12  1982           NaN 1982-12-01
36      1  1983     -0.796712 1983-01-01
37      2  1983      0.100800 1983-02-01
38      3  1983     -0.951718 1983-03-01
39      4  1983     -0.364767 1983-04-01
There are enough months in the past
Target period: 08-1982 to 04-1983
Target period includes two years

Year: 1983 - End-Month of observation: 5
Forecast Year: 1983 -  Forecast Month: 8
Dropping year: 1983  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
32      9  1982      0.384146 1982-09-01
33     10  1982           NaN 1982-10-01
34     11  1982           NaN 1982-11-01
35     12  1982           NaN 1982-12-01
36      1  1983     -0.796712 1983-01-01
37      2  1983      0.100800 1983-02-01
38      3  1983     -0.951718 1983-03-01
39      4  1983     -0.364767 1983-04-01
40      5  1983     -0.734193 1983-05-01
There are enough months in the past
Target period: 09-1982 to 05-1983
Target period includes two years

Year: 1983 - End-Month of observation: 6
Forecast Year: 1983 -  Forecast Month: 9
Dropping year: 1983  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
33     10  1982           NaN 1982-10-01
34     11  1982           NaN 1982-11-01
35     12  1982           NaN 1982-12-01
36      1  1983     -0.796712 1983-01-01
37      2  1983      0.100800 1983-02-01
38      3  1983     -0.951718 1983-03-01
39      4  1983     -0.364767 1983-04-01
40      5  1983     -0.734193 1983-05-01
41      6  1983      0.284660 1983-06-01
There are enough months in the past
Target period: 10-1982 to 06-1983
Target period includes two years

Year: 1983 - End-Month of observation: 7
Forecast Year: 1983 -  Forecast Month: 10
Dropping year: 1983  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
34     11  1982           NaN 1982-11-01
35     12  1982           NaN 1982-12-01
36      1  1983     -0.796712 1983-01-01
37      2  1983      0.100800 1983-02-01
38      3  1983     -0.951718 1983-03-01
39      4  1983     -0.364767 1983-04-01
40      5  1983     -0.734193 1983-05-01
41      6  1983      0.284660 1983-06-01
42      7  1983     -0.332697 1983-07-01
There are enough months in the past
Target period: 11-1982 to 07-1983
Target period includes two years

Year: 1983 - End-Month of observation: 8
Forecast Year: 1983 -  Forecast Month: 11
Dropping year: 1983  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
35     12  1982           NaN 1982-12-01
36      1  1983     -0.796712 1983-01-01
37      2  1983      0.100800 1983-02-01
38      3  1983     -0.951718 1983-03-01
39      4  1983     -0.364767 1983-04-01
40      5  1983     -0.734193 1983-05-01
41      6  1983      0.284660 1983-06-01
42      7  1983     -0.332697 1983-07-01
43      8  1983      1.307074 1983-08-01
There are enough months in the past
Target period: 12-1982 to 08-1983
Target period includes two years

Year: 1983 - End-Month of observation: 9
Forecast Year: 1983 -  Forecast Month: 12
Dropping year: 1983  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
36      1  1983     -0.796712 1983-01-01
37      2  1983      0.100800 1983-02-01
38      3  1983     -0.951718 1983-03-01
39      4  1983     -0.364767 1983-04-01
40      5  1983     -0.734193 1983-05-01
41      6  1983      0.284660 1983-06-01
42      7  1983     -0.332697 1983-07-01
43      8  1983      1.307074 1983-08-01
44      9  1983      1.468819 1983-09-01
There are enough months in the past
Target period: 01-1983 to 09-1983
Target period includes only one year

Year: 1983 - End-Month of observation: 10
Forecast Year: 1984 -  Forecast Month: 1
Dropping year: 1983  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
37      2  1983      0.100800 1983-02-01
38      3  1983     -0.951718 1983-03-01
39      4  1983     -0.364767 1983-04-01
40      5  1983     -0.734193 1983-05-01
41      6  1983      0.284660 1983-06-01
42      7  1983     -0.332697 1983-07-01
43      8  1983      1.307074 1983-08-01
44      9  1983      1.468819 1983-09-01
45     10  1983      1.573028 1983-10-01
There are enough months in the past
Target period: 02-1983 to 10-1983
Target period includes only one year

Year: 1983 - End-Month of observation: 11
Forecast Year: 1984 -  Forecast Month: 2
Dropping year: 1983  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
38      3  1983     -0.951718 1983-03-01
39      4  1983     -0.364767 1983-04-01
40      5  1983     -0.734193 1983-05-01
41      6  1983      0.284660 1983-06-01
42      7  1983     -0.332697 1983-07-01
43      8  1983      1.307074 1983-08-01
44      9  1983      1.468819 1983-09-01
45     10  1983      1.573028 1983-10-01
46     11  1983      1.199867 1983-11-01
There are enough months in the past
Target period: 03-1983 to 11-1983
Target period includes only one year

Year: 1983 - End-Month of observation: 12
Forecast Year: 1984 -  Forecast Month: 3
Dropping year: 1983  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
39      4  1983     -0.364767 1983-04-01
40      5  1983     -0.734193 1983-05-01
41      6  1983      0.284660 1983-06-01
42      7  1983     -0.332697 1983-07-01
43      8  1983      1.307074 1983-08-01
44      9  1983      1.468819 1983-09-01
45     10  1983      1.573028 1983-10-01
46     11  1983      1.199867 1983-11-01
47     12  1983     -0.256680 1983-12-01
There are enough months in the past
Target period: 04-1983 to 12-1983
Target period includes only one year

Year: 1984 - End-Month of observation: 1
Forecast Year: 1984 -  Forecast Month: 4
Dropping year: 1984  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
40      5  1983     -0.734193 1983-05-01
41      6  1983      0.284660 1983-06-01
42      7  1983     -0.332697 1983-07-01
43      8  1983      1.307074 1983-08-01
44      9  1983      1.468819 1983-09-01
45     10  1983      1.573028 1983-10-01
46     11  1983      1.199867 1983-11-01
47     12  1983     -0.256680 1983-12-01
48      1  1984      0.727208 1984-01-01
There are enough months in the past
Target period: 05-1983 to 01-1984
Target period includes two years

Year: 1984 - End-Month of observation: 2
Forecast Year: 1984 -  Forecast Month: 5
Dropping year: 1984  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
41      6  1983      0.284660 1983-06-01
42      7  1983     -0.332697 1983-07-01
43      8  1983      1.307074 1983-08-01
44      9  1983      1.468819 1983-09-01
45     10  1983      1.573028 1983-10-01
46     11  1983      1.199867 1983-11-01
47     12  1983     -0.256680 1983-12-01
48      1  1984      0.727208 1984-01-01
49      2  1984      2.454052 1984-02-01
There are enough months in the past
Target period: 06-1983 to 02-1984
Target period includes two years

Year: 1984 - End-Month of observation: 3
Forecast Year: 1984 -  Forecast Month: 6
Dropping year: 1984  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
42      7  1983     -0.332697 1983-07-01
43      8  1983      1.307074 1983-08-01
44      9  1983      1.468819 1983-09-01
45     10  1983      1.573028 1983-10-01
46     11  1983      1.199867 1983-11-01
47     12  1983     -0.256680 1983-12-01
48      1  1984      0.727208 1984-01-01
49      2  1984      2.454052 1984-02-01
50      3  1984      1.193772 1984-03-01
There are enough months in the past
Target period: 07-1983 to 03-1984
Target period includes two years

Year: 1984 - End-Month of observation: 4
Forecast Year: 1984 -  Forecast Month: 7
Dropping year: 1984  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
43      8  1983      1.307074 1983-08-01
44      9  1983      1.468819 1983-09-01
45     10  1983      1.573028 1983-10-01
46     11  1983      1.199867 1983-11-01
47     12  1983     -0.256680 1983-12-01
48      1  1984      0.727208 1984-01-01
49      2  1984      2.454052 1984-02-01
50      3  1984      1.193772 1984-03-01
51      4  1984     -0.160803 1984-04-01
There are enough months in the past
Target period: 08-1983 to 04-1984
Target period includes two years

Year: 1984 - End-Month of observation: 5
Forecast Year: 1984 -  Forecast Month: 8
Dropping year: 1984  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
44      9  1983      1.468819 1983-09-01
45     10  1983      1.573028 1983-10-01
46     11  1983      1.199867 1983-11-01
47     12  1983     -0.256680 1983-12-01
48      1  1984      0.727208 1984-01-01
49      2  1984      2.454052 1984-02-01
50      3  1984      1.193772 1984-03-01
51      4  1984     -0.160803 1984-04-01
52      5  1984      0.722645 1984-05-01
There are enough months in the past
Target period: 09-1983 to 05-1984
Target period includes two years

Year: 1984 - End-Month of observation: 6
Forecast Year: 1984 -  Forecast Month: 9
Dropping year: 1984  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
45     10  1983      1.573028 1983-10-01
46     11  1983      1.199867 1983-11-01
47     12  1983     -0.256680 1983-12-01
48      1  1984      0.727208 1984-01-01
49      2  1984      2.454052 1984-02-01
50      3  1984      1.193772 1984-03-01
51      4  1984     -0.160803 1984-04-01
52      5  1984      0.722645 1984-05-01
53      6  1984      1.159690 1984-06-01
There are enough months in the past
Target period: 10-1983 to 06-1984
Target period includes two years

Year: 1984 - End-Month of observation: 7
Forecast Year: 1984 -  Forecast Month: 10
Dropping year: 1984  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
46     11  1983      1.199867 1983-11-01
47     12  1983     -0.256680 1983-12-01
48      1  1984      0.727208 1984-01-01
49      2  1984      2.454052 1984-02-01
50      3  1984      1.193772 1984-03-01
51      4  1984     -0.160803 1984-04-01
52      5  1984      0.722645 1984-05-01
53      6  1984      1.159690 1984-06-01
54      7  1984      1.575762 1984-07-01
There are enough months in the past
Target period: 11-1983 to 07-1984
Target period includes two years

Year: 1984 - End-Month of observation: 8
Forecast Year: 1984 -  Forecast Month: 11
Dropping year: 1984  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
47     12  1983     -0.256680 1983-12-01
48      1  1984      0.727208 1984-01-01
49      2  1984      2.454052 1984-02-01
50      3  1984      1.193772 1984-03-01
51      4  1984     -0.160803 1984-04-01
52      5  1984      0.722645 1984-05-01
53      6  1984      1.159690 1984-06-01
54      7  1984      1.575762 1984-07-01
55      8  1984     -0.886873 1984-08-01
There are enough months in the past
Target period: 12-1983 to 08-1984
Target period includes two years

Year: 1984 - End-Month of observation: 9
Forecast Year: 1984 -  Forecast Month: 12
Dropping year: 1984  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
48      1  1984      0.727208 1984-01-01
49      2  1984      2.454052 1984-02-01
50      3  1984      1.193772 1984-03-01
51      4  1984     -0.160803 1984-04-01
52      5  1984      0.722645 1984-05-01
53      6  1984      1.159690 1984-06-01
54      7  1984      1.575762 1984-07-01
55      8  1984     -0.886873 1984-08-01
56      9  1984     -0.124697 1984-09-01
There are enough months in the past
Target period: 01-1984 to 09-1984
Target period includes only one year

Year: 1984 - End-Month of observation: 10
Forecast Year: 1985 -  Forecast Month: 1
Dropping year: 1984  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
49      2  1984      2.454052 1984-02-01
50      3  1984      1.193772 1984-03-01
51      4  1984     -0.160803 1984-04-01
52      5  1984      0.722645 1984-05-01
53      6  1984      1.159690 1984-06-01
54      7  1984      1.575762 1984-07-01
55      8  1984     -0.886873 1984-08-01
56      9  1984     -0.124697 1984-09-01
57     10  1984      0.291037 1984-10-01
There are enough months in the past
Target period: 02-1984 to 10-1984
Target period includes only one year

Year: 1984 - End-Month of observation: 11
Forecast Year: 1985 -  Forecast Month: 2
Dropping year: 1984  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
50      3  1984      1.193772 1984-03-01
51      4  1984     -0.160803 1984-04-01
52      5  1984      0.722645 1984-05-01
53      6  1984      1.159690 1984-06-01
54      7  1984      1.575762 1984-07-01
55      8  1984     -0.886873 1984-08-01
56      9  1984     -0.124697 1984-09-01
57     10  1984      0.291037 1984-10-01
58     11  1984      1.158132 1984-11-01
There are enough months in the past
Target period: 03-1984 to 11-1984
Target period includes only one year

Year: 1984 - End-Month of observation: 12
Forecast Year: 1985 -  Forecast Month: 3
Dropping year: 1984  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
51      4  1984     -0.160803 1984-04-01
52      5  1984      0.722645 1984-05-01
53      6  1984      1.159690 1984-06-01
54      7  1984      1.575762 1984-07-01
55      8  1984     -0.886873 1984-08-01
56      9  1984     -0.124697 1984-09-01
57     10  1984      0.291037 1984-10-01
58     11  1984      1.158132 1984-11-01
59     12  1984     -0.942096 1984-12-01
There are enough months in the past
Target period: 04-1984 to 12-1984
Target period includes only one year

Year: 1985 - End-Month of observation: 1
Forecast Year: 1985 -  Forecast Month: 4
Dropping year: 1985  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
52      5  1984      0.722645 1984-05-01
53      6  1984      1.159690 1984-06-01
54      7  1984      1.575762 1984-07-01
55      8  1984     -0.886873 1984-08-01
56      9  1984     -0.124697 1984-09-01
57     10  1984      0.291037 1984-10-01
58     11  1984      1.158132 1984-11-01
59     12  1984     -0.942096 1984-12-01
60      1  1985     -1.244110 1985-01-01
There are enough months in the past
Target period: 05-1984 to 01-1985
Target period includes two years

Year: 1985 - End-Month of observation: 2
Forecast Year: 1985 -  Forecast Month: 5
Dropping year: 1985  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
53      6  1984      1.159690 1984-06-01
54      7  1984      1.575762 1984-07-01
55      8  1984     -0.886873 1984-08-01
56      9  1984     -0.124697 1984-09-01
57     10  1984      0.291037 1984-10-01
58     11  1984      1.158132 1984-11-01
59     12  1984     -0.942096 1984-12-01
60      1  1985     -1.244110 1985-01-01
61      2  1985     -1.259258 1985-02-01
There are enough months in the past
Target period: 06-1984 to 02-1985
Target period includes two years

Year: 1985 - End-Month of observation: 3
Forecast Year: 1985 -  Forecast Month: 6
Dropping year: 1985  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
54      7  1984      1.575762 1984-07-01
55      8  1984     -0.886873 1984-08-01
56      9  1984     -0.124697 1984-09-01
57     10  1984      0.291037 1984-10-01
58     11  1984      1.158132 1984-11-01
59     12  1984     -0.942096 1984-12-01
60      1  1985     -1.244110 1985-01-01
61      2  1985     -1.259258 1985-02-01
62      3  1985      0.744396 1985-03-01
There are enough months in the past
Target period: 07-1984 to 03-1985
Target period includes two years

Year: 1985 - End-Month of observation: 4
Forecast Year: 1985 -  Forecast Month: 7
Dropping year: 1985  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
55      8  1984     -0.886873 1984-08-01
56      9  1984     -0.124697 1984-09-01
57     10  1984      0.291037 1984-10-01
58     11  1984      1.158132 1984-11-01
59     12  1984     -0.942096 1984-12-01
60      1  1985     -1.244110 1985-01-01
61      2  1985     -1.259258 1985-02-01
62      3  1985      0.744396 1985-03-01
63      4  1985      0.583685 1985-04-01
There are enough months in the past
Target period: 08-1984 to 04-1985
Target period includes two years

Year: 1985 - End-Month of observation: 5
Forecast Year: 1985 -  Forecast Month: 8
Dropping year: 1985  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
56      9  1984     -0.124697 1984-09-01
57     10  1984      0.291037 1984-10-01
58     11  1984      1.158132 1984-11-01
59     12  1984     -0.942096 1984-12-01
60      1  1985     -1.244110 1985-01-01
61      2  1985     -1.259258 1985-02-01
62      3  1985      0.744396 1985-03-01
63      4  1985      0.583685 1985-04-01
64      5  1985      0.782769 1985-05-01
There are enough months in the past
Target period: 09-1984 to 05-1985
Target period includes two years

Year: 1985 - End-Month of observation: 6
Forecast Year: 1985 -  Forecast Month: 9
Dropping year: 1985  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
57     10  1984      0.291037 1984-10-01
58     11  1984      1.158132 1984-11-01
59     12  1984     -0.942096 1984-12-01
60      1  1985     -1.244110 1985-01-01
61      2  1985     -1.259258 1985-02-01
62      3  1985      0.744396 1985-03-01
63      4  1985      0.583685 1985-04-01
64      5  1985      0.782769 1985-05-01
65      6  1985      0.689027 1985-06-01
There are enough months in the past
Target period: 10-1984 to 06-1985
Target period includes two years

Year: 1985 - End-Month of observation: 7
Forecast Year: 1985 -  Forecast Month: 10
Dropping year: 1985  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
58     11  1984      1.158132 1984-11-01
59     12  1984     -0.942096 1984-12-01
60      1  1985     -1.244110 1985-01-01
61      2  1985     -1.259258 1985-02-01
62      3  1985      0.744396 1985-03-01
63      4  1985      0.583685 1985-04-01
64      5  1985      0.782769 1985-05-01
65      6  1985      0.689027 1985-06-01
66      7  1985      0.619012 1985-07-01
There are enough months in the past
Target period: 11-1984 to 07-1985
Target period includes two years

Year: 1985 - End-Month of observation: 8
Forecast Year: 1985 -  Forecast Month: 11
Dropping year: 1985  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
59     12  1984     -0.942096 1984-12-01
60      1  1985     -1.244110 1985-01-01
61      2  1985     -1.259258 1985-02-01
62      3  1985      0.744396 1985-03-01
63      4  1985      0.583685 1985-04-01
64      5  1985      0.782769 1985-05-01
65      6  1985      0.689027 1985-06-01
66      7  1985      0.619012 1985-07-01
67      8  1985      0.710619 1985-08-01
There are enough months in the past
Target period: 12-1984 to 08-1985
Target period includes two years

Year: 1985 - End-Month of observation: 9
Forecast Year: 1985 -  Forecast Month: 12
Dropping year: 1985  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
60      1  1985     -1.244110 1985-01-01
61      2  1985     -1.259258 1985-02-01
62      3  1985      0.744396 1985-03-01
63      4  1985      0.583685 1985-04-01
64      5  1985      0.782769 1985-05-01
65      6  1985      0.689027 1985-06-01
66      7  1985      0.619012 1985-07-01
67      8  1985      0.710619 1985-08-01
68      9  1985      0.380196 1985-09-01
There are enough months in the past
Target period: 01-1985 to 09-1985
Target period includes only one year

Year: 1985 - End-Month of observation: 10
Forecast Year: 1986 -  Forecast Month: 1
Dropping year: 1985  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
61      2  1985     -1.259258 1985-02-01
62      3  1985      0.744396 1985-03-01
63      4  1985      0.583685 1985-04-01
64      5  1985      0.782769 1985-05-01
65      6  1985      0.689027 1985-06-01
66      7  1985      0.619012 1985-07-01
67      8  1985      0.710619 1985-08-01
68      9  1985      0.380196 1985-09-01
69     10  1985      0.794642 1985-10-01
There are enough months in the past
Target period: 02-1985 to 10-1985
Target period includes only one year

Year: 1985 - End-Month of observation: 11
Forecast Year: 1986 -  Forecast Month: 2
Dropping year: 1985  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
62      3  1985      0.744396 1985-03-01
63      4  1985      0.583685 1985-04-01
64      5  1985      0.782769 1985-05-01
65      6  1985      0.689027 1985-06-01
66      7  1985      0.619012 1985-07-01
67      8  1985      0.710619 1985-08-01
68      9  1985      0.380196 1985-09-01
69     10  1985      0.794642 1985-10-01
70     11  1985      0.633891 1985-11-01
There are enough months in the past
Target period: 03-1985 to 11-1985
Target period includes only one year

Year: 1985 - End-Month of observation: 12
Forecast Year: 1986 -  Forecast Month: 3
Dropping year: 1985  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
63      4  1985      0.583685 1985-04-01
64      5  1985      0.782769 1985-05-01
65      6  1985      0.689027 1985-06-01
66      7  1985      0.619012 1985-07-01
67      8  1985      0.710619 1985-08-01
68      9  1985      0.380196 1985-09-01
69     10  1985      0.794642 1985-10-01
70     11  1985      0.633891 1985-11-01
71     12  1985     -0.750703 1985-12-01
There are enough months in the past
Target period: 04-1985 to 12-1985
Target period includes only one year

Year: 1986 - End-Month of observation: 1
Forecast Year: 1986 -  Forecast Month: 4
Dropping year: 1986  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
64      5  1985      0.782769 1985-05-01
65      6  1985      0.689027 1985-06-01
66      7  1985      0.619012 1985-07-01
67      8  1985      0.710619 1985-08-01
68      9  1985      0.380196 1985-09-01
69     10  1985      0.794642 1985-10-01
70     11  1985      0.633891 1985-11-01
71     12  1985     -0.750703 1985-12-01
72      1  1986     -0.670261 1986-01-01
There are enough months in the past
Target period: 05-1985 to 01-1986
Target period includes two years

Year: 1986 - End-Month of observation: 2
Forecast Year: 1986 -  Forecast Month: 5
Dropping year: 1986  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
65      6  1985      0.689027 1985-06-01
66      7  1985      0.619012 1985-07-01
67      8  1985      0.710619 1985-08-01
68      9  1985      0.380196 1985-09-01
69     10  1985      0.794642 1985-10-01
70     11  1985      0.633891 1985-11-01
71     12  1985     -0.750703 1985-12-01
72      1  1986     -0.670261 1986-01-01
73      2  1986     -0.370705 1986-02-01
There are enough months in the past
Target period: 06-1985 to 02-1986
Target period includes two years

Year: 1986 - End-Month of observation: 3
Forecast Year: 1986 -  Forecast Month: 6
Dropping year: 1986  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
66      7  1985      0.619012 1985-07-01
67      8  1985      0.710619 1985-08-01
68      9  1985      0.380196 1985-09-01
69     10  1985      0.794642 1985-10-01
70     11  1985      0.633891 1985-11-01
71     12  1985     -0.750703 1985-12-01
72      1  1986     -0.670261 1986-01-01
73      2  1986     -0.370705 1986-02-01
74      3  1986     -0.898463 1986-03-01
There are enough months in the past
Target period: 07-1985 to 03-1986
Target period includes two years

Year: 1986 - End-Month of observation: 4
Forecast Year: 1986 -  Forecast Month: 7
Dropping year: 1986  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
67      8  1985      0.710619 1985-08-01
68      9  1985      0.380196 1985-09-01
69     10  1985      0.794642 1985-10-01
70     11  1985      0.633891 1985-11-01
71     12  1985     -0.750703 1985-12-01
72      1  1986     -0.670261 1986-01-01
73      2  1986     -0.370705 1986-02-01
74      3  1986     -0.898463 1986-03-01
75      4  1986     -0.569182 1986-04-01
There are enough months in the past
Target period: 08-1985 to 04-1986
Target period includes two years

Year: 1986 - End-Month of observation: 5
Forecast Year: 1986 -  Forecast Month: 8
Dropping year: 1986  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
68      9  1985      0.380196 1985-09-01
69     10  1985      0.794642 1985-10-01
70     11  1985      0.633891 1985-11-01
71     12  1985     -0.750703 1985-12-01
72      1  1986     -0.670261 1986-01-01
73      2  1986     -0.370705 1986-02-01
74      3  1986     -0.898463 1986-03-01
75      4  1986     -0.569182 1986-04-01
76      5  1986      0.315669 1986-05-01
There are enough months in the past
Target period: 09-1985 to 05-1986
Target period includes two years

Year: 1986 - End-Month of observation: 6
Forecast Year: 1986 -  Forecast Month: 9
Dropping year: 1986  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
69     10  1985      0.794642 1985-10-01
70     11  1985      0.633891 1985-11-01
71     12  1985     -0.750703 1985-12-01
72      1  1986     -0.670261 1986-01-01
73      2  1986     -0.370705 1986-02-01
74      3  1986     -0.898463 1986-03-01
75      4  1986     -0.569182 1986-04-01
76      5  1986      0.315669 1986-05-01
77      6  1986      0.508366 1986-06-01
There are enough months in the past
Target period: 10-1985 to 06-1986
Target period includes two years

Year: 1986 - End-Month of observation: 7
Forecast Year: 1986 -  Forecast Month: 10
Dropping year: 1986  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
70     11  1985      0.633891 1985-11-01
71     12  1985     -0.750703 1985-12-01
72      1  1986     -0.670261 1986-01-01
73      2  1986     -0.370705 1986-02-01
74      3  1986     -0.898463 1986-03-01
75      4  1986     -0.569182 1986-04-01
76      5  1986      0.315669 1986-05-01
77      6  1986      0.508366 1986-06-01
78      7  1986      0.095685 1986-07-01
There are enough months in the past
Target period: 11-1985 to 07-1986
Target period includes two years

Year: 1986 - End-Month of observation: 8
Forecast Year: 1986 -  Forecast Month: 11
Dropping year: 1986  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
71     12  1985     -0.750703 1985-12-01
72      1  1986     -0.670261 1986-01-01
73      2  1986     -0.370705 1986-02-01
74      3  1986     -0.898463 1986-03-01
75      4  1986     -0.569182 1986-04-01
76      5  1986      0.315669 1986-05-01
77      6  1986      0.508366 1986-06-01
78      7  1986      0.095685 1986-07-01
79      8  1986      2.020854 1986-08-01
There are enough months in the past
Target period: 12-1985 to 08-1986
Target period includes two years

Year: 1986 - End-Month of observation: 9
Forecast Year: 1986 -  Forecast Month: 12
Dropping year: 1986  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
72      1  1986     -0.670261 1986-01-01
73      2  1986     -0.370705 1986-02-01
74      3  1986     -0.898463 1986-03-01
75      4  1986     -0.569182 1986-04-01
76      5  1986      0.315669 1986-05-01
77      6  1986      0.508366 1986-06-01
78      7  1986      0.095685 1986-07-01
79      8  1986      2.020854 1986-08-01
80      9  1986      0.927865 1986-09-01
There are enough months in the past
Target period: 01-1986 to 09-1986
Target period includes only one year

Year: 1986 - End-Month of observation: 10
Forecast Year: 1987 -  Forecast Month: 1
Dropping year: 1986  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
73      2  1986     -0.370705 1986-02-01
74      3  1986     -0.898463 1986-03-01
75      4  1986     -0.569182 1986-04-01
76      5  1986      0.315669 1986-05-01
77      6  1986      0.508366 1986-06-01
78      7  1986      0.095685 1986-07-01
79      8  1986      2.020854 1986-08-01
80      9  1986      0.927865 1986-09-01
81     10  1986      0.913218 1986-10-01
There are enough months in the past
Target period: 02-1986 to 10-1986
Target period includes only one year

Year: 1986 - End-Month of observation: 11
Forecast Year: 1987 -  Forecast Month: 2
Dropping year: 1986  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
74      3  1986     -0.898463 1986-03-01
75      4  1986     -0.569182 1986-04-01
76      5  1986      0.315669 1986-05-01
77      6  1986      0.508366 1986-06-01
78      7  1986      0.095685 1986-07-01
79      8  1986      2.020854 1986-08-01
80      9  1986      0.927865 1986-09-01
81     10  1986      0.913218 1986-10-01
82     11  1986      1.610914 1986-11-01
There are enough months in the past
Target period: 03-1986 to 11-1986
Target period includes only one year

Year: 1986 - End-Month of observation: 12
Forecast Year: 1987 -  Forecast Month: 3
Dropping year: 1986  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
75      4  1986     -0.569182 1986-04-01
76      5  1986      0.315669 1986-05-01
77      6  1986      0.508366 1986-06-01
78      7  1986      0.095685 1986-07-01
79      8  1986      2.020854 1986-08-01
80      9  1986      0.927865 1986-09-01
81     10  1986      0.913218 1986-10-01
82     11  1986      1.610914 1986-11-01
83     12  1986      0.498030 1986-12-01
There are enough months in the past
Target period: 04-1986 to 12-1986
Target period includes only one year

Year: 1987 - End-Month of observation: 1
Forecast Year: 1987 -  Forecast Month: 4
Dropping year: 1987  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
76      5  1986      0.315669 1986-05-01
77      6  1986      0.508366 1986-06-01
78      7  1986      0.095685 1986-07-01
79      8  1986      2.020854 1986-08-01
80      9  1986      0.927865 1986-09-01
81     10  1986      0.913218 1986-10-01
82     11  1986      1.610914 1986-11-01
83     12  1986      0.498030 1986-12-01
84      1  1987     -0.504405 1987-01-01
There are enough months in the past
Target period: 05-1986 to 01-1987
Target period includes two years

Year: 1987 - End-Month of observation: 2
Forecast Year: 1987 -  Forecast Month: 5
Dropping year: 1987  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
77      6  1986      0.508366 1986-06-01
78      7  1986      0.095685 1986-07-01
79      8  1986      2.020854 1986-08-01
80      9  1986      0.927865 1986-09-01
81     10  1986      0.913218 1986-10-01
82     11  1986      1.610914 1986-11-01
83     12  1986      0.498030 1986-12-01
84      1  1987     -0.504405 1987-01-01
85      2  1987     -0.773939 1987-02-01
There are enough months in the past
Target period: 06-1986 to 02-1987
Target period includes two years

Year: 1987 - End-Month of observation: 3
Forecast Year: 1987 -  Forecast Month: 6
Dropping year: 1987  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
78      7  1986      0.095685 1986-07-01
79      8  1986      2.020854 1986-08-01
80      9  1986      0.927865 1986-09-01
81     10  1986      0.913218 1986-10-01
82     11  1986      1.610914 1986-11-01
83     12  1986      0.498030 1986-12-01
84      1  1987     -0.504405 1987-01-01
85      2  1987     -0.773939 1987-02-01
86      3  1987      0.402005 1987-03-01
There are enough months in the past
Target period: 07-1986 to 03-1987
Target period includes two years

Year: 1987 - End-Month of observation: 4
Forecast Year: 1987 -  Forecast Month: 7
Dropping year: 1987  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
79      8  1986      2.020854 1986-08-01
80      9  1986      0.927865 1986-09-01
81     10  1986      0.913218 1986-10-01
82     11  1986      1.610914 1986-11-01
83     12  1986      0.498030 1986-12-01
84      1  1987     -0.504405 1987-01-01
85      2  1987     -0.773939 1987-02-01
86      3  1987      0.402005 1987-03-01
87      4  1987     -0.573368 1987-04-01
There are enough months in the past
Target period: 08-1986 to 04-1987
Target period includes two years

Year: 1987 - End-Month of observation: 5
Forecast Year: 1987 -  Forecast Month: 8
Dropping year: 1987  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
80      9  1986      0.927865 1986-09-01
81     10  1986      0.913218 1986-10-01
82     11  1986      1.610914 1986-11-01
83     12  1986      0.498030 1986-12-01
84      1  1987     -0.504405 1987-01-01
85      2  1987     -0.773939 1987-02-01
86      3  1987      0.402005 1987-03-01
87      4  1987     -0.573368 1987-04-01
88      5  1987     -0.976373 1987-05-01
There are enough months in the past
Target period: 09-1986 to 05-1987
Target period includes two years

Year: 1987 - End-Month of observation: 6
Forecast Year: 1987 -  Forecast Month: 9
Dropping year: 1987  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
81     10  1986      0.913218 1986-10-01
82     11  1986      1.610914 1986-11-01
83     12  1986      0.498030 1986-12-01
84      1  1987     -0.504405 1987-01-01
85      2  1987     -0.773939 1987-02-01
86      3  1987      0.402005 1987-03-01
87      4  1987     -0.573368 1987-04-01
88      5  1987     -0.976373 1987-05-01
89      6  1987     -1.715410 1987-06-01
There are enough months in the past
Target period: 10-1986 to 06-1987
Target period includes two years

Year: 1987 - End-Month of observation: 7
Forecast Year: 1987 -  Forecast Month: 10
Dropping year: 1987  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
82     11  1986      1.610914 1986-11-01
83     12  1986      0.498030 1986-12-01
84      1  1987     -0.504405 1987-01-01
85      2  1987     -0.773939 1987-02-01
86      3  1987      0.402005 1987-03-01
87      4  1987     -0.573368 1987-04-01
88      5  1987     -0.976373 1987-05-01
89      6  1987     -1.715410 1987-06-01
90      7  1987     -0.033314 1987-07-01
There are enough months in the past
Target period: 11-1986 to 07-1987
Target period includes two years

Year: 1987 - End-Month of observation: 8
Forecast Year: 1987 -  Forecast Month: 11
Dropping year: 1987  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
83     12  1986      0.498030 1986-12-01
84      1  1987     -0.504405 1987-01-01
85      2  1987     -0.773939 1987-02-01
86      3  1987      0.402005 1987-03-01
87      4  1987     -0.573368 1987-04-01
88      5  1987     -0.976373 1987-05-01
89      6  1987     -1.715410 1987-06-01
90      7  1987     -0.033314 1987-07-01
91      8  1987     -0.018238 1987-08-01
There are enough months in the past
Target period: 12-1986 to 08-1987
Target period includes two years

Year: 1987 - End-Month of observation: 9
Forecast Year: 1987 -  Forecast Month: 12
Dropping year: 1987  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
84      1  1987     -0.504405 1987-01-01
85      2  1987     -0.773939 1987-02-01
86      3  1987      0.402005 1987-03-01
87      4  1987     -0.573368 1987-04-01
88      5  1987     -0.976373 1987-05-01
89      6  1987     -1.715410 1987-06-01
90      7  1987     -0.033314 1987-07-01
91      8  1987     -0.018238 1987-08-01
92      9  1987     -0.596046 1987-09-01
There are enough months in the past
Target period: 01-1987 to 09-1987
Target period includes only one year

Year: 1987 - End-Month of observation: 10
Forecast Year: 1988 -  Forecast Month: 1
Dropping year: 1987  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
85      2  1987     -0.773939 1987-02-01
86      3  1987      0.402005 1987-03-01
87      4  1987     -0.573368 1987-04-01
88      5  1987     -0.976373 1987-05-01
89      6  1987     -1.715410 1987-06-01
90      7  1987     -0.033314 1987-07-01
91      8  1987     -0.018238 1987-08-01
92      9  1987     -0.596046 1987-09-01
93     10  1987      0.584085 1987-10-01
There are enough months in the past
Target period: 02-1987 to 10-1987
Target period includes only one year

Year: 1987 - End-Month of observation: 11
Forecast Year: 1988 -  Forecast Month: 2
Dropping year: 1987  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
86      3  1987      0.402005 1987-03-01
87      4  1987     -0.573368 1987-04-01
88      5  1987     -0.976373 1987-05-01
89      6  1987     -1.715410 1987-06-01
90      7  1987     -0.033314 1987-07-01
91      8  1987     -0.018238 1987-08-01
92      9  1987     -0.596046 1987-09-01
93     10  1987      0.584085 1987-10-01
94     11  1987     -0.415193 1987-11-01
There are enough months in the past
Target period: 03-1987 to 11-1987
Target period includes only one year

Year: 1987 - End-Month of observation: 12
Forecast Year: 1988 -  Forecast Month: 3
Dropping year: 1987  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
87      4  1987     -0.573368 1987-04-01
88      5  1987     -0.976373 1987-05-01
89      6  1987     -1.715410 1987-06-01
90      7  1987     -0.033314 1987-07-01
91      8  1987     -0.018238 1987-08-01
92      9  1987     -0.596046 1987-09-01
93     10  1987      0.584085 1987-10-01
94     11  1987     -0.415193 1987-11-01
95     12  1987     -0.413689 1987-12-01
There are enough months in the past
Target period: 04-1987 to 12-1987
Target period includes only one year

Year: 1988 - End-Month of observation: 1
Forecast Year: 1988 -  Forecast Month: 4
Dropping year: 1988  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
88      5  1987     -0.976373 1987-05-01
89      6  1987     -1.715410 1987-06-01
90      7  1987     -0.033314 1987-07-01
91      8  1987     -0.018238 1987-08-01
92      9  1987     -0.596046 1987-09-01
93     10  1987      0.584085 1987-10-01
94     11  1987     -0.415193 1987-11-01
95     12  1987     -0.413689 1987-12-01
96      1  1988      0.818331 1988-01-01
There are enough months in the past
Target period: 05-1987 to 01-1988
Target period includes two years

Year: 1988 - End-Month of observation: 2
Forecast Year: 1988 -  Forecast Month: 5
Dropping year: 1988  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
89      6  1987     -1.715410 1987-06-01
90      7  1987     -0.033314 1987-07-01
91      8  1987     -0.018238 1987-08-01
92      9  1987     -0.596046 1987-09-01
93     10  1987      0.584085 1987-10-01
94     11  1987     -0.415193 1987-11-01
95     12  1987     -0.413689 1987-12-01
96      1  1988      0.818331 1988-01-01
97      2  1988      0.187623 1988-02-01
There are enough months in the past
Target period: 06-1987 to 02-1988
Target period includes two years

Year: 1988 - End-Month of observation: 3
Forecast Year: 1988 -  Forecast Month: 6
Dropping year: 1988  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
90      7  1987     -0.033314 1987-07-01
91      8  1987     -0.018238 1987-08-01
92      9  1987     -0.596046 1987-09-01
93     10  1987      0.584085 1987-10-01
94     11  1987     -0.415193 1987-11-01
95     12  1987     -0.413689 1987-12-01
96      1  1988      0.818331 1988-01-01
97      2  1988      0.187623 1988-02-01
98      3  1988      1.742555 1988-03-01
There are enough months in the past
Target period: 07-1987 to 03-1988
Target period includes two years

Year: 1988 - End-Month of observation: 4
Forecast Year: 1988 -  Forecast Month: 7
Dropping year: 1988  - get series for analysis.
    Month  Year  Anomaly_Qlog       DATE
91      8  1987     -0.018238 1987-08-01
92      9  1987     -0.596046 1987-09-01
93     10  1987      0.584085 1987-10-01
94     11  1987     -0.415193 1987-11-01
95     12  1987     -0.413689 1987-12-01
96      1  1988      0.818331 1988-01-01
97      2  1988      0.187623 1988-02-01
98      3  1988      1.742555 1988-03-01
99      4  1988      0.695763 1988-04-01
There are enough months in the past
Target period: 08-1987 to 04-1988
Target period includes two years

Year: 1988 - End-Month of observation: 5
Forecast Year: 1988 -  Forecast Month: 8
Dropping year: 1988  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
92       9  1987     -0.596046 1987-09-01
93      10  1987      0.584085 1987-10-01
94      11  1987     -0.415193 1987-11-01
95      12  1987     -0.413689 1987-12-01
96       1  1988      0.818331 1988-01-01
97       2  1988      0.187623 1988-02-01
98       3  1988      1.742555 1988-03-01
99       4  1988      0.695763 1988-04-01
100      5  1988     -0.788636 1988-05-01
There are enough months in the past
Target period: 09-1987 to 05-1988
Target period includes two years

Year: 1988 - End-Month of observation: 6
Forecast Year: 1988 -  Forecast Month: 9
Dropping year: 1988  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
93      10  1987      0.584085 1987-10-01
94      11  1987     -0.415193 1987-11-01
95      12  1987     -0.413689 1987-12-01
96       1  1988      0.818331 1988-01-01
97       2  1988      0.187623 1988-02-01
98       3  1988      1.742555 1988-03-01
99       4  1988      0.695763 1988-04-01
100      5  1988     -0.788636 1988-05-01
101      6  1988     -1.236878 1988-06-01
There are enough months in the past
Target period: 10-1987 to 06-1988
Target period includes two years

Year: 1988 - End-Month of observation: 7
Forecast Year: 1988 -  Forecast Month: 10
Dropping year: 1988  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
94      11  1987     -0.415193 1987-11-01
95      12  1987     -0.413689 1987-12-01
96       1  1988      0.818331 1988-01-01
97       2  1988      0.187623 1988-02-01
98       3  1988      1.742555 1988-03-01
99       4  1988      0.695763 1988-04-01
100      5  1988     -0.788636 1988-05-01
101      6  1988     -1.236878 1988-06-01
102      7  1988     -0.667932 1988-07-01
There are enough months in the past
Target period: 11-1987 to 07-1988
Target period includes two years

Year: 1988 - End-Month of observation: 8
Forecast Year: 1988 -  Forecast Month: 11
Dropping year: 1988  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
95      12  1987     -0.413689 1987-12-01
96       1  1988      0.818331 1988-01-01
97       2  1988      0.187623 1988-02-01
98       3  1988      1.742555 1988-03-01
99       4  1988      0.695763 1988-04-01
100      5  1988     -0.788636 1988-05-01
101      6  1988     -1.236878 1988-06-01
102      7  1988     -0.667932 1988-07-01
103      8  1988     -0.082788 1988-08-01
There are enough months in the past
Target period: 12-1987 to 08-1988
Target period includes two years

Year: 1988 - End-Month of observation: 9
Forecast Year: 1988 -  Forecast Month: 12
Dropping year: 1988  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
96       1  1988      0.818331 1988-01-01
97       2  1988      0.187623 1988-02-01
98       3  1988      1.742555 1988-03-01
99       4  1988      0.695763 1988-04-01
100      5  1988     -0.788636 1988-05-01
101      6  1988     -1.236878 1988-06-01
102      7  1988     -0.667932 1988-07-01
103      8  1988     -0.082788 1988-08-01
104      9  1988     -1.185904 1988-09-01
There are enough months in the past
Target period: 01-1988 to 09-1988
Target period includes only one year

Year: 1988 - End-Month of observation: 10
Forecast Year: 1989 -  Forecast Month: 1
Dropping year: 1988  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
97       2  1988      0.187623 1988-02-01
98       3  1988      1.742555 1988-03-01
99       4  1988      0.695763 1988-04-01
100      5  1988     -0.788636 1988-05-01
101      6  1988     -1.236878 1988-06-01
102      7  1988     -0.667932 1988-07-01
103      8  1988     -0.082788 1988-08-01
104      9  1988     -1.185904 1988-09-01
105     10  1988     -1.280330 1988-10-01
There are enough months in the past
Target period: 02-1988 to 10-1988
Target period includes only one year

Year: 1988 - End-Month of observation: 11
Forecast Year: 1989 -  Forecast Month: 2
Dropping year: 1988  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
98       3  1988      1.742555 1988-03-01
99       4  1988      0.695763 1988-04-01
100      5  1988     -0.788636 1988-05-01
101      6  1988     -1.236878 1988-06-01
102      7  1988     -0.667932 1988-07-01
103      8  1988     -0.082788 1988-08-01
104      9  1988     -1.185904 1988-09-01
105     10  1988     -1.280330 1988-10-01
106     11  1988     -0.544928 1988-11-01
There are enough months in the past
Target period: 03-1988 to 11-1988
Target period includes only one year

Year: 1988 - End-Month of observation: 12
Forecast Year: 1989 -  Forecast Month: 3
Dropping year: 1988  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
99       4  1988      0.695763 1988-04-01
100      5  1988     -0.788636 1988-05-01
101      6  1988     -1.236878 1988-06-01
102      7  1988     -0.667932 1988-07-01
103      8  1988     -0.082788 1988-08-01
104      9  1988     -1.185904 1988-09-01
105     10  1988     -1.280330 1988-10-01
106     11  1988     -0.544928 1988-11-01
107     12  1988     -1.010211 1988-12-01
There are enough months in the past
Target period: 04-1988 to 12-1988
Target period includes only one year

Year: 1989 - End-Month of observation: 1
Forecast Year: 1989 -  Forecast Month: 4
Dropping year: 1989  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
100      5  1988     -0.788636 1988-05-01
101      6  1988     -1.236878 1988-06-01
102      7  1988     -0.667932 1988-07-01
103      8  1988     -0.082788 1988-08-01
104      9  1988     -1.185904 1988-09-01
105     10  1988     -1.280330 1988-10-01
106     11  1988     -0.544928 1988-11-01
107     12  1988     -1.010211 1988-12-01
108      1  1989     -1.280020 1989-01-01
There are enough months in the past
Target period: 05-1988 to 01-1989
Target period includes two years

Year: 1989 - End-Month of observation: 2
Forecast Year: 1989 -  Forecast Month: 5
Dropping year: 1989  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
101      6  1988     -1.236878 1988-06-01
102      7  1988     -0.667932 1988-07-01
103      8  1988     -0.082788 1988-08-01
104      9  1988     -1.185904 1988-09-01
105     10  1988     -1.280330 1988-10-01
106     11  1988     -0.544928 1988-11-01
107     12  1988     -1.010211 1988-12-01
108      1  1989     -1.280020 1989-01-01
109      2  1989     -1.368724 1989-02-01
There are enough months in the past
Target period: 06-1988 to 02-1989
Target period includes two years

Year: 1989 - End-Month of observation: 3
Forecast Year: 1989 -  Forecast Month: 6
Dropping year: 1989  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
102      7  1988     -0.667932 1988-07-01
103      8  1988     -0.082788 1988-08-01
104      9  1988     -1.185904 1988-09-01
105     10  1988     -1.280330 1988-10-01
106     11  1988     -0.544928 1988-11-01
107     12  1988     -1.010211 1988-12-01
108      1  1989     -1.280020 1989-01-01
109      2  1989     -1.368724 1989-02-01
110      3  1989     -0.994765 1989-03-01
There are enough months in the past
Target period: 07-1988 to 03-1989
Target period includes two years

Year: 1989 - End-Month of observation: 4
Forecast Year: 1989 -  Forecast Month: 7
Dropping year: 1989  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
103      8  1988     -0.082788 1988-08-01
104      9  1988     -1.185904 1988-09-01
105     10  1988     -1.280330 1988-10-01
106     11  1988     -0.544928 1988-11-01
107     12  1988     -1.010211 1988-12-01
108      1  1989     -1.280020 1989-01-01
109      2  1989     -1.368724 1989-02-01
110      3  1989     -0.994765 1989-03-01
111      4  1989     -0.983002 1989-04-01
There are enough months in the past
Target period: 08-1988 to 04-1989
Target period includes two years

Year: 1989 - End-Month of observation: 5
Forecast Year: 1989 -  Forecast Month: 8
Dropping year: 1989  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
104      9  1988     -1.185904 1988-09-01
105     10  1988     -1.280330 1988-10-01
106     11  1988     -0.544928 1988-11-01
107     12  1988     -1.010211 1988-12-01
108      1  1989     -1.280020 1989-01-01
109      2  1989     -1.368724 1989-02-01
110      3  1989     -0.994765 1989-03-01
111      4  1989     -0.983002 1989-04-01
112      5  1989     -1.846345 1989-05-01
There are enough months in the past
Target period: 09-1988 to 05-1989
Target period includes two years

Year: 1989 - End-Month of observation: 6
Forecast Year: 1989 -  Forecast Month: 9
Dropping year: 1989  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
105     10  1988     -1.280330 1988-10-01
106     11  1988     -0.544928 1988-11-01
107     12  1988     -1.010211 1988-12-01
108      1  1989     -1.280020 1989-01-01
109      2  1989     -1.368724 1989-02-01
110      3  1989     -0.994765 1989-03-01
111      4  1989     -0.983002 1989-04-01
112      5  1989     -1.846345 1989-05-01
113      6  1989     -2.084692 1989-06-01
There are enough months in the past
Target period: 10-1988 to 06-1989
Target period includes two years

Year: 1989 - End-Month of observation: 7
Forecast Year: 1989 -  Forecast Month: 10
Dropping year: 1989  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
106     11  1988     -0.544928 1988-11-01
107     12  1988     -1.010211 1988-12-01
108      1  1989     -1.280020 1989-01-01
109      2  1989     -1.368724 1989-02-01
110      3  1989     -0.994765 1989-03-01
111      4  1989     -0.983002 1989-04-01
112      5  1989     -1.846345 1989-05-01
113      6  1989     -2.084692 1989-06-01
114      7  1989     -1.610597 1989-07-01
There are enough months in the past
Target period: 11-1988 to 07-1989
Target period includes two years

Year: 1989 - End-Month of observation: 8
Forecast Year: 1989 -  Forecast Month: 11
Dropping year: 1989  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
107     12  1988     -1.010211 1988-12-01
108      1  1989     -1.280020 1989-01-01
109      2  1989     -1.368724 1989-02-01
110      3  1989     -0.994765 1989-03-01
111      4  1989     -0.983002 1989-04-01
112      5  1989     -1.846345 1989-05-01
113      6  1989     -2.084692 1989-06-01
114      7  1989     -1.610597 1989-07-01
115      8  1989     -0.035092 1989-08-01
There are enough months in the past
Target period: 12-1988 to 08-1989
Target period includes two years

Year: 1989 - End-Month of observation: 9
Forecast Year: 1989 -  Forecast Month: 12
Dropping year: 1989  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
108      1  1989     -1.280020 1989-01-01
109      2  1989     -1.368724 1989-02-01
110      3  1989     -0.994765 1989-03-01
111      4  1989     -0.983002 1989-04-01
112      5  1989     -1.846345 1989-05-01
113      6  1989     -2.084692 1989-06-01
114      7  1989     -1.610597 1989-07-01
115      8  1989     -0.035092 1989-08-01
116      9  1989     -1.516816 1989-09-01
There are enough months in the past
Target period: 01-1989 to 09-1989
Target period includes only one year

Year: 1989 - End-Month of observation: 10
Forecast Year: 1990 -  Forecast Month: 1
Dropping year: 1989  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
109      2  1989     -1.368724 1989-02-01
110      3  1989     -0.994765 1989-03-01
111      4  1989     -0.983002 1989-04-01
112      5  1989     -1.846345 1989-05-01
113      6  1989     -2.084692 1989-06-01
114      7  1989     -1.610597 1989-07-01
115      8  1989     -0.035092 1989-08-01
116      9  1989     -1.516816 1989-09-01
117     10  1989     -1.961382 1989-10-01
There are enough months in the past
Target period: 02-1989 to 10-1989
Target period includes only one year

Year: 1989 - End-Month of observation: 11
Forecast Year: 1990 -  Forecast Month: 2
Dropping year: 1989  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
110      3  1989     -0.994765 1989-03-01
111      4  1989     -0.983002 1989-04-01
112      5  1989     -1.846345 1989-05-01
113      6  1989     -2.084692 1989-06-01
114      7  1989     -1.610597 1989-07-01
115      8  1989     -0.035092 1989-08-01
116      9  1989     -1.516816 1989-09-01
117     10  1989     -1.961382 1989-10-01
118     11  1989     -1.405065 1989-11-01
There are enough months in the past
Target period: 03-1989 to 11-1989
Target period includes only one year

Year: 1989 - End-Month of observation: 12
Forecast Year: 1990 -  Forecast Month: 3
Dropping year: 1989  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
111      4  1989     -0.983002 1989-04-01
112      5  1989     -1.846345 1989-05-01
113      6  1989     -2.084692 1989-06-01
114      7  1989     -1.610597 1989-07-01
115      8  1989     -0.035092 1989-08-01
116      9  1989     -1.516816 1989-09-01
117     10  1989     -1.961382 1989-10-01
118     11  1989     -1.405065 1989-11-01
119     12  1989     -0.226197 1989-12-01
There are enough months in the past
Target period: 04-1989 to 12-1989
Target period includes only one year

Year: 1990 - End-Month of observation: 1
Forecast Year: 1990 -  Forecast Month: 4
Dropping year: 1990  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
112      5  1989     -1.846345 1989-05-01
113      6  1989     -2.084692 1989-06-01
114      7  1989     -1.610597 1989-07-01
115      8  1989     -0.035092 1989-08-01
116      9  1989     -1.516816 1989-09-01
117     10  1989     -1.961382 1989-10-01
118     11  1989     -1.405065 1989-11-01
119     12  1989     -0.226197 1989-12-01
120      1  1990     -1.217702 1990-01-01
There are enough months in the past
Target period: 05-1989 to 01-1990
Target period includes two years

Year: 1990 - End-Month of observation: 2
Forecast Year: 1990 -  Forecast Month: 5
Dropping year: 1990  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
113      6  1989     -2.084692 1989-06-01
114      7  1989     -1.610597 1989-07-01
115      8  1989     -0.035092 1989-08-01
116      9  1989     -1.516816 1989-09-01
117     10  1989     -1.961382 1989-10-01
118     11  1989     -1.405065 1989-11-01
119     12  1989     -0.226197 1989-12-01
120      1  1990     -1.217702 1990-01-01
121      2  1990      0.695973 1990-02-01
There are enough months in the past
Target period: 06-1989 to 02-1990
Target period includes two years

Year: 1990 - End-Month of observation: 3
Forecast Year: 1990 -  Forecast Month: 6
Dropping year: 1990  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
114      7  1989     -1.610597 1989-07-01
115      8  1989     -0.035092 1989-08-01
116      9  1989     -1.516816 1989-09-01
117     10  1989     -1.961382 1989-10-01
118     11  1989     -1.405065 1989-11-01
119     12  1989     -0.226197 1989-12-01
120      1  1990     -1.217702 1990-01-01
121      2  1990      0.695973 1990-02-01
122      3  1990      0.368636 1990-03-01
There are enough months in the past
Target period: 07-1989 to 03-1990
Target period includes two years

Year: 1990 - End-Month of observation: 4
Forecast Year: 1990 -  Forecast Month: 7
Dropping year: 1990  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
115      8  1989     -0.035092 1989-08-01
116      9  1989     -1.516816 1989-09-01
117     10  1989     -1.961382 1989-10-01
118     11  1989     -1.405065 1989-11-01
119     12  1989     -0.226197 1989-12-01
120      1  1990     -1.217702 1990-01-01
121      2  1990      0.695973 1990-02-01
122      3  1990      0.368636 1990-03-01
123      4  1990      1.740413 1990-04-01
There are enough months in the past
Target period: 08-1989 to 04-1990
Target period includes two years

Year: 1990 - End-Month of observation: 5
Forecast Year: 1990 -  Forecast Month: 8
Dropping year: 1990  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
116      9  1989     -1.516816 1989-09-01
117     10  1989     -1.961382 1989-10-01
118     11  1989     -1.405065 1989-11-01
119     12  1989     -0.226197 1989-12-01
120      1  1990     -1.217702 1990-01-01
121      2  1990      0.695973 1990-02-01
122      3  1990      0.368636 1990-03-01
123      4  1990      1.740413 1990-04-01
124      5  1990      0.055118 1990-05-01
There are enough months in the past
Target period: 09-1989 to 05-1990
Target period includes two years

Year: 1990 - End-Month of observation: 6
Forecast Year: 1990 -  Forecast Month: 9
Dropping year: 1990  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
117     10  1989     -1.961382 1989-10-01
118     11  1989     -1.405065 1989-11-01
119     12  1989     -0.226197 1989-12-01
120      1  1990     -1.217702 1990-01-01
121      2  1990      0.695973 1990-02-01
122      3  1990      0.368636 1990-03-01
123      4  1990      1.740413 1990-04-01
124      5  1990      0.055118 1990-05-01
125      6  1990      0.182126 1990-06-01
There are enough months in the past
Target period: 10-1989 to 06-1990
Target period includes two years

Year: 1990 - End-Month of observation: 7
Forecast Year: 1990 -  Forecast Month: 10
Dropping year: 1990  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
118     11  1989     -1.405065 1989-11-01
119     12  1989     -0.226197 1989-12-01
120      1  1990     -1.217702 1990-01-01
121      2  1990      0.695973 1990-02-01
122      3  1990      0.368636 1990-03-01
123      4  1990      1.740413 1990-04-01
124      5  1990      0.055118 1990-05-01
125      6  1990      0.182126 1990-06-01
126      7  1990     -1.619038 1990-07-01
There are enough months in the past
Target period: 11-1989 to 07-1990
Target period includes two years

Year: 1990 - End-Month of observation: 8
Forecast Year: 1990 -  Forecast Month: 11
Dropping year: 1990  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
119     12  1989     -0.226197 1989-12-01
120      1  1990     -1.217702 1990-01-01
121      2  1990      0.695973 1990-02-01
122      3  1990      0.368636 1990-03-01
123      4  1990      1.740413 1990-04-01
124      5  1990      0.055118 1990-05-01
125      6  1990      0.182126 1990-06-01
126      7  1990     -1.619038 1990-07-01
127      8  1990     -1.997518 1990-08-01
There are enough months in the past
Target period: 12-1989 to 08-1990
Target period includes two years

Year: 1990 - End-Month of observation: 9
Forecast Year: 1990 -  Forecast Month: 12
Dropping year: 1990  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
120      1  1990     -1.217702 1990-01-01
121      2  1990      0.695973 1990-02-01
122      3  1990      0.368636 1990-03-01
123      4  1990      1.740413 1990-04-01
124      5  1990      0.055118 1990-05-01
125      6  1990      0.182126 1990-06-01
126      7  1990     -1.619038 1990-07-01
127      8  1990     -1.997518 1990-08-01
128      9  1990     -1.517861 1990-09-01
There are enough months in the past
Target period: 01-1990 to 09-1990
Target period includes only one year

Year: 1990 - End-Month of observation: 10
Forecast Year: 1991 -  Forecast Month: 1
Dropping year: 1990  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
121      2  1990      0.695973 1990-02-01
122      3  1990      0.368636 1990-03-01
123      4  1990      1.740413 1990-04-01
124      5  1990      0.055118 1990-05-01
125      6  1990      0.182126 1990-06-01
126      7  1990     -1.619038 1990-07-01
127      8  1990     -1.997518 1990-08-01
128      9  1990     -1.517861 1990-09-01
129     10  1990      0.017501 1990-10-01
There are enough months in the past
Target period: 02-1990 to 10-1990
Target period includes only one year

Year: 1990 - End-Month of observation: 11
Forecast Year: 1991 -  Forecast Month: 2
Dropping year: 1990  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
122      3  1990      0.368636 1990-03-01
123      4  1990      1.740413 1990-04-01
124      5  1990      0.055118 1990-05-01
125      6  1990      0.182126 1990-06-01
126      7  1990     -1.619038 1990-07-01
127      8  1990     -1.997518 1990-08-01
128      9  1990     -1.517861 1990-09-01
129     10  1990      0.017501 1990-10-01
130     11  1990      0.987506 1990-11-01
There are enough months in the past
Target period: 03-1990 to 11-1990
Target period includes only one year

Year: 1990 - End-Month of observation: 12
Forecast Year: 1991 -  Forecast Month: 3
Dropping year: 1990  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
123      4  1990      1.740413 1990-04-01
124      5  1990      0.055118 1990-05-01
125      6  1990      0.182126 1990-06-01
126      7  1990     -1.619038 1990-07-01
127      8  1990     -1.997518 1990-08-01
128      9  1990     -1.517861 1990-09-01
129     10  1990      0.017501 1990-10-01
130     11  1990      0.987506 1990-11-01
131     12  1990      0.935263 1990-12-01
There are enough months in the past
Target period: 04-1990 to 12-1990
Target period includes only one year

Year: 1991 - End-Month of observation: 1
Forecast Year: 1991 -  Forecast Month: 4
Dropping year: 1991  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
124      5  1990      0.055118 1990-05-01
125      6  1990      0.182126 1990-06-01
126      7  1990     -1.619038 1990-07-01
127      8  1990     -1.997518 1990-08-01
128      9  1990     -1.517861 1990-09-01
129     10  1990      0.017501 1990-10-01
130     11  1990      0.987506 1990-11-01
131     12  1990      0.935263 1990-12-01
132      1  1991     -0.332189 1991-01-01
There are enough months in the past
Target period: 05-1990 to 01-1991
Target period includes two years

Year: 1991 - End-Month of observation: 2
Forecast Year: 1991 -  Forecast Month: 5
Dropping year: 1991  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
125      6  1990      0.182126 1990-06-01
126      7  1990     -1.619038 1990-07-01
127      8  1990     -1.997518 1990-08-01
128      9  1990     -1.517861 1990-09-01
129     10  1990      0.017501 1990-10-01
130     11  1990      0.987506 1990-11-01
131     12  1990      0.935263 1990-12-01
132      1  1991     -0.332189 1991-01-01
133      2  1991     -0.834223 1991-02-01
There are enough months in the past
Target period: 06-1990 to 02-1991
Target period includes two years

Year: 1991 - End-Month of observation: 3
Forecast Year: 1991 -  Forecast Month: 6
Dropping year: 1991  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
126      7  1990     -1.619038 1990-07-01
127      8  1990     -1.997518 1990-08-01
128      9  1990     -1.517861 1990-09-01
129     10  1990      0.017501 1990-10-01
130     11  1990      0.987506 1990-11-01
131     12  1990      0.935263 1990-12-01
132      1  1991     -0.332189 1991-01-01
133      2  1991     -0.834223 1991-02-01
134      3  1991     -0.618578 1991-03-01
There are enough months in the past
Target period: 07-1990 to 03-1991
Target period includes two years

Year: 1991 - End-Month of observation: 4
Forecast Year: 1991 -  Forecast Month: 7
Dropping year: 1991  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
127      8  1990     -1.997518 1990-08-01
128      9  1990     -1.517861 1990-09-01
129     10  1990      0.017501 1990-10-01
130     11  1990      0.987506 1990-11-01
131     12  1990      0.935263 1990-12-01
132      1  1991     -0.332189 1991-01-01
133      2  1991     -0.834223 1991-02-01
134      3  1991     -0.618578 1991-03-01
135      4  1991     -0.820711 1991-04-01
There are enough months in the past
Target period: 08-1990 to 04-1991
Target period includes two years

Year: 1991 - End-Month of observation: 5
Forecast Year: 1991 -  Forecast Month: 8
Dropping year: 1991  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
128      9  1990     -1.517861 1990-09-01
129     10  1990      0.017501 1990-10-01
130     11  1990      0.987506 1990-11-01
131     12  1990      0.935263 1990-12-01
132      1  1991     -0.332189 1991-01-01
133      2  1991     -0.834223 1991-02-01
134      3  1991     -0.618578 1991-03-01
135      4  1991     -0.820711 1991-04-01
136      5  1991     -0.026225 1991-05-01
There are enough months in the past
Target period: 09-1990 to 05-1991
Target period includes two years

Year: 1991 - End-Month of observation: 6
Forecast Year: 1991 -  Forecast Month: 9
Dropping year: 1991  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
129     10  1990      0.017501 1990-10-01
130     11  1990      0.987506 1990-11-01
131     12  1990      0.935263 1990-12-01
132      1  1991     -0.332189 1991-01-01
133      2  1991     -0.834223 1991-02-01
134      3  1991     -0.618578 1991-03-01
135      4  1991     -0.820711 1991-04-01
136      5  1991     -0.026225 1991-05-01
137      6  1991      0.362392 1991-06-01
There are enough months in the past
Target period: 10-1990 to 06-1991
Target period includes two years

Year: 1991 - End-Month of observation: 7
Forecast Year: 1991 -  Forecast Month: 10
Dropping year: 1991  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
130     11  1990      0.987506 1990-11-01
131     12  1990      0.935263 1990-12-01
132      1  1991     -0.332189 1991-01-01
133      2  1991     -0.834223 1991-02-01
134      3  1991     -0.618578 1991-03-01
135      4  1991     -0.820711 1991-04-01
136      5  1991     -0.026225 1991-05-01
137      6  1991      0.362392 1991-06-01
138      7  1991      0.623227 1991-07-01
There are enough months in the past
Target period: 11-1990 to 07-1991
Target period includes two years

Year: 1991 - End-Month of observation: 8
Forecast Year: 1991 -  Forecast Month: 11
Dropping year: 1991  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
131     12  1990      0.935263 1990-12-01
132      1  1991     -0.332189 1991-01-01
133      2  1991     -0.834223 1991-02-01
134      3  1991     -0.618578 1991-03-01
135      4  1991     -0.820711 1991-04-01
136      5  1991     -0.026225 1991-05-01
137      6  1991      0.362392 1991-06-01
138      7  1991      0.623227 1991-07-01
139      8  1991      0.865586 1991-08-01
There are enough months in the past
Target period: 12-1990 to 08-1991
Target period includes two years

Year: 1991 - End-Month of observation: 9
Forecast Year: 1991 -  Forecast Month: 12
Dropping year: 1991  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
132      1  1991     -0.332189 1991-01-01
133      2  1991     -0.834223 1991-02-01
134      3  1991     -0.618578 1991-03-01
135      4  1991     -0.820711 1991-04-01
136      5  1991     -0.026225 1991-05-01
137      6  1991      0.362392 1991-06-01
138      7  1991      0.623227 1991-07-01
139      8  1991      0.865586 1991-08-01
140      9  1991      0.693688 1991-09-01
There are enough months in the past
Target period: 01-1991 to 09-1991
Target period includes only one year

Year: 1991 - End-Month of observation: 10
Forecast Year: 1992 -  Forecast Month: 1
Dropping year: 1991  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
133      2  1991     -0.834223 1991-02-01
134      3  1991     -0.618578 1991-03-01
135      4  1991     -0.820711 1991-04-01
136      5  1991     -0.026225 1991-05-01
137      6  1991      0.362392 1991-06-01
138      7  1991      0.623227 1991-07-01
139      8  1991      0.865586 1991-08-01
140      9  1991      0.693688 1991-09-01
141     10  1991      1.130842 1991-10-01
There are enough months in the past
Target period: 02-1991 to 10-1991
Target period includes only one year

Year: 1991 - End-Month of observation: 11
Forecast Year: 1992 -  Forecast Month: 2
Dropping year: 1991  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
134      3  1991     -0.618578 1991-03-01
135      4  1991     -0.820711 1991-04-01
136      5  1991     -0.026225 1991-05-01
137      6  1991      0.362392 1991-06-01
138      7  1991      0.623227 1991-07-01
139      8  1991      0.865586 1991-08-01
140      9  1991      0.693688 1991-09-01
141     10  1991      1.130842 1991-10-01
142     11  1991      0.146338 1991-11-01
There are enough months in the past
Target period: 03-1991 to 11-1991
Target period includes only one year

Year: 1991 - End-Month of observation: 12
Forecast Year: 1992 -  Forecast Month: 3
Dropping year: 1991  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
135      4  1991     -0.820711 1991-04-01
136      5  1991     -0.026225 1991-05-01
137      6  1991      0.362392 1991-06-01
138      7  1991      0.623227 1991-07-01
139      8  1991      0.865586 1991-08-01
140      9  1991      0.693688 1991-09-01
141     10  1991      1.130842 1991-10-01
142     11  1991      0.146338 1991-11-01
143     12  1991      0.559022 1991-12-01
There are enough months in the past
Target period: 04-1991 to 12-1991
Target period includes only one year

Year: 1992 - End-Month of observation: 1
Forecast Year: 1992 -  Forecast Month: 4
Dropping year: 1992  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
136      5  1991     -0.026225 1991-05-01
137      6  1991      0.362392 1991-06-01
138      7  1991      0.623227 1991-07-01
139      8  1991      0.865586 1991-08-01
140      9  1991      0.693688 1991-09-01
141     10  1991      1.130842 1991-10-01
142     11  1991      0.146338 1991-11-01
143     12  1991      0.559022 1991-12-01
144      1  1992     -0.151861 1992-01-01
There are enough months in the past
Target period: 05-1991 to 01-1992
Target period includes two years

Year: 1992 - End-Month of observation: 2
Forecast Year: 1992 -  Forecast Month: 5
Dropping year: 1992  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
137      6  1991      0.362392 1991-06-01
138      7  1991      0.623227 1991-07-01
139      8  1991      0.865586 1991-08-01
140      9  1991      0.693688 1991-09-01
141     10  1991      1.130842 1991-10-01
142     11  1991      0.146338 1991-11-01
143     12  1991      0.559022 1991-12-01
144      1  1992     -0.151861 1992-01-01
145      2  1992     -0.451418 1992-02-01
There are enough months in the past
Target period: 06-1991 to 02-1992
Target period includes two years

Year: 1992 - End-Month of observation: 3
Forecast Year: 1992 -  Forecast Month: 6
Dropping year: 1992  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
138      7  1991      0.623227 1991-07-01
139      8  1991      0.865586 1991-08-01
140      9  1991      0.693688 1991-09-01
141     10  1991      1.130842 1991-10-01
142     11  1991      0.146338 1991-11-01
143     12  1991      0.559022 1991-12-01
144      1  1992     -0.151861 1992-01-01
145      2  1992     -0.451418 1992-02-01
146      3  1992     -0.621814 1992-03-01
There are enough months in the past
Target period: 07-1991 to 03-1992
Target period includes two years

Year: 1992 - End-Month of observation: 4
Forecast Year: 1992 -  Forecast Month: 7
Dropping year: 1992  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
139      8  1991      0.865586 1991-08-01
140      9  1991      0.693688 1991-09-01
141     10  1991      1.130842 1991-10-01
142     11  1991      0.146338 1991-11-01
143     12  1991      0.559022 1991-12-01
144      1  1992     -0.151861 1992-01-01
145      2  1992     -0.451418 1992-02-01
146      3  1992     -0.621814 1992-03-01
147      4  1992     -0.109710 1992-04-01
There are enough months in the past
Target period: 08-1991 to 04-1992
Target period includes two years

Year: 1992 - End-Month of observation: 5
Forecast Year: 1992 -  Forecast Month: 8
Dropping year: 1992  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
140      9  1991      0.693688 1991-09-01
141     10  1991      1.130842 1991-10-01
142     11  1991      0.146338 1991-11-01
143     12  1991      0.559022 1991-12-01
144      1  1992     -0.151861 1992-01-01
145      2  1992     -0.451418 1992-02-01
146      3  1992     -0.621814 1992-03-01
147      4  1992     -0.109710 1992-04-01
148      5  1992      0.897623 1992-05-01
There are enough months in the past
Target period: 09-1991 to 05-1992
Target period includes two years

Year: 1992 - End-Month of observation: 6
Forecast Year: 1992 -  Forecast Month: 9
Dropping year: 1992  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
141     10  1991      1.130842 1991-10-01
142     11  1991      0.146338 1991-11-01
143     12  1991      0.559022 1991-12-01
144      1  1992     -0.151861 1992-01-01
145      2  1992     -0.451418 1992-02-01
146      3  1992     -0.621814 1992-03-01
147      4  1992     -0.109710 1992-04-01
148      5  1992      0.897623 1992-05-01
149      6  1992      0.517625 1992-06-01
There are enough months in the past
Target period: 10-1991 to 06-1992
Target period includes two years

Year: 1992 - End-Month of observation: 7
Forecast Year: 1992 -  Forecast Month: 10
Dropping year: 1992  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
142     11  1991      0.146338 1991-11-01
143     12  1991      0.559022 1991-12-01
144      1  1992     -0.151861 1992-01-01
145      2  1992     -0.451418 1992-02-01
146      3  1992     -0.621814 1992-03-01
147      4  1992     -0.109710 1992-04-01
148      5  1992      0.897623 1992-05-01
149      6  1992      0.517625 1992-06-01
150      7  1992      0.285137 1992-07-01
There are enough months in the past
Target period: 11-1991 to 07-1992
Target period includes two years

Year: 1992 - End-Month of observation: 8
Forecast Year: 1992 -  Forecast Month: 11
Dropping year: 1992  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
143     12  1991      0.559022 1991-12-01
144      1  1992     -0.151861 1992-01-01
145      2  1992     -0.451418 1992-02-01
146      3  1992     -0.621814 1992-03-01
147      4  1992     -0.109710 1992-04-01
148      5  1992      0.897623 1992-05-01
149      6  1992      0.517625 1992-06-01
150      7  1992      0.285137 1992-07-01
151      8  1992     -0.708144 1992-08-01
There are enough months in the past
Target period: 12-1991 to 08-1992
Target period includes two years

Year: 1992 - End-Month of observation: 9
Forecast Year: 1992 -  Forecast Month: 12
Dropping year: 1992  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
144      1  1992     -0.151861 1992-01-01
145      2  1992     -0.451418 1992-02-01
146      3  1992     -0.621814 1992-03-01
147      4  1992     -0.109710 1992-04-01
148      5  1992      0.897623 1992-05-01
149      6  1992      0.517625 1992-06-01
150      7  1992      0.285137 1992-07-01
151      8  1992     -0.708144 1992-08-01
152      9  1992      0.532099 1992-09-01
There are enough months in the past
Target period: 01-1992 to 09-1992
Target period includes only one year

Year: 1992 - End-Month of observation: 10
Forecast Year: 1993 -  Forecast Month: 1
Dropping year: 1992  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
145      2  1992     -0.451418 1992-02-01
146      3  1992     -0.621814 1992-03-01
147      4  1992     -0.109710 1992-04-01
148      5  1992      0.897623 1992-05-01
149      6  1992      0.517625 1992-06-01
150      7  1992      0.285137 1992-07-01
151      8  1992     -0.708144 1992-08-01
152      9  1992      0.532099 1992-09-01
153     10  1992      0.270075 1992-10-01
There are enough months in the past
Target period: 02-1992 to 10-1992
Target period includes only one year

Year: 1992 - End-Month of observation: 11
Forecast Year: 1993 -  Forecast Month: 2
Dropping year: 1992  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
146      3  1992     -0.621814 1992-03-01
147      4  1992     -0.109710 1992-04-01
148      5  1992      0.897623 1992-05-01
149      6  1992      0.517625 1992-06-01
150      7  1992      0.285137 1992-07-01
151      8  1992     -0.708144 1992-08-01
152      9  1992      0.532099 1992-09-01
153     10  1992      0.270075 1992-10-01
154     11  1992      0.017482 1992-11-01
There are enough months in the past
Target period: 03-1992 to 11-1992
Target period includes only one year

Year: 1992 - End-Month of observation: 12
Forecast Year: 1993 -  Forecast Month: 3
Dropping year: 1992  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
147      4  1992     -0.109710 1992-04-01
148      5  1992      0.897623 1992-05-01
149      6  1992      0.517625 1992-06-01
150      7  1992      0.285137 1992-07-01
151      8  1992     -0.708144 1992-08-01
152      9  1992      0.532099 1992-09-01
153     10  1992      0.270075 1992-10-01
154     11  1992      0.017482 1992-11-01
155     12  1992     -0.661842 1992-12-01
There are enough months in the past
Target period: 04-1992 to 12-1992
Target period includes only one year

Year: 1993 - End-Month of observation: 1
Forecast Year: 1993 -  Forecast Month: 4
Dropping year: 1993  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
148      5  1992      0.897623 1992-05-01
149      6  1992      0.517625 1992-06-01
150      7  1992      0.285137 1992-07-01
151      8  1992     -0.708144 1992-08-01
152      9  1992      0.532099 1992-09-01
153     10  1992      0.270075 1992-10-01
154     11  1992      0.017482 1992-11-01
155     12  1992     -0.661842 1992-12-01
156      1  1993     -0.391850 1993-01-01
There are enough months in the past
Target period: 05-1992 to 01-1993
Target period includes two years

Year: 1993 - End-Month of observation: 2
Forecast Year: 1993 -  Forecast Month: 5
Dropping year: 1993  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
149      6  1992      0.517625 1992-06-01
150      7  1992      0.285137 1992-07-01
151      8  1992     -0.708144 1992-08-01
152      9  1992      0.532099 1992-09-01
153     10  1992      0.270075 1992-10-01
154     11  1992      0.017482 1992-11-01
155     12  1992     -0.661842 1992-12-01
156      1  1993     -0.391850 1993-01-01
157      2  1993      1.702978 1993-02-01
There are enough months in the past
Target period: 06-1992 to 02-1993
Target period includes two years

Year: 1993 - End-Month of observation: 3
Forecast Year: 1993 -  Forecast Month: 6
Dropping year: 1993  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
150      7  1992      0.285137 1992-07-01
151      8  1992     -0.708144 1992-08-01
152      9  1992      0.532099 1992-09-01
153     10  1992      0.270075 1992-10-01
154     11  1992      0.017482 1992-11-01
155     12  1992     -0.661842 1992-12-01
156      1  1993     -0.391850 1993-01-01
157      2  1993      1.702978 1993-02-01
158      3  1993     -0.434609 1993-03-01
There are enough months in the past
Target period: 07-1992 to 03-1993
Target period includes two years

Year: 1993 - End-Month of observation: 4
Forecast Year: 1993 -  Forecast Month: 7
Dropping year: 1993  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
151      8  1992     -0.708144 1992-08-01
152      9  1992      0.532099 1992-09-01
153     10  1992      0.270075 1992-10-01
154     11  1992      0.017482 1992-11-01
155     12  1992     -0.661842 1992-12-01
156      1  1993     -0.391850 1993-01-01
157      2  1993      1.702978 1993-02-01
158      3  1993     -0.434609 1993-03-01
159      4  1993      0.941890 1993-04-01
There are enough months in the past
Target period: 08-1992 to 04-1993
Target period includes two years

Year: 1993 - End-Month of observation: 5
Forecast Year: 1993 -  Forecast Month: 8
Dropping year: 1993  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
152      9  1992      0.532099 1992-09-01
153     10  1992      0.270075 1992-10-01
154     11  1992      0.017482 1992-11-01
155     12  1992     -0.661842 1992-12-01
156      1  1993     -0.391850 1993-01-01
157      2  1993      1.702978 1993-02-01
158      3  1993     -0.434609 1993-03-01
159      4  1993      0.941890 1993-04-01
160      5  1993      0.929453 1993-05-01
There are enough months in the past
Target period: 09-1992 to 05-1993
Target period includes two years

Year: 1993 - End-Month of observation: 6
Forecast Year: 1993 -  Forecast Month: 9
Dropping year: 1993  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
153     10  1992      0.270075 1992-10-01
154     11  1992      0.017482 1992-11-01
155     12  1992     -0.661842 1992-12-01
156      1  1993     -0.391850 1993-01-01
157      2  1993      1.702978 1993-02-01
158      3  1993     -0.434609 1993-03-01
159      4  1993      0.941890 1993-04-01
160      5  1993      0.929453 1993-05-01
161      6  1993      0.271876 1993-06-01
There are enough months in the past
Target period: 10-1992 to 06-1993
Target period includes two years

Year: 1993 - End-Month of observation: 7
Forecast Year: 1993 -  Forecast Month: 10
Dropping year: 1993  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
154     11  1992      0.017482 1992-11-01
155     12  1992     -0.661842 1992-12-01
156      1  1993     -0.391850 1993-01-01
157      2  1993      1.702978 1993-02-01
158      3  1993     -0.434609 1993-03-01
159      4  1993      0.941890 1993-04-01
160      5  1993      0.929453 1993-05-01
161      6  1993      0.271876 1993-06-01
162      7  1993     -0.455937 1993-07-01
There are enough months in the past
Target period: 11-1992 to 07-1993
Target period includes two years

Year: 1993 - End-Month of observation: 8
Forecast Year: 1993 -  Forecast Month: 11
Dropping year: 1993  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
155     12  1992     -0.661842 1992-12-01
156      1  1993     -0.391850 1993-01-01
157      2  1993      1.702978 1993-02-01
158      3  1993     -0.434609 1993-03-01
159      4  1993      0.941890 1993-04-01
160      5  1993      0.929453 1993-05-01
161      6  1993      0.271876 1993-06-01
162      7  1993     -0.455937 1993-07-01
163      8  1993      0.028734 1993-08-01
There are enough months in the past
Target period: 12-1992 to 08-1993
Target period includes two years

Year: 1993 - End-Month of observation: 9
Forecast Year: 1993 -  Forecast Month: 12
Dropping year: 1993  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
156      1  1993     -0.391850 1993-01-01
157      2  1993      1.702978 1993-02-01
158      3  1993     -0.434609 1993-03-01
159      4  1993      0.941890 1993-04-01
160      5  1993      0.929453 1993-05-01
161      6  1993      0.271876 1993-06-01
162      7  1993     -0.455937 1993-07-01
163      8  1993      0.028734 1993-08-01
164      9  1993      0.656601 1993-09-01
There are enough months in the past
Target period: 01-1993 to 09-1993
Target period includes only one year

Year: 1993 - End-Month of observation: 10
Forecast Year: 1994 -  Forecast Month: 1
Dropping year: 1993  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
157      2  1993      1.702978 1993-02-01
158      3  1993     -0.434609 1993-03-01
159      4  1993      0.941890 1993-04-01
160      5  1993      0.929453 1993-05-01
161      6  1993      0.271876 1993-06-01
162      7  1993     -0.455937 1993-07-01
163      8  1993      0.028734 1993-08-01
164      9  1993      0.656601 1993-09-01
165     10  1993      1.335728 1993-10-01
There are enough months in the past
Target period: 02-1993 to 10-1993
Target period includes only one year

Year: 1993 - End-Month of observation: 11
Forecast Year: 1994 -  Forecast Month: 2
Dropping year: 1993  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
158      3  1993     -0.434609 1993-03-01
159      4  1993      0.941890 1993-04-01
160      5  1993      0.929453 1993-05-01
161      6  1993      0.271876 1993-06-01
162      7  1993     -0.455937 1993-07-01
163      8  1993      0.028734 1993-08-01
164      9  1993      0.656601 1993-09-01
165     10  1993      1.335728 1993-10-01
166     11  1993      1.562345 1993-11-01
There are enough months in the past
Target period: 03-1993 to 11-1993
Target period includes only one year

Year: 1993 - End-Month of observation: 12
Forecast Year: 1994 -  Forecast Month: 3
Dropping year: 1993  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
159      4  1993      0.941890 1993-04-01
160      5  1993      0.929453 1993-05-01
161      6  1993      0.271876 1993-06-01
162      7  1993     -0.455937 1993-07-01
163      8  1993      0.028734 1993-08-01
164      9  1993      0.656601 1993-09-01
165     10  1993      1.335728 1993-10-01
166     11  1993      1.562345 1993-11-01
167     12  1993      2.352541 1993-12-01
There are enough months in the past
Target period: 04-1993 to 12-1993
Target period includes only one year

Year: 1994 - End-Month of observation: 1
Forecast Year: 1994 -  Forecast Month: 4
Dropping year: 1994  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
160      5  1993      0.929453 1993-05-01
161      6  1993      0.271876 1993-06-01
162      7  1993     -0.455937 1993-07-01
163      8  1993      0.028734 1993-08-01
164      9  1993      0.656601 1993-09-01
165     10  1993      1.335728 1993-10-01
166     11  1993      1.562345 1993-11-01
167     12  1993      2.352541 1993-12-01
168      1  1994      1.297849 1994-01-01
There are enough months in the past
Target period: 05-1993 to 01-1994
Target period includes two years

Year: 1994 - End-Month of observation: 2
Forecast Year: 1994 -  Forecast Month: 5
Dropping year: 1994  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
161      6  1993      0.271876 1993-06-01
162      7  1993     -0.455937 1993-07-01
163      8  1993      0.028734 1993-08-01
164      9  1993      0.656601 1993-09-01
165     10  1993      1.335728 1993-10-01
166     11  1993      1.562345 1993-11-01
167     12  1993      2.352541 1993-12-01
168      1  1994      1.297849 1994-01-01
169      2  1994           NaN 1994-02-01
There are enough months in the past
Target period: 06-1993 to 02-1994
Target period includes two years

Year: 1994 - End-Month of observation: 3
Forecast Year: 1994 -  Forecast Month: 6
Dropping year: 1994  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
162      7  1993     -0.455937 1993-07-01
163      8  1993      0.028734 1993-08-01
164      9  1993      0.656601 1993-09-01
165     10  1993      1.335728 1993-10-01
166     11  1993      1.562345 1993-11-01
167     12  1993      2.352541 1993-12-01
168      1  1994      1.297849 1994-01-01
169      2  1994           NaN 1994-02-01
170      3  1994      0.184724 1994-03-01
There are enough months in the past
Target period: 07-1993 to 03-1994
Target period includes two years

Year: 1994 - End-Month of observation: 4
Forecast Year: 1994 -  Forecast Month: 7
Dropping year: 1994  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
163      8  1993      0.028734 1993-08-01
164      9  1993      0.656601 1993-09-01
165     10  1993      1.335728 1993-10-01
166     11  1993      1.562345 1993-11-01
167     12  1993      2.352541 1993-12-01
168      1  1994      1.297849 1994-01-01
169      2  1994           NaN 1994-02-01
170      3  1994      0.184724 1994-03-01
171      4  1994     -0.084077 1994-04-01
There are enough months in the past
Target period: 08-1993 to 04-1994
Target period includes two years

Year: 1994 - End-Month of observation: 5
Forecast Year: 1994 -  Forecast Month: 8
Dropping year: 1994  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
164      9  1993      0.656601 1993-09-01
165     10  1993      1.335728 1993-10-01
166     11  1993      1.562345 1993-11-01
167     12  1993      2.352541 1993-12-01
168      1  1994      1.297849 1994-01-01
169      2  1994           NaN 1994-02-01
170      3  1994      0.184724 1994-03-01
171      4  1994     -0.084077 1994-04-01
172      5  1994      1.142730 1994-05-01
There are enough months in the past
Target period: 09-1993 to 05-1994
Target period includes two years

Year: 1994 - End-Month of observation: 6
Forecast Year: 1994 -  Forecast Month: 9
Dropping year: 1994  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
165     10  1993      1.335728 1993-10-01
166     11  1993      1.562345 1993-11-01
167     12  1993      2.352541 1993-12-01
168      1  1994      1.297849 1994-01-01
169      2  1994           NaN 1994-02-01
170      3  1994      0.184724 1994-03-01
171      4  1994     -0.084077 1994-04-01
172      5  1994      1.142730 1994-05-01
173      6  1994     -0.628118 1994-06-01
There are enough months in the past
Target period: 10-1993 to 06-1994
Target period includes two years

Year: 1994 - End-Month of observation: 7
Forecast Year: 1994 -  Forecast Month: 10
Dropping year: 1994  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
166     11  1993      1.562345 1993-11-01
167     12  1993      2.352541 1993-12-01
168      1  1994      1.297849 1994-01-01
169      2  1994           NaN 1994-02-01
170      3  1994      0.184724 1994-03-01
171      4  1994     -0.084077 1994-04-01
172      5  1994      1.142730 1994-05-01
173      6  1994     -0.628118 1994-06-01
174      7  1994     -0.508600 1994-07-01
There are enough months in the past
Target period: 11-1993 to 07-1994
Target period includes two years

Year: 1994 - End-Month of observation: 8
Forecast Year: 1994 -  Forecast Month: 11
Dropping year: 1994  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
167     12  1993      2.352541 1993-12-01
168      1  1994      1.297849 1994-01-01
169      2  1994           NaN 1994-02-01
170      3  1994      0.184724 1994-03-01
171      4  1994     -0.084077 1994-04-01
172      5  1994      1.142730 1994-05-01
173      6  1994     -0.628118 1994-06-01
174      7  1994     -0.508600 1994-07-01
175      8  1994      0.605638 1994-08-01
There are enough months in the past
Target period: 12-1993 to 08-1994
Target period includes two years

Year: 1994 - End-Month of observation: 9
Forecast Year: 1994 -  Forecast Month: 12
Dropping year: 1994  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
168      1  1994      1.297849 1994-01-01
169      2  1994           NaN 1994-02-01
170      3  1994      0.184724 1994-03-01
171      4  1994     -0.084077 1994-04-01
172      5  1994      1.142730 1994-05-01
173      6  1994     -0.628118 1994-06-01
174      7  1994     -0.508600 1994-07-01
175      8  1994      0.605638 1994-08-01
176      9  1994      0.844961 1994-09-01
There are enough months in the past
Target period: 01-1994 to 09-1994
Target period includes only one year

Year: 1994 - End-Month of observation: 10
Forecast Year: 1995 -  Forecast Month: 1
Dropping year: 1994  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
169      2  1994           NaN 1994-02-01
170      3  1994      0.184724 1994-03-01
171      4  1994     -0.084077 1994-04-01
172      5  1994      1.142730 1994-05-01
173      6  1994     -0.628118 1994-06-01
174      7  1994     -0.508600 1994-07-01
175      8  1994      0.605638 1994-08-01
176      9  1994      0.844961 1994-09-01
177     10  1994      0.181266 1994-10-01
There are enough months in the past
Target period: 02-1994 to 10-1994
Target period includes only one year

Year: 1994 - End-Month of observation: 11
Forecast Year: 1995 -  Forecast Month: 2
Dropping year: 1994  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
170      3  1994      0.184724 1994-03-01
171      4  1994     -0.084077 1994-04-01
172      5  1994      1.142730 1994-05-01
173      6  1994     -0.628118 1994-06-01
174      7  1994     -0.508600 1994-07-01
175      8  1994      0.605638 1994-08-01
176      9  1994      0.844961 1994-09-01
177     10  1994      0.181266 1994-10-01
178     11  1994      0.578897 1994-11-01
There are enough months in the past
Target period: 03-1994 to 11-1994
Target period includes only one year

Year: 1994 - End-Month of observation: 12
Forecast Year: 1995 -  Forecast Month: 3
Dropping year: 1994  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
171      4  1994     -0.084077 1994-04-01
172      5  1994      1.142730 1994-05-01
173      6  1994     -0.628118 1994-06-01
174      7  1994     -0.508600 1994-07-01
175      8  1994      0.605638 1994-08-01
176      9  1994      0.844961 1994-09-01
177     10  1994      0.181266 1994-10-01
178     11  1994      0.578897 1994-11-01
179     12  1994      0.929445 1994-12-01
There are enough months in the past
Target period: 04-1994 to 12-1994
Target period includes only one year

Year: 1995 - End-Month of observation: 1
Forecast Year: 1995 -  Forecast Month: 4
Dropping year: 1995  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
172      5  1994      1.142730 1994-05-01
173      6  1994     -0.628118 1994-06-01
174      7  1994     -0.508600 1994-07-01
175      8  1994      0.605638 1994-08-01
176      9  1994      0.844961 1994-09-01
177     10  1994      0.181266 1994-10-01
178     11  1994      0.578897 1994-11-01
179     12  1994      0.929445 1994-12-01
180      1  1995     -0.771544 1995-01-01
There are enough months in the past
Target period: 05-1994 to 01-1995
Target period includes two years

Year: 1995 - End-Month of observation: 2
Forecast Year: 1995 -  Forecast Month: 5
Dropping year: 1995  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
173      6  1994     -0.628118 1994-06-01
174      7  1994     -0.508600 1994-07-01
175      8  1994      0.605638 1994-08-01
176      9  1994      0.844961 1994-09-01
177     10  1994      0.181266 1994-10-01
178     11  1994      0.578897 1994-11-01
179     12  1994      0.929445 1994-12-01
180      1  1995     -0.771544 1995-01-01
181      2  1995      0.080346 1995-02-01
There are enough months in the past
Target period: 06-1994 to 02-1995
Target period includes two years

Year: 1995 - End-Month of observation: 3
Forecast Year: 1995 -  Forecast Month: 6
Dropping year: 1995  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
174      7  1994     -0.508600 1994-07-01
175      8  1994      0.605638 1994-08-01
176      9  1994      0.844961 1994-09-01
177     10  1994      0.181266 1994-10-01
178     11  1994      0.578897 1994-11-01
179     12  1994      0.929445 1994-12-01
180      1  1995     -0.771544 1995-01-01
181      2  1995      0.080346 1995-02-01
182      3  1995     -0.028342 1995-03-01
There are enough months in the past
Target period: 07-1994 to 03-1995
Target period includes two years

Year: 1995 - End-Month of observation: 4
Forecast Year: 1995 -  Forecast Month: 7
Dropping year: 1995  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
175      8  1994      0.605638 1994-08-01
176      9  1994      0.844961 1994-09-01
177     10  1994      0.181266 1994-10-01
178     11  1994      0.578897 1994-11-01
179     12  1994      0.929445 1994-12-01
180      1  1995     -0.771544 1995-01-01
181      2  1995      0.080346 1995-02-01
182      3  1995     -0.028342 1995-03-01
183      4  1995      1.142900 1995-04-01
There are enough months in the past
Target period: 08-1994 to 04-1995
Target period includes two years

Year: 1995 - End-Month of observation: 5
Forecast Year: 1995 -  Forecast Month: 8
Dropping year: 1995  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
176      9  1994      0.844961 1994-09-01
177     10  1994      0.181266 1994-10-01
178     11  1994      0.578897 1994-11-01
179     12  1994      0.929445 1994-12-01
180      1  1995     -0.771544 1995-01-01
181      2  1995      0.080346 1995-02-01
182      3  1995     -0.028342 1995-03-01
183      4  1995      1.142900 1995-04-01
184      5  1995      0.193611 1995-05-01
There are enough months in the past
Target period: 09-1994 to 05-1995
Target period includes two years

Year: 1995 - End-Month of observation: 6
Forecast Year: 1995 -  Forecast Month: 9
Dropping year: 1995  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
177     10  1994      0.181266 1994-10-01
178     11  1994      0.578897 1994-11-01
179     12  1994      0.929445 1994-12-01
180      1  1995     -0.771544 1995-01-01
181      2  1995      0.080346 1995-02-01
182      3  1995     -0.028342 1995-03-01
183      4  1995      1.142900 1995-04-01
184      5  1995      0.193611 1995-05-01
185      6  1995      0.309844 1995-06-01
There are enough months in the past
Target period: 10-1994 to 06-1995
Target period includes two years

Year: 1995 - End-Month of observation: 7
Forecast Year: 1995 -  Forecast Month: 10
Dropping year: 1995  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
178     11  1994      0.578897 1994-11-01
179     12  1994      0.929445 1994-12-01
180      1  1995     -0.771544 1995-01-01
181      2  1995      0.080346 1995-02-01
182      3  1995     -0.028342 1995-03-01
183      4  1995      1.142900 1995-04-01
184      5  1995      0.193611 1995-05-01
185      6  1995      0.309844 1995-06-01
186      7  1995      0.499323 1995-07-01
There are enough months in the past
Target period: 11-1994 to 07-1995
Target period includes two years

Year: 1995 - End-Month of observation: 8
Forecast Year: 1995 -  Forecast Month: 11
Dropping year: 1995  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
179     12  1994      0.929445 1994-12-01
180      1  1995     -0.771544 1995-01-01
181      2  1995      0.080346 1995-02-01
182      3  1995     -0.028342 1995-03-01
183      4  1995      1.142900 1995-04-01
184      5  1995      0.193611 1995-05-01
185      6  1995      0.309844 1995-06-01
186      7  1995      0.499323 1995-07-01
187      8  1995     -1.407229 1995-08-01
There are enough months in the past
Target period: 12-1994 to 08-1995
Target period includes two years

Year: 1995 - End-Month of observation: 9
Forecast Year: 1995 -  Forecast Month: 12
Dropping year: 1995  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
180      1  1995     -0.771544 1995-01-01
181      2  1995      0.080346 1995-02-01
182      3  1995     -0.028342 1995-03-01
183      4  1995      1.142900 1995-04-01
184      5  1995      0.193611 1995-05-01
185      6  1995      0.309844 1995-06-01
186      7  1995      0.499323 1995-07-01
187      8  1995     -1.407229 1995-08-01
188      9  1995     -1.777712 1995-09-01
There are enough months in the past
Target period: 01-1995 to 09-1995
Target period includes only one year

Year: 1995 - End-Month of observation: 10
Forecast Year: 1996 -  Forecast Month: 1
Dropping year: 1995  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
181      2  1995      0.080346 1995-02-01
182      3  1995     -0.028342 1995-03-01
183      4  1995      1.142900 1995-04-01
184      5  1995      0.193611 1995-05-01
185      6  1995      0.309844 1995-06-01
186      7  1995      0.499323 1995-07-01
187      8  1995     -1.407229 1995-08-01
188      9  1995     -1.777712 1995-09-01
189     10  1995     -0.460783 1995-10-01
There are enough months in the past
Target period: 02-1995 to 10-1995
Target period includes only one year

Year: 1995 - End-Month of observation: 11
Forecast Year: 1996 -  Forecast Month: 2
Dropping year: 1995  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
182      3  1995     -0.028342 1995-03-01
183      4  1995      1.142900 1995-04-01
184      5  1995      0.193611 1995-05-01
185      6  1995      0.309844 1995-06-01
186      7  1995      0.499323 1995-07-01
187      8  1995     -1.407229 1995-08-01
188      9  1995     -1.777712 1995-09-01
189     10  1995     -0.460783 1995-10-01
190     11  1995      0.560488 1995-11-01
There are enough months in the past
Target period: 03-1995 to 11-1995
Target period includes only one year

Year: 1995 - End-Month of observation: 12
Forecast Year: 1996 -  Forecast Month: 3
Dropping year: 1995  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
183      4  1995      1.142900 1995-04-01
184      5  1995      0.193611 1995-05-01
185      6  1995      0.309844 1995-06-01
186      7  1995      0.499323 1995-07-01
187      8  1995     -1.407229 1995-08-01
188      9  1995     -1.777712 1995-09-01
189     10  1995     -0.460783 1995-10-01
190     11  1995      0.560488 1995-11-01
191     12  1995     -1.028693 1995-12-01
There are enough months in the past
Target period: 04-1995 to 12-1995
Target period includes only one year

Year: 1996 - End-Month of observation: 1
Forecast Year: 1996 -  Forecast Month: 4
Dropping year: 1996  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
184      5  1995      0.193611 1995-05-01
185      6  1995      0.309844 1995-06-01
186      7  1995      0.499323 1995-07-01
187      8  1995     -1.407229 1995-08-01
188      9  1995     -1.777712 1995-09-01
189     10  1995     -0.460783 1995-10-01
190     11  1995      0.560488 1995-11-01
191     12  1995     -1.028693 1995-12-01
192      1  1996     -0.773628 1996-01-01
There are enough months in the past
Target period: 05-1995 to 01-1996
Target period includes two years

Year: 1996 - End-Month of observation: 2
Forecast Year: 1996 -  Forecast Month: 5
Dropping year: 1996  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
185      6  1995      0.309844 1995-06-01
186      7  1995      0.499323 1995-07-01
187      8  1995     -1.407229 1995-08-01
188      9  1995     -1.777712 1995-09-01
189     10  1995     -0.460783 1995-10-01
190     11  1995      0.560488 1995-11-01
191     12  1995     -1.028693 1995-12-01
192      1  1996     -0.773628 1996-01-01
193      2  1996     -1.114598 1996-02-01
There are enough months in the past
Target period: 06-1995 to 02-1996
Target period includes two years

Year: 1996 - End-Month of observation: 3
Forecast Year: 1996 -  Forecast Month: 6
Dropping year: 1996  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
186      7  1995      0.499323 1995-07-01
187      8  1995     -1.407229 1995-08-01
188      9  1995     -1.777712 1995-09-01
189     10  1995     -0.460783 1995-10-01
190     11  1995      0.560488 1995-11-01
191     12  1995     -1.028693 1995-12-01
192      1  1996     -0.773628 1996-01-01
193      2  1996     -1.114598 1996-02-01
194      3  1996     -1.316506 1996-03-01
There are enough months in the past
Target period: 07-1995 to 03-1996
Target period includes two years

Year: 1996 - End-Month of observation: 4
Forecast Year: 1996 -  Forecast Month: 7
Dropping year: 1996  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
187      8  1995     -1.407229 1995-08-01
188      9  1995     -1.777712 1995-09-01
189     10  1995     -0.460783 1995-10-01
190     11  1995      0.560488 1995-11-01
191     12  1995     -1.028693 1995-12-01
192      1  1996     -0.773628 1996-01-01
193      2  1996     -1.114598 1996-02-01
194      3  1996     -1.316506 1996-03-01
195      4  1996      0.569727 1996-04-01
There are enough months in the past
Target period: 08-1995 to 04-1996
Target period includes two years

Year: 1996 - End-Month of observation: 5
Forecast Year: 1996 -  Forecast Month: 8
Dropping year: 1996  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
188      9  1995     -1.777712 1995-09-01
189     10  1995     -0.460783 1995-10-01
190     11  1995      0.560488 1995-11-01
191     12  1995     -1.028693 1995-12-01
192      1  1996     -0.773628 1996-01-01
193      2  1996     -1.114598 1996-02-01
194      3  1996     -1.316506 1996-03-01
195      4  1996      0.569727 1996-04-01
196      5  1996     -0.909332 1996-05-01
There are enough months in the past
Target period: 09-1995 to 05-1996
Target period includes two years

Year: 1996 - End-Month of observation: 6
Forecast Year: 1996 -  Forecast Month: 9
Dropping year: 1996  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
189     10  1995     -0.460783 1995-10-01
190     11  1995      0.560488 1995-11-01
191     12  1995     -1.028693 1995-12-01
192      1  1996     -0.773628 1996-01-01
193      2  1996     -1.114598 1996-02-01
194      3  1996     -1.316506 1996-03-01
195      4  1996      0.569727 1996-04-01
196      5  1996     -0.909332 1996-05-01
197      6  1996     -1.732159 1996-06-01
There are enough months in the past
Target period: 10-1995 to 06-1996
Target period includes two years

Year: 1996 - End-Month of observation: 7
Forecast Year: 1996 -  Forecast Month: 10
Dropping year: 1996  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
190     11  1995      0.560488 1995-11-01
191     12  1995     -1.028693 1995-12-01
192      1  1996     -0.773628 1996-01-01
193      2  1996     -1.114598 1996-02-01
194      3  1996     -1.316506 1996-03-01
195      4  1996      0.569727 1996-04-01
196      5  1996     -0.909332 1996-05-01
197      6  1996     -1.732159 1996-06-01
198      7  1996     -2.199121 1996-07-01
There are enough months in the past
Target period: 11-1995 to 07-1996
Target period includes two years

Year: 1996 - End-Month of observation: 8
Forecast Year: 1996 -  Forecast Month: 11
Dropping year: 1996  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
191     12  1995     -1.028693 1995-12-01
192      1  1996     -0.773628 1996-01-01
193      2  1996     -1.114598 1996-02-01
194      3  1996     -1.316506 1996-03-01
195      4  1996      0.569727 1996-04-01
196      5  1996     -0.909332 1996-05-01
197      6  1996     -1.732159 1996-06-01
198      7  1996     -2.199121 1996-07-01
199      8  1996     -2.770442 1996-08-01
There are enough months in the past
Target period: 12-1995 to 08-1996
Target period includes two years

Year: 1996 - End-Month of observation: 9
Forecast Year: 1996 -  Forecast Month: 12
Dropping year: 1996  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
192      1  1996     -0.773628 1996-01-01
193      2  1996     -1.114598 1996-02-01
194      3  1996     -1.316506 1996-03-01
195      4  1996      0.569727 1996-04-01
196      5  1996     -0.909332 1996-05-01
197      6  1996     -1.732159 1996-06-01
198      7  1996     -2.199121 1996-07-01
199      8  1996     -2.770442 1996-08-01
200      9  1996      0.490324 1996-09-01
There are enough months in the past
Target period: 01-1996 to 09-1996
Target period includes only one year

Year: 1996 - End-Month of observation: 10
Forecast Year: 1997 -  Forecast Month: 1
Dropping year: 1996  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
193      2  1996     -1.114598 1996-02-01
194      3  1996     -1.316506 1996-03-01
195      4  1996      0.569727 1996-04-01
196      5  1996     -0.909332 1996-05-01
197      6  1996     -1.732159 1996-06-01
198      7  1996     -2.199121 1996-07-01
199      8  1996     -2.770442 1996-08-01
200      9  1996      0.490324 1996-09-01
201     10  1996     -0.214463 1996-10-01
There are enough months in the past
Target period: 02-1996 to 10-1996
Target period includes only one year

Year: 1996 - End-Month of observation: 11
Forecast Year: 1997 -  Forecast Month: 2
Dropping year: 1996  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
194      3  1996     -1.316506 1996-03-01
195      4  1996      0.569727 1996-04-01
196      5  1996     -0.909332 1996-05-01
197      6  1996     -1.732159 1996-06-01
198      7  1996     -2.199121 1996-07-01
199      8  1996     -2.770442 1996-08-01
200      9  1996      0.490324 1996-09-01
201     10  1996     -0.214463 1996-10-01
202     11  1996      0.031035 1996-11-01
There are enough months in the past
Target period: 03-1996 to 11-1996
Target period includes only one year

Year: 1996 - End-Month of observation: 12
Forecast Year: 1997 -  Forecast Month: 3
Dropping year: 1996  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
195      4  1996      0.569727 1996-04-01
196      5  1996     -0.909332 1996-05-01
197      6  1996     -1.732159 1996-06-01
198      7  1996     -2.199121 1996-07-01
199      8  1996     -2.770442 1996-08-01
200      9  1996      0.490324 1996-09-01
201     10  1996     -0.214463 1996-10-01
202     11  1996      0.031035 1996-11-01
203     12  1996     -0.764436 1996-12-01
There are enough months in the past
Target period: 04-1996 to 12-1996
Target period includes only one year

Year: 1997 - End-Month of observation: 1
Forecast Year: 1997 -  Forecast Month: 4
Dropping year: 1997  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
196      5  1996     -0.909332 1996-05-01
197      6  1996     -1.732159 1996-06-01
198      7  1996     -2.199121 1996-07-01
199      8  1996     -2.770442 1996-08-01
200      9  1996      0.490324 1996-09-01
201     10  1996     -0.214463 1996-10-01
202     11  1996      0.031035 1996-11-01
203     12  1996     -0.764436 1996-12-01
204      1  1997     -0.609809 1997-01-01
There are enough months in the past
Target period: 05-1996 to 01-1997
Target period includes two years

Year: 1997 - End-Month of observation: 2
Forecast Year: 1997 -  Forecast Month: 5
Dropping year: 1997  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
197      6  1996     -1.732159 1996-06-01
198      7  1996     -2.199121 1996-07-01
199      8  1996     -2.770442 1996-08-01
200      9  1996      0.490324 1996-09-01
201     10  1996     -0.214463 1996-10-01
202     11  1996      0.031035 1996-11-01
203     12  1996     -0.764436 1996-12-01
204      1  1997     -0.609809 1997-01-01
205      2  1997     -0.735161 1997-02-01
There are enough months in the past
Target period: 06-1996 to 02-1997
Target period includes two years

Year: 1997 - End-Month of observation: 3
Forecast Year: 1997 -  Forecast Month: 6
Dropping year: 1997  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
198      7  1996     -2.199121 1996-07-01
199      8  1996     -2.770442 1996-08-01
200      9  1996      0.490324 1996-09-01
201     10  1996     -0.214463 1996-10-01
202     11  1996      0.031035 1996-11-01
203     12  1996     -0.764436 1996-12-01
204      1  1997     -0.609809 1997-01-01
205      2  1997     -0.735161 1997-02-01
206      3  1997     -0.671217 1997-03-01
There are enough months in the past
Target period: 07-1996 to 03-1997
Target period includes two years

Year: 1997 - End-Month of observation: 4
Forecast Year: 1997 -  Forecast Month: 7
Dropping year: 1997  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
199      8  1996     -2.770442 1996-08-01
200      9  1996      0.490324 1996-09-01
201     10  1996     -0.214463 1996-10-01
202     11  1996      0.031035 1996-11-01
203     12  1996     -0.764436 1996-12-01
204      1  1997     -0.609809 1997-01-01
205      2  1997     -0.735161 1997-02-01
206      3  1997     -0.671217 1997-03-01
207      4  1997     -1.152541 1997-04-01
There are enough months in the past
Target period: 08-1996 to 04-1997
Target period includes two years

Year: 1997 - End-Month of observation: 5
Forecast Year: 1997 -  Forecast Month: 8
Dropping year: 1997  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
200      9  1996      0.490324 1996-09-01
201     10  1996     -0.214463 1996-10-01
202     11  1996      0.031035 1996-11-01
203     12  1996     -0.764436 1996-12-01
204      1  1997     -0.609809 1997-01-01
205      2  1997     -0.735161 1997-02-01
206      3  1997     -0.671217 1997-03-01
207      4  1997     -1.152541 1997-04-01
208      5  1997     -1.229191 1997-05-01
There are enough months in the past
Target period: 09-1996 to 05-1997
Target period includes two years

Year: 1997 - End-Month of observation: 6
Forecast Year: 1997 -  Forecast Month: 9
Dropping year: 1997  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
201     10  1996     -0.214463 1996-10-01
202     11  1996      0.031035 1996-11-01
203     12  1996     -0.764436 1996-12-01
204      1  1997     -0.609809 1997-01-01
205      2  1997     -0.735161 1997-02-01
206      3  1997     -0.671217 1997-03-01
207      4  1997     -1.152541 1997-04-01
208      5  1997     -1.229191 1997-05-01
209      6  1997     -0.216433 1997-06-01
There are enough months in the past
Target period: 10-1996 to 06-1997
Target period includes two years

Year: 1997 - End-Month of observation: 7
Forecast Year: 1997 -  Forecast Month: 10
Dropping year: 1997  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
202     11  1996      0.031035 1996-11-01
203     12  1996     -0.764436 1996-12-01
204      1  1997     -0.609809 1997-01-01
205      2  1997     -0.735161 1997-02-01
206      3  1997     -0.671217 1997-03-01
207      4  1997     -1.152541 1997-04-01
208      5  1997     -1.229191 1997-05-01
209      6  1997     -0.216433 1997-06-01
210      7  1997     -1.788752 1997-07-01
There are enough months in the past
Target period: 11-1996 to 07-1997
Target period includes two years

Year: 1997 - End-Month of observation: 8
Forecast Year: 1997 -  Forecast Month: 11
Dropping year: 1997  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
203     12  1996     -0.764436 1996-12-01
204      1  1997     -0.609809 1997-01-01
205      2  1997     -0.735161 1997-02-01
206      3  1997     -0.671217 1997-03-01
207      4  1997     -1.152541 1997-04-01
208      5  1997     -1.229191 1997-05-01
209      6  1997     -0.216433 1997-06-01
210      7  1997     -1.788752 1997-07-01
211      8  1997     -0.163174 1997-08-01
There are enough months in the past
Target period: 12-1996 to 08-1997
Target period includes two years

Year: 1997 - End-Month of observation: 9
Forecast Year: 1997 -  Forecast Month: 12
Dropping year: 1997  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
204      1  1997     -0.609809 1997-01-01
205      2  1997     -0.735161 1997-02-01
206      3  1997     -0.671217 1997-03-01
207      4  1997     -1.152541 1997-04-01
208      5  1997     -1.229191 1997-05-01
209      6  1997     -0.216433 1997-06-01
210      7  1997     -1.788752 1997-07-01
211      8  1997     -0.163174 1997-08-01
212      9  1997     -1.238533 1997-09-01
There are enough months in the past
Target period: 01-1997 to 09-1997
Target period includes only one year

Year: 1997 - End-Month of observation: 10
Forecast Year: 1998 -  Forecast Month: 1
Dropping year: 1997  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
205      2  1997     -0.735161 1997-02-01
206      3  1997     -0.671217 1997-03-01
207      4  1997     -1.152541 1997-04-01
208      5  1997     -1.229191 1997-05-01
209      6  1997     -0.216433 1997-06-01
210      7  1997     -1.788752 1997-07-01
211      8  1997     -0.163174 1997-08-01
212      9  1997     -1.238533 1997-09-01
213     10  1997     -0.144519 1997-10-01
There are enough months in the past
Target period: 02-1997 to 10-1997
Target period includes only one year

Year: 1997 - End-Month of observation: 11
Forecast Year: 1998 -  Forecast Month: 2
Dropping year: 1997  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
206      3  1997     -0.671217 1997-03-01
207      4  1997     -1.152541 1997-04-01
208      5  1997     -1.229191 1997-05-01
209      6  1997     -0.216433 1997-06-01
210      7  1997     -1.788752 1997-07-01
211      8  1997     -0.163174 1997-08-01
212      9  1997     -1.238533 1997-09-01
213     10  1997     -0.144519 1997-10-01
214     11  1997      0.583983 1997-11-01
There are enough months in the past
Target period: 03-1997 to 11-1997
Target period includes only one year

Year: 1997 - End-Month of observation: 12
Forecast Year: 1998 -  Forecast Month: 3
Dropping year: 1997  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
207      4  1997     -1.152541 1997-04-01
208      5  1997     -1.229191 1997-05-01
209      6  1997     -0.216433 1997-06-01
210      7  1997     -1.788752 1997-07-01
211      8  1997     -0.163174 1997-08-01
212      9  1997     -1.238533 1997-09-01
213     10  1997     -0.144519 1997-10-01
214     11  1997      0.583983 1997-11-01
215     12  1997      2.308784 1997-12-01
There are enough months in the past
Target period: 04-1997 to 12-1997
Target period includes only one year

Year: 1998 - End-Month of observation: 1
Forecast Year: 1998 -  Forecast Month: 4
Dropping year: 1998  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
208      5  1997     -1.229191 1997-05-01
209      6  1997     -0.216433 1997-06-01
210      7  1997     -1.788752 1997-07-01
211      8  1997     -0.163174 1997-08-01
212      9  1997     -1.238533 1997-09-01
213     10  1997     -0.144519 1997-10-01
214     11  1997      0.583983 1997-11-01
215     12  1997      2.308784 1997-12-01
216      1  1998      1.599805 1998-01-01
There are enough months in the past
Target period: 05-1997 to 01-1998
Target period includes two years

Year: 1998 - End-Month of observation: 2
Forecast Year: 1998 -  Forecast Month: 5
Dropping year: 1998  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
209      6  1997     -0.216433 1997-06-01
210      7  1997     -1.788752 1997-07-01
211      8  1997     -0.163174 1997-08-01
212      9  1997     -1.238533 1997-09-01
213     10  1997     -0.144519 1997-10-01
214     11  1997      0.583983 1997-11-01
215     12  1997      2.308784 1997-12-01
216      1  1998      1.599805 1998-01-01
217      2  1998     -0.535340 1998-02-01
There are enough months in the past
Target period: 06-1997 to 02-1998
Target period includes two years

Year: 1998 - End-Month of observation: 3
Forecast Year: 1998 -  Forecast Month: 6
Dropping year: 1998  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
210      7  1997     -1.788752 1997-07-01
211      8  1997     -0.163174 1997-08-01
212      9  1997     -1.238533 1997-09-01
213     10  1997     -0.144519 1997-10-01
214     11  1997      0.583983 1997-11-01
215     12  1997      2.308784 1997-12-01
216      1  1998      1.599805 1998-01-01
217      2  1998     -0.535340 1998-02-01
218      3  1998     -0.821700 1998-03-01
There are enough months in the past
Target period: 07-1997 to 03-1998
Target period includes two years

Year: 1998 - End-Month of observation: 4
Forecast Year: 1998 -  Forecast Month: 7
Dropping year: 1998  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
211      8  1997     -0.163174 1997-08-01
212      9  1997     -1.238533 1997-09-01
213     10  1997     -0.144519 1997-10-01
214     11  1997      0.583983 1997-11-01
215     12  1997      2.308784 1997-12-01
216      1  1998      1.599805 1998-01-01
217      2  1998     -0.535340 1998-02-01
218      3  1998     -0.821700 1998-03-01
219      4  1998     -0.223646 1998-04-01
There are enough months in the past
Target period: 08-1997 to 04-1998
Target period includes two years

Year: 1998 - End-Month of observation: 5
Forecast Year: 1998 -  Forecast Month: 8
Dropping year: 1998  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
212      9  1997     -1.238533 1997-09-01
213     10  1997     -0.144519 1997-10-01
214     11  1997      0.583983 1997-11-01
215     12  1997      2.308784 1997-12-01
216      1  1998      1.599805 1998-01-01
217      2  1998     -0.535340 1998-02-01
218      3  1998     -0.821700 1998-03-01
219      4  1998     -0.223646 1998-04-01
220      5  1998     -0.437847 1998-05-01
There are enough months in the past
Target period: 09-1997 to 05-1998
Target period includes two years

Year: 1998 - End-Month of observation: 6
Forecast Year: 1998 -  Forecast Month: 9
Dropping year: 1998  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
213     10  1997     -0.144519 1997-10-01
214     11  1997      0.583983 1997-11-01
215     12  1997      2.308784 1997-12-01
216      1  1998      1.599805 1998-01-01
217      2  1998     -0.535340 1998-02-01
218      3  1998     -0.821700 1998-03-01
219      4  1998     -0.223646 1998-04-01
220      5  1998     -0.437847 1998-05-01
221      6  1998     -0.312289 1998-06-01
There are enough months in the past
Target period: 10-1997 to 06-1998
Target period includes two years

Year: 1998 - End-Month of observation: 7
Forecast Year: 1998 -  Forecast Month: 10
Dropping year: 1998  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
214     11  1997      0.583983 1997-11-01
215     12  1997      2.308784 1997-12-01
216      1  1998      1.599805 1998-01-01
217      2  1998     -0.535340 1998-02-01
218      3  1998     -0.821700 1998-03-01
219      4  1998     -0.223646 1998-04-01
220      5  1998     -0.437847 1998-05-01
221      6  1998     -0.312289 1998-06-01
222      7  1998      0.929367 1998-07-01
There are enough months in the past
Target period: 11-1997 to 07-1998
Target period includes two years

Year: 1998 - End-Month of observation: 8
Forecast Year: 1998 -  Forecast Month: 11
Dropping year: 1998  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
215     12  1997      2.308784 1997-12-01
216      1  1998      1.599805 1998-01-01
217      2  1998     -0.535340 1998-02-01
218      3  1998     -0.821700 1998-03-01
219      4  1998     -0.223646 1998-04-01
220      5  1998     -0.437847 1998-05-01
221      6  1998     -0.312289 1998-06-01
222      7  1998      0.929367 1998-07-01
223      8  1998     -0.543317 1998-08-01
There are enough months in the past
Target period: 12-1997 to 08-1998
Target period includes two years

Year: 1998 - End-Month of observation: 9
Forecast Year: 1998 -  Forecast Month: 12
Dropping year: 1998  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
216      1  1998      1.599805 1998-01-01
217      2  1998     -0.535340 1998-02-01
218      3  1998     -0.821700 1998-03-01
219      4  1998     -0.223646 1998-04-01
220      5  1998     -0.437847 1998-05-01
221      6  1998     -0.312289 1998-06-01
222      7  1998      0.929367 1998-07-01
223      8  1998     -0.543317 1998-08-01
224      9  1998     -0.830146 1998-09-01
There are enough months in the past
Target period: 01-1998 to 09-1998
Target period includes only one year

Year: 1998 - End-Month of observation: 10
Forecast Year: 1999 -  Forecast Month: 1
Dropping year: 1998  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
217      2  1998     -0.535340 1998-02-01
218      3  1998     -0.821700 1998-03-01
219      4  1998     -0.223646 1998-04-01
220      5  1998     -0.437847 1998-05-01
221      6  1998     -0.312289 1998-06-01
222      7  1998      0.929367 1998-07-01
223      8  1998     -0.543317 1998-08-01
224      9  1998     -0.830146 1998-09-01
225     10  1998     -1.455970 1998-10-01
There are enough months in the past
Target period: 02-1998 to 10-1998
Target period includes only one year

Year: 1998 - End-Month of observation: 11
Forecast Year: 1999 -  Forecast Month: 2
Dropping year: 1998  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
218      3  1998     -0.821700 1998-03-01
219      4  1998     -0.223646 1998-04-01
220      5  1998     -0.437847 1998-05-01
221      6  1998     -0.312289 1998-06-01
222      7  1998      0.929367 1998-07-01
223      8  1998     -0.543317 1998-08-01
224      9  1998     -0.830146 1998-09-01
225     10  1998     -1.455970 1998-10-01
226     11  1998     -0.806662 1998-11-01
There are enough months in the past
Target period: 03-1998 to 11-1998
Target period includes only one year

Year: 1998 - End-Month of observation: 12
Forecast Year: 1999 -  Forecast Month: 3
Dropping year: 1998  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
219      4  1998     -0.223646 1998-04-01
220      5  1998     -0.437847 1998-05-01
221      6  1998     -0.312289 1998-06-01
222      7  1998      0.929367 1998-07-01
223      8  1998     -0.543317 1998-08-01
224      9  1998     -0.830146 1998-09-01
225     10  1998     -1.455970 1998-10-01
226     11  1998     -0.806662 1998-11-01
227     12  1998      0.551987 1998-12-01
There are enough months in the past
Target period: 04-1998 to 12-1998
Target period includes only one year

Year: 1999 - End-Month of observation: 1
Forecast Year: 1999 -  Forecast Month: 4
Dropping year: 1999  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
220      5  1998     -0.437847 1998-05-01
221      6  1998     -0.312289 1998-06-01
222      7  1998      0.929367 1998-07-01
223      8  1998     -0.543317 1998-08-01
224      9  1998     -0.830146 1998-09-01
225     10  1998     -1.455970 1998-10-01
226     11  1998     -0.806662 1998-11-01
227     12  1998      0.551987 1998-12-01
228      1  1999      2.014703 1999-01-01
There are enough months in the past
Target period: 05-1998 to 01-1999
Target period includes two years

Year: 1999 - End-Month of observation: 2
Forecast Year: 1999 -  Forecast Month: 5
Dropping year: 1999  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
221      6  1998     -0.312289 1998-06-01
222      7  1998      0.929367 1998-07-01
223      8  1998     -0.543317 1998-08-01
224      9  1998     -0.830146 1998-09-01
225     10  1998     -1.455970 1998-10-01
226     11  1998     -0.806662 1998-11-01
227     12  1998      0.551987 1998-12-01
228      1  1999      2.014703 1999-01-01
229      2  1999      2.378751 1999-02-01
There are enough months in the past
Target period: 06-1998 to 02-1999
Target period includes two years

Year: 1999 - End-Month of observation: 3
Forecast Year: 1999 -  Forecast Month: 6
Dropping year: 1999  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
222      7  1998      0.929367 1998-07-01
223      8  1998     -0.543317 1998-08-01
224      9  1998     -0.830146 1998-09-01
225     10  1998     -1.455970 1998-10-01
226     11  1998     -0.806662 1998-11-01
227     12  1998      0.551987 1998-12-01
228      1  1999      2.014703 1999-01-01
229      2  1999      2.378751 1999-02-01
230      3  1999      1.549766 1999-03-01
There are enough months in the past
Target period: 07-1998 to 03-1999
Target period includes two years

Year: 1999 - End-Month of observation: 4
Forecast Year: 1999 -  Forecast Month: 7
Dropping year: 1999  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
223      8  1998     -0.543317 1998-08-01
224      9  1998     -0.830146 1998-09-01
225     10  1998     -1.455970 1998-10-01
226     11  1998     -0.806662 1998-11-01
227     12  1998      0.551987 1998-12-01
228      1  1999      2.014703 1999-01-01
229      2  1999      2.378751 1999-02-01
230      3  1999      1.549766 1999-03-01
231      4  1999      0.620392 1999-04-01
There are enough months in the past
Target period: 08-1998 to 04-1999
Target period includes two years

Year: 1999 - End-Month of observation: 5
Forecast Year: 1999 -  Forecast Month: 8
Dropping year: 1999  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
224      9  1998     -0.830146 1998-09-01
225     10  1998     -1.455970 1998-10-01
226     11  1998     -0.806662 1998-11-01
227     12  1998      0.551987 1998-12-01
228      1  1999      2.014703 1999-01-01
229      2  1999      2.378751 1999-02-01
230      3  1999      1.549766 1999-03-01
231      4  1999      0.620392 1999-04-01
232      5  1999     -0.628618 1999-05-01
There are enough months in the past
Target period: 09-1998 to 05-1999
Target period includes two years

Year: 1999 - End-Month of observation: 6
Forecast Year: 1999 -  Forecast Month: 9
Dropping year: 1999  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
225     10  1998     -1.455970 1998-10-01
226     11  1998     -0.806662 1998-11-01
227     12  1998      0.551987 1998-12-01
228      1  1999      2.014703 1999-01-01
229      2  1999      2.378751 1999-02-01
230      3  1999      1.549766 1999-03-01
231      4  1999      0.620392 1999-04-01
232      5  1999     -0.628618 1999-05-01
233      6  1999      0.386102 1999-06-01
There are enough months in the past
Target period: 10-1998 to 06-1999
Target period includes two years

Year: 1999 - End-Month of observation: 7
Forecast Year: 1999 -  Forecast Month: 10
Dropping year: 1999  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
226     11  1998     -0.806662 1998-11-01
227     12  1998      0.551987 1998-12-01
228      1  1999      2.014703 1999-01-01
229      2  1999      2.378751 1999-02-01
230      3  1999      1.549766 1999-03-01
231      4  1999      0.620392 1999-04-01
232      5  1999     -0.628618 1999-05-01
233      6  1999      0.386102 1999-06-01
234      7  1999      1.672127 1999-07-01
There are enough months in the past
Target period: 11-1998 to 07-1999
Target period includes two years

Year: 1999 - End-Month of observation: 8
Forecast Year: 1999 -  Forecast Month: 11
Dropping year: 1999  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
227     12  1998      0.551987 1998-12-01
228      1  1999      2.014703 1999-01-01
229      2  1999      2.378751 1999-02-01
230      3  1999      1.549766 1999-03-01
231      4  1999      0.620392 1999-04-01
232      5  1999     -0.628618 1999-05-01
233      6  1999      0.386102 1999-06-01
234      7  1999      1.672127 1999-07-01
235      8  1999     -0.011291 1999-08-01
There are enough months in the past
Target period: 12-1998 to 08-1999
Target period includes two years

Year: 1999 - End-Month of observation: 9
Forecast Year: 1999 -  Forecast Month: 12
Dropping year: 1999  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
228      1  1999      2.014703 1999-01-01
229      2  1999      2.378751 1999-02-01
230      3  1999      1.549766 1999-03-01
231      4  1999      0.620392 1999-04-01
232      5  1999     -0.628618 1999-05-01
233      6  1999      0.386102 1999-06-01
234      7  1999      1.672127 1999-07-01
235      8  1999     -0.011291 1999-08-01
236      9  1999      0.421248 1999-09-01
There are enough months in the past
Target period: 01-1999 to 09-1999
Target period includes only one year

Year: 1999 - End-Month of observation: 10
Forecast Year: 2000 -  Forecast Month: 1
Dropping year: 1999  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
229      2  1999      2.378751 1999-02-01
230      3  1999      1.549766 1999-03-01
231      4  1999      0.620392 1999-04-01
232      5  1999     -0.628618 1999-05-01
233      6  1999      0.386102 1999-06-01
234      7  1999      1.672127 1999-07-01
235      8  1999     -0.011291 1999-08-01
236      9  1999      0.421248 1999-09-01
237     10  1999     -1.266806 1999-10-01
There are enough months in the past
Target period: 02-1999 to 10-1999
Target period includes only one year

Year: 1999 - End-Month of observation: 11
Forecast Year: 2000 -  Forecast Month: 2
Dropping year: 1999  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
230      3  1999      1.549766 1999-03-01
231      4  1999      0.620392 1999-04-01
232      5  1999     -0.628618 1999-05-01
233      6  1999      0.386102 1999-06-01
234      7  1999      1.672127 1999-07-01
235      8  1999     -0.011291 1999-08-01
236      9  1999      0.421248 1999-09-01
237     10  1999     -1.266806 1999-10-01
238     11  1999     -1.604439 1999-11-01
There are enough months in the past
Target period: 03-1999 to 11-1999
Target period includes only one year

Year: 1999 - End-Month of observation: 12
Forecast Year: 2000 -  Forecast Month: 3
Dropping year: 1999  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
231      4  1999      0.620392 1999-04-01
232      5  1999     -0.628618 1999-05-01
233      6  1999      0.386102 1999-06-01
234      7  1999      1.672127 1999-07-01
235      8  1999     -0.011291 1999-08-01
236      9  1999      0.421248 1999-09-01
237     10  1999     -1.266806 1999-10-01
238     11  1999     -1.604439 1999-11-01
239     12  1999     -0.999923 1999-12-01
There are enough months in the past
Target period: 04-1999 to 12-1999
Target period includes only one year

Year: 2000 - End-Month of observation: 1
Forecast Year: 2000 -  Forecast Month: 4
Dropping year: 2000  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
232      5  1999     -0.628618 1999-05-01
233      6  1999      0.386102 1999-06-01
234      7  1999      1.672127 1999-07-01
235      8  1999     -0.011291 1999-08-01
236      9  1999      0.421248 1999-09-01
237     10  1999     -1.266806 1999-10-01
238     11  1999     -1.604439 1999-11-01
239     12  1999     -0.999923 1999-12-01
240      1  2000     -0.752051 2000-01-01
There are enough months in the past
Target period: 05-1999 to 01-2000
Target period includes two years

Year: 2000 - End-Month of observation: 2
Forecast Year: 2000 -  Forecast Month: 5
Dropping year: 2000  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
233      6  1999      0.386102 1999-06-01
234      7  1999      1.672127 1999-07-01
235      8  1999     -0.011291 1999-08-01
236      9  1999      0.421248 1999-09-01
237     10  1999     -1.266806 1999-10-01
238     11  1999     -1.604439 1999-11-01
239     12  1999     -0.999923 1999-12-01
240      1  2000     -0.752051 2000-01-01
241      2  2000     -1.082684 2000-02-01
There are enough months in the past
Target period: 06-1999 to 02-2000
Target period includes two years

Year: 2000 - End-Month of observation: 3
Forecast Year: 2000 -  Forecast Month: 6
Dropping year: 2000  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
234      7  1999      1.672127 1999-07-01
235      8  1999     -0.011291 1999-08-01
236      9  1999      0.421248 1999-09-01
237     10  1999     -1.266806 1999-10-01
238     11  1999     -1.604439 1999-11-01
239     12  1999     -0.999923 1999-12-01
240      1  2000     -0.752051 2000-01-01
241      2  2000     -1.082684 2000-02-01
242      3  2000     -1.341889 2000-03-01
There are enough months in the past
Target period: 07-1999 to 03-2000
Target period includes two years

Year: 2000 - End-Month of observation: 4
Forecast Year: 2000 -  Forecast Month: 7
Dropping year: 2000  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
235      8  1999     -0.011291 1999-08-01
236      9  1999      0.421248 1999-09-01
237     10  1999     -1.266806 1999-10-01
238     11  1999     -1.604439 1999-11-01
239     12  1999     -0.999923 1999-12-01
240      1  2000     -0.752051 2000-01-01
241      2  2000     -1.082684 2000-02-01
242      3  2000     -1.341889 2000-03-01
243      4  2000           NaN 2000-04-01
There are enough months in the past
Target period: 08-1999 to 04-2000
Target period includes two years

Year: 2000 - End-Month of observation: 5
Forecast Year: 2000 -  Forecast Month: 8
Dropping year: 2000  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
236      9  1999      0.421248 1999-09-01
237     10  1999     -1.266806 1999-10-01
238     11  1999     -1.604439 1999-11-01
239     12  1999     -0.999923 1999-12-01
240      1  2000     -0.752051 2000-01-01
241      2  2000     -1.082684 2000-02-01
242      3  2000     -1.341889 2000-03-01
243      4  2000           NaN 2000-04-01
244      5  2000      2.064755 2000-05-01
There are enough months in the past
Target period: 09-1999 to 05-2000
Target period includes two years

Year: 2000 - End-Month of observation: 6
Forecast Year: 2000 -  Forecast Month: 9
Dropping year: 2000  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
237     10  1999     -1.266806 1999-10-01
238     11  1999     -1.604439 1999-11-01
239     12  1999     -0.999923 1999-12-01
240      1  2000     -0.752051 2000-01-01
241      2  2000     -1.082684 2000-02-01
242      3  2000     -1.341889 2000-03-01
243      4  2000           NaN 2000-04-01
244      5  2000      2.064755 2000-05-01
245      6  2000      0.505539 2000-06-01
There are enough months in the past
Target period: 10-1999 to 06-2000
Target period includes two years

Year: 2000 - End-Month of observation: 7
Forecast Year: 2000 -  Forecast Month: 10
Dropping year: 2000  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
238     11  1999     -1.604439 1999-11-01
239     12  1999     -0.999923 1999-12-01
240      1  2000     -0.752051 2000-01-01
241      2  2000     -1.082684 2000-02-01
242      3  2000     -1.341889 2000-03-01
243      4  2000           NaN 2000-04-01
244      5  2000      2.064755 2000-05-01
245      6  2000      0.505539 2000-06-01
246      7  2000      1.241263 2000-07-01
There are enough months in the past
Target period: 11-1999 to 07-2000
Target period includes two years

Year: 2000 - End-Month of observation: 8
Forecast Year: 2000 -  Forecast Month: 11
Dropping year: 2000  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
239     12  1999     -0.999923 1999-12-01
240      1  2000     -0.752051 2000-01-01
241      2  2000     -1.082684 2000-02-01
242      3  2000     -1.341889 2000-03-01
243      4  2000           NaN 2000-04-01
244      5  2000      2.064755 2000-05-01
245      6  2000      0.505539 2000-06-01
246      7  2000      1.241263 2000-07-01
247      8  2000           NaN 2000-08-01
There are enough months in the past
Target period: 12-1999 to 08-2000
Target period includes two years

Year: 2000 - End-Month of observation: 9
Forecast Year: 2000 -  Forecast Month: 12
Dropping year: 2000  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
240      1  2000     -0.752051 2000-01-01
241      2  2000     -1.082684 2000-02-01
242      3  2000     -1.341889 2000-03-01
243      4  2000           NaN 2000-04-01
244      5  2000      2.064755 2000-05-01
245      6  2000      0.505539 2000-06-01
246      7  2000      1.241263 2000-07-01
247      8  2000           NaN 2000-08-01
248      9  2000           NaN 2000-09-01
There are enough months in the past
Target period: 01-2000 to 09-2000
Target period includes only one year

Year: 2000 - End-Month of observation: 10
Forecast Year: 2001 -  Forecast Month: 1
Dropping year: 2000  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
241      2  2000     -1.082684 2000-02-01
242      3  2000     -1.341889 2000-03-01
243      4  2000           NaN 2000-04-01
244      5  2000      2.064755 2000-05-01
245      6  2000      0.505539 2000-06-01
246      7  2000      1.241263 2000-07-01
247      8  2000           NaN 2000-08-01
248      9  2000           NaN 2000-09-01
249     10  2000           NaN 2000-10-01
There are enough months in the past
Target period: 02-2000 to 10-2000
Target period includes only one year

Year: 2000 - End-Month of observation: 11
Forecast Year: 2001 -  Forecast Month: 2
Dropping year: 2000  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
242      3  2000     -1.341889 2000-03-01
243      4  2000           NaN 2000-04-01
244      5  2000      2.064755 2000-05-01
245      6  2000      0.505539 2000-06-01
246      7  2000      1.241263 2000-07-01
247      8  2000           NaN 2000-08-01
248      9  2000           NaN 2000-09-01
249     10  2000           NaN 2000-10-01
250     11  2000           NaN 2000-11-01
There are enough months in the past
Target period: 03-2000 to 11-2000
Target period includes only one year

Year: 2000 - End-Month of observation: 12
Forecast Year: 2001 -  Forecast Month: 3
Dropping year: 2000  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
243      4  2000           NaN 2000-04-01
244      5  2000      2.064755 2000-05-01
245      6  2000      0.505539 2000-06-01
246      7  2000      1.241263 2000-07-01
247      8  2000           NaN 2000-08-01
248      9  2000           NaN 2000-09-01
249     10  2000           NaN 2000-10-01
250     11  2000           NaN 2000-11-01
251     12  2000           NaN 2000-12-01
There are enough months in the past
Target period: 04-2000 to 12-2000
Target period includes only one year

Year: 2001 - End-Month of observation: 1
Forecast Year: 2001 -  Forecast Month: 4
Dropping year: 2001  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
244      5  2000      2.064755 2000-05-01
245      6  2000      0.505539 2000-06-01
246      7  2000      1.241263 2000-07-01
247      8  2000           NaN 2000-08-01
248      9  2000           NaN 2000-09-01
249     10  2000           NaN 2000-10-01
250     11  2000           NaN 2000-11-01
251     12  2000           NaN 2000-12-01
252      1  2001           NaN 2001-01-01
There are enough months in the past
Target period: 05-2000 to 01-2001
Target period includes two years

Year: 2001 - End-Month of observation: 2
Forecast Year: 2001 -  Forecast Month: 5
Dropping year: 2001  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
245      6  2000      0.505539 2000-06-01
246      7  2000      1.241263 2000-07-01
247      8  2000           NaN 2000-08-01
248      9  2000           NaN 2000-09-01
249     10  2000           NaN 2000-10-01
250     11  2000           NaN 2000-11-01
251     12  2000           NaN 2000-12-01
252      1  2001           NaN 2001-01-01
253      2  2001           NaN 2001-02-01
There are enough months in the past
Target period: 06-2000 to 02-2001
Target period includes two years

Year: 2001 - End-Month of observation: 3
Forecast Year: 2001 -  Forecast Month: 6
Dropping year: 2001  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
246      7  2000      1.241263 2000-07-01
247      8  2000           NaN 2000-08-01
248      9  2000           NaN 2000-09-01
249     10  2000           NaN 2000-10-01
250     11  2000           NaN 2000-11-01
251     12  2000           NaN 2000-12-01
252      1  2001           NaN 2001-01-01
253      2  2001           NaN 2001-02-01
254      3  2001      1.498400 2001-03-01
There are enough months in the past
Target period: 07-2000 to 03-2001
Target period includes two years

Year: 2001 - End-Month of observation: 4
Forecast Year: 2001 -  Forecast Month: 7
Dropping year: 2001  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
247      8  2000           NaN 2000-08-01
248      9  2000           NaN 2000-09-01
249     10  2000           NaN 2000-10-01
250     11  2000           NaN 2000-11-01
251     12  2000           NaN 2000-12-01
252      1  2001           NaN 2001-01-01
253      2  2001           NaN 2001-02-01
254      3  2001      1.498400 2001-03-01
255      4  2001     -0.303012 2001-04-01
There are enough months in the past
Target period: 08-2000 to 04-2001
Target period includes two years

Year: 2001 - End-Month of observation: 5
Forecast Year: 2001 -  Forecast Month: 8
Dropping year: 2001  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
248      9  2000           NaN 2000-09-01
249     10  2000           NaN 2000-10-01
250     11  2000           NaN 2000-11-01
251     12  2000           NaN 2000-12-01
252      1  2001           NaN 2001-01-01
253      2  2001           NaN 2001-02-01
254      3  2001      1.498400 2001-03-01
255      4  2001     -0.303012 2001-04-01
256      5  2001     -0.136805 2001-05-01
There are enough months in the past
Target period: 09-2000 to 05-2001
Target period includes two years

Year: 2001 - End-Month of observation: 6
Forecast Year: 2001 -  Forecast Month: 9
Dropping year: 2001  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
249     10  2000           NaN 2000-10-01
250     11  2000           NaN 2000-11-01
251     12  2000           NaN 2000-12-01
252      1  2001           NaN 2001-01-01
253      2  2001           NaN 2001-02-01
254      3  2001      1.498400 2001-03-01
255      4  2001     -0.303012 2001-04-01
256      5  2001     -0.136805 2001-05-01
257      6  2001      1.243150 2001-06-01
There are enough months in the past
Target period: 10-2000 to 06-2001
Target period includes two years

Year: 2001 - End-Month of observation: 7
Forecast Year: 2001 -  Forecast Month: 10
Dropping year: 2001  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
250     11  2000           NaN 2000-11-01
251     12  2000           NaN 2000-12-01
252      1  2001           NaN 2001-01-01
253      2  2001           NaN 2001-02-01
254      3  2001      1.498400 2001-03-01
255      4  2001     -0.303012 2001-04-01
256      5  2001     -0.136805 2001-05-01
257      6  2001      1.243150 2001-06-01
258      7  2001     -0.321207 2001-07-01
There are enough months in the past
Target period: 11-2000 to 07-2001
Target period includes two years

Year: 2001 - End-Month of observation: 8
Forecast Year: 2001 -  Forecast Month: 11
Dropping year: 2001  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
251     12  2000           NaN 2000-12-01
252      1  2001           NaN 2001-01-01
253      2  2001           NaN 2001-02-01
254      3  2001      1.498400 2001-03-01
255      4  2001     -0.303012 2001-04-01
256      5  2001     -0.136805 2001-05-01
257      6  2001      1.243150 2001-06-01
258      7  2001     -0.321207 2001-07-01
259      8  2001      0.712015 2001-08-01
There are enough months in the past
Target period: 12-2000 to 08-2001
Target period includes two years

Year: 2001 - End-Month of observation: 9
Forecast Year: 2001 -  Forecast Month: 12
Dropping year: 2001  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
252      1  2001           NaN 2001-01-01
253      2  2001           NaN 2001-02-01
254      3  2001      1.498400 2001-03-01
255      4  2001     -0.303012 2001-04-01
256      5  2001     -0.136805 2001-05-01
257      6  2001      1.243150 2001-06-01
258      7  2001     -0.321207 2001-07-01
259      8  2001      0.712015 2001-08-01
260      9  2001      0.039467 2001-09-01
There are enough months in the past
Target period: 01-2001 to 09-2001
Target period includes only one year

Year: 2001 - End-Month of observation: 10
Forecast Year: 2002 -  Forecast Month: 1
Dropping year: 2001  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
253      2  2001           NaN 2001-02-01
254      3  2001      1.498400 2001-03-01
255      4  2001     -0.303012 2001-04-01
256      5  2001     -0.136805 2001-05-01
257      6  2001      1.243150 2001-06-01
258      7  2001     -0.321207 2001-07-01
259      8  2001      0.712015 2001-08-01
260      9  2001      0.039467 2001-09-01
261     10  2001      1.297236 2001-10-01
There are enough months in the past
Target period: 02-2001 to 10-2001
Target period includes only one year

Year: 2001 - End-Month of observation: 11
Forecast Year: 2002 -  Forecast Month: 2
Dropping year: 2001  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
254      3  2001      1.498400 2001-03-01
255      4  2001     -0.303012 2001-04-01
256      5  2001     -0.136805 2001-05-01
257      6  2001      1.243150 2001-06-01
258      7  2001     -0.321207 2001-07-01
259      8  2001      0.712015 2001-08-01
260      9  2001      0.039467 2001-09-01
261     10  2001      1.297236 2001-10-01
262     11  2001      1.250172 2001-11-01
There are enough months in the past
Target period: 03-2001 to 11-2001
Target period includes only one year

Year: 2001 - End-Month of observation: 12
Forecast Year: 2002 -  Forecast Month: 3
Dropping year: 2001  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
255      4  2001     -0.303012 2001-04-01
256      5  2001     -0.136805 2001-05-01
257      6  2001      1.243150 2001-06-01
258      7  2001     -0.321207 2001-07-01
259      8  2001      0.712015 2001-08-01
260      9  2001      0.039467 2001-09-01
261     10  2001      1.297236 2001-10-01
262     11  2001      1.250172 2001-11-01
263     12  2001      0.168188 2001-12-01
There are enough months in the past
Target period: 04-2001 to 12-2001
Target period includes only one year

Year: 2002 - End-Month of observation: 1
Forecast Year: 2002 -  Forecast Month: 4
Dropping year: 2002  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
256      5  2001     -0.136805 2001-05-01
257      6  2001      1.243150 2001-06-01
258      7  2001     -0.321207 2001-07-01
259      8  2001      0.712015 2001-08-01
260      9  2001      0.039467 2001-09-01
261     10  2001      1.297236 2001-10-01
262     11  2001      1.250172 2001-11-01
263     12  2001      0.168188 2001-12-01
264      1  2002      0.168765 2002-01-01
There are enough months in the past
Target period: 05-2001 to 01-2002
Target period includes two years

Year: 2002 - End-Month of observation: 2
Forecast Year: 2002 -  Forecast Month: 5
Dropping year: 2002  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
257      6  2001      1.243150 2001-06-01
258      7  2001     -0.321207 2001-07-01
259      8  2001      0.712015 2001-08-01
260      9  2001      0.039467 2001-09-01
261     10  2001      1.297236 2001-10-01
262     11  2001      1.250172 2001-11-01
263     12  2001      0.168188 2001-12-01
264      1  2002      0.168765 2002-01-01
265      2  2002     -0.004572 2002-02-01
There are enough months in the past
Target period: 06-2001 to 02-2002
Target period includes two years

Year: 2002 - End-Month of observation: 3
Forecast Year: 2002 -  Forecast Month: 6
Dropping year: 2002  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
258      7  2001     -0.321207 2001-07-01
259      8  2001      0.712015 2001-08-01
260      9  2001      0.039467 2001-09-01
261     10  2001      1.297236 2001-10-01
262     11  2001      1.250172 2001-11-01
263     12  2001      0.168188 2001-12-01
264      1  2002      0.168765 2002-01-01
265      2  2002     -0.004572 2002-02-01
266      3  2002      2.527140 2002-03-01
There are enough months in the past
Target period: 07-2001 to 03-2002
Target period includes two years

Year: 2002 - End-Month of observation: 4
Forecast Year: 2002 -  Forecast Month: 7
Dropping year: 2002  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
259      8  2001      0.712015 2001-08-01
260      9  2001      0.039467 2001-09-01
261     10  2001      1.297236 2001-10-01
262     11  2001      1.250172 2001-11-01
263     12  2001      0.168188 2001-12-01
264      1  2002      0.168765 2002-01-01
265      2  2002     -0.004572 2002-02-01
266      3  2002      2.527140 2002-03-01
267      4  2002      2.078428 2002-04-01
There are enough months in the past
Target period: 08-2001 to 04-2002
Target period includes two years

Year: 2002 - End-Month of observation: 5
Forecast Year: 2002 -  Forecast Month: 8
Dropping year: 2002  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
260      9  2001      0.039467 2001-09-01
261     10  2001      1.297236 2001-10-01
262     11  2001      1.250172 2001-11-01
263     12  2001      0.168188 2001-12-01
264      1  2002      0.168765 2002-01-01
265      2  2002     -0.004572 2002-02-01
266      3  2002      2.527140 2002-03-01
267      4  2002      2.078428 2002-04-01
268      5  2002      1.454932 2002-05-01
There are enough months in the past
Target period: 09-2001 to 05-2002
Target period includes two years

Year: 2002 - End-Month of observation: 6
Forecast Year: 2002 -  Forecast Month: 9
Dropping year: 2002  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
261     10  2001      1.297236 2001-10-01
262     11  2001      1.250172 2001-11-01
263     12  2001      0.168188 2001-12-01
264      1  2002      0.168765 2002-01-01
265      2  2002     -0.004572 2002-02-01
266      3  2002      2.527140 2002-03-01
267      4  2002      2.078428 2002-04-01
268      5  2002      1.454932 2002-05-01
269      6  2002      0.734981 2002-06-01
There are enough months in the past
Target period: 10-2001 to 06-2002
Target period includes two years

Year: 2002 - End-Month of observation: 7
Forecast Year: 2002 -  Forecast Month: 10
Dropping year: 2002  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
262     11  2001      1.250172 2001-11-01
263     12  2001      0.168188 2001-12-01
264      1  2002      0.168765 2002-01-01
265      2  2002     -0.004572 2002-02-01
266      3  2002      2.527140 2002-03-01
267      4  2002      2.078428 2002-04-01
268      5  2002      1.454932 2002-05-01
269      6  2002      0.734981 2002-06-01
270      7  2002      0.434812 2002-07-01
There are enough months in the past
Target period: 11-2001 to 07-2002
Target period includes two years

Year: 2002 - End-Month of observation: 8
Forecast Year: 2002 -  Forecast Month: 11
Dropping year: 2002  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
263     12  2001      0.168188 2001-12-01
264      1  2002      0.168765 2002-01-01
265      2  2002     -0.004572 2002-02-01
266      3  2002      2.527140 2002-03-01
267      4  2002      2.078428 2002-04-01
268      5  2002      1.454932 2002-05-01
269      6  2002      0.734981 2002-06-01
270      7  2002      0.434812 2002-07-01
271      8  2002      0.528228 2002-08-01
There are enough months in the past
Target period: 12-2001 to 08-2002
Target period includes two years

Year: 2002 - End-Month of observation: 9
Forecast Year: 2002 -  Forecast Month: 12
Dropping year: 2002  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
264      1  2002      0.168765 2002-01-01
265      2  2002     -0.004572 2002-02-01
266      3  2002      2.527140 2002-03-01
267      4  2002      2.078428 2002-04-01
268      5  2002      1.454932 2002-05-01
269      6  2002      0.734981 2002-06-01
270      7  2002      0.434812 2002-07-01
271      8  2002      0.528228 2002-08-01
272      9  2002      0.323237 2002-09-01
There are enough months in the past
Target period: 01-2002 to 09-2002
Target period includes only one year

Year: 2002 - End-Month of observation: 10
Forecast Year: 2003 -  Forecast Month: 1
Dropping year: 2002  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
265      2  2002     -0.004572 2002-02-01
266      3  2002      2.527140 2002-03-01
267      4  2002      2.078428 2002-04-01
268      5  2002      1.454932 2002-05-01
269      6  2002      0.734981 2002-06-01
270      7  2002      0.434812 2002-07-01
271      8  2002      0.528228 2002-08-01
272      9  2002      0.323237 2002-09-01
273     10  2002     -0.353800 2002-10-01
There are enough months in the past
Target period: 02-2002 to 10-2002
Target period includes only one year

Year: 2002 - End-Month of observation: 11
Forecast Year: 2003 -  Forecast Month: 2
Dropping year: 2002  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
266      3  2002      2.527140 2002-03-01
267      4  2002      2.078428 2002-04-01
268      5  2002      1.454932 2002-05-01
269      6  2002      0.734981 2002-06-01
270      7  2002      0.434812 2002-07-01
271      8  2002      0.528228 2002-08-01
272      9  2002      0.323237 2002-09-01
273     10  2002     -0.353800 2002-10-01
274     11  2002     -0.184854 2002-11-01
There are enough months in the past
Target period: 03-2002 to 11-2002
Target period includes only one year

Year: 2002 - End-Month of observation: 12
Forecast Year: 2003 -  Forecast Month: 3
Dropping year: 2002  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
267      4  2002      2.078428 2002-04-01
268      5  2002      1.454932 2002-05-01
269      6  2002      0.734981 2002-06-01
270      7  2002      0.434812 2002-07-01
271      8  2002      0.528228 2002-08-01
272      9  2002      0.323237 2002-09-01
273     10  2002     -0.353800 2002-10-01
274     11  2002     -0.184854 2002-11-01
275     12  2002      1.832011 2002-12-01
There are enough months in the past
Target period: 04-2002 to 12-2002
Target period includes only one year

Year: 2003 - End-Month of observation: 1
Forecast Year: 2003 -  Forecast Month: 4
Dropping year: 2003  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
268      5  2002      1.454932 2002-05-01
269      6  2002      0.734981 2002-06-01
270      7  2002      0.434812 2002-07-01
271      8  2002      0.528228 2002-08-01
272      9  2002      0.323237 2002-09-01
273     10  2002     -0.353800 2002-10-01
274     11  2002     -0.184854 2002-11-01
275     12  2002      1.832011 2002-12-01
276      1  2003      1.662446 2003-01-01
There are enough months in the past
Target period: 05-2002 to 01-2003
Target period includes two years

Year: 2003 - End-Month of observation: 2
Forecast Year: 2003 -  Forecast Month: 5
Dropping year: 2003  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
269      6  2002      0.734981 2002-06-01
270      7  2002      0.434812 2002-07-01
271      8  2002      0.528228 2002-08-01
272      9  2002      0.323237 2002-09-01
273     10  2002     -0.353800 2002-10-01
274     11  2002     -0.184854 2002-11-01
275     12  2002      1.832011 2002-12-01
276      1  2003      1.662446 2003-01-01
277      2  2003      0.958376 2003-02-01
There are enough months in the past
Target period: 06-2002 to 02-2003
Target period includes two years

Year: 2003 - End-Month of observation: 3
Forecast Year: 2003 -  Forecast Month: 6
Dropping year: 2003  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
270      7  2002      0.434812 2002-07-01
271      8  2002      0.528228 2002-08-01
272      9  2002      0.323237 2002-09-01
273     10  2002     -0.353800 2002-10-01
274     11  2002     -0.184854 2002-11-01
275     12  2002      1.832011 2002-12-01
276      1  2003      1.662446 2003-01-01
277      2  2003      0.958376 2003-02-01
278      3  2003      0.214817 2003-03-01
There are enough months in the past
Target period: 07-2002 to 03-2003
Target period includes two years

Year: 2003 - End-Month of observation: 4
Forecast Year: 2003 -  Forecast Month: 7
Dropping year: 2003  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
271      8  2002      0.528228 2002-08-01
272      9  2002      0.323237 2002-09-01
273     10  2002     -0.353800 2002-10-01
274     11  2002     -0.184854 2002-11-01
275     12  2002      1.832011 2002-12-01
276      1  2003      1.662446 2003-01-01
277      2  2003      0.958376 2003-02-01
278      3  2003      0.214817 2003-03-01
279      4  2003     -0.689754 2003-04-01
There are enough months in the past
Target period: 08-2002 to 04-2003
Target period includes two years

Year: 2003 - End-Month of observation: 5
Forecast Year: 2003 -  Forecast Month: 8
Dropping year: 2003  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
272      9  2002      0.323237 2002-09-01
273     10  2002     -0.353800 2002-10-01
274     11  2002     -0.184854 2002-11-01
275     12  2002      1.832011 2002-12-01
276      1  2003      1.662446 2003-01-01
277      2  2003      0.958376 2003-02-01
278      3  2003      0.214817 2003-03-01
279      4  2003     -0.689754 2003-04-01
280      5  2003      0.670987 2003-05-01
There are enough months in the past
Target period: 09-2002 to 05-2003
Target period includes two years

Year: 2003 - End-Month of observation: 6
Forecast Year: 2003 -  Forecast Month: 9
Dropping year: 2003  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
273     10  2002     -0.353800 2002-10-01
274     11  2002     -0.184854 2002-11-01
275     12  2002      1.832011 2002-12-01
276      1  2003      1.662446 2003-01-01
277      2  2003      0.958376 2003-02-01
278      3  2003      0.214817 2003-03-01
279      4  2003     -0.689754 2003-04-01
280      5  2003      0.670987 2003-05-01
281      6  2003      1.084724 2003-06-01
There are enough months in the past
Target period: 10-2002 to 06-2003
Target period includes two years

Year: 2003 - End-Month of observation: 7
Forecast Year: 2003 -  Forecast Month: 10
Dropping year: 2003  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
274     11  2002     -0.184854 2002-11-01
275     12  2002      1.832011 2002-12-01
276      1  2003      1.662446 2003-01-01
277      2  2003      0.958376 2003-02-01
278      3  2003      0.214817 2003-03-01
279      4  2003     -0.689754 2003-04-01
280      5  2003      0.670987 2003-05-01
281      6  2003      1.084724 2003-06-01
282      7  2003      0.506555 2003-07-01
There are enough months in the past
Target period: 11-2002 to 07-2003
Target period includes two years

Year: 2003 - End-Month of observation: 8
Forecast Year: 2003 -  Forecast Month: 11
Dropping year: 2003  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
275     12  2002      1.832011 2002-12-01
276      1  2003      1.662446 2003-01-01
277      2  2003      0.958376 2003-02-01
278      3  2003      0.214817 2003-03-01
279      4  2003     -0.689754 2003-04-01
280      5  2003      0.670987 2003-05-01
281      6  2003      1.084724 2003-06-01
282      7  2003      0.506555 2003-07-01
283      8  2003      0.476646 2003-08-01
There are enough months in the past
Target period: 12-2002 to 08-2003
Target period includes two years

Year: 2003 - End-Month of observation: 9
Forecast Year: 2003 -  Forecast Month: 12
Dropping year: 2003  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
276      1  2003      1.662446 2003-01-01
277      2  2003      0.958376 2003-02-01
278      3  2003      0.214817 2003-03-01
279      4  2003     -0.689754 2003-04-01
280      5  2003      0.670987 2003-05-01
281      6  2003      1.084724 2003-06-01
282      7  2003      0.506555 2003-07-01
283      8  2003      0.476646 2003-08-01
284      9  2003      1.584296 2003-09-01
There are enough months in the past
Target period: 01-2003 to 09-2003
Target period includes only one year

Year: 2003 - End-Month of observation: 10
Forecast Year: 2004 -  Forecast Month: 1
Dropping year: 2003  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
277      2  2003      0.958376 2003-02-01
278      3  2003      0.214817 2003-03-01
279      4  2003     -0.689754 2003-04-01
280      5  2003      0.670987 2003-05-01
281      6  2003      1.084724 2003-06-01
282      7  2003      0.506555 2003-07-01
283      8  2003      0.476646 2003-08-01
284      9  2003      1.584296 2003-09-01
285     10  2003     -0.107711 2003-10-01
There are enough months in the past
Target period: 02-2003 to 10-2003
Target period includes only one year

Year: 2003 - End-Month of observation: 11
Forecast Year: 2004 -  Forecast Month: 2
Dropping year: 2003  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
278      3  2003      0.214817 2003-03-01
279      4  2003     -0.689754 2003-04-01
280      5  2003      0.670987 2003-05-01
281      6  2003      1.084724 2003-06-01
282      7  2003      0.506555 2003-07-01
283      8  2003      0.476646 2003-08-01
284      9  2003      1.584296 2003-09-01
285     10  2003     -0.107711 2003-10-01
286     11  2003      1.425786 2003-11-01
There are enough months in the past
Target period: 03-2003 to 11-2003
Target period includes only one year

Year: 2003 - End-Month of observation: 12
Forecast Year: 2004 -  Forecast Month: 3
Dropping year: 2003  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
279      4  2003     -0.689754 2003-04-01
280      5  2003      0.670987 2003-05-01
281      6  2003      1.084724 2003-06-01
282      7  2003      0.506555 2003-07-01
283      8  2003      0.476646 2003-08-01
284      9  2003      1.584296 2003-09-01
285     10  2003     -0.107711 2003-10-01
286     11  2003      1.425786 2003-11-01
287     12  2003      0.268160 2003-12-01
There are enough months in the past
Target period: 04-2003 to 12-2003
Target period includes only one year

Year: 2004 - End-Month of observation: 1
Forecast Year: 2004 -  Forecast Month: 4
Dropping year: 2004  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
280      5  2003      0.670987 2003-05-01
281      6  2003      1.084724 2003-06-01
282      7  2003      0.506555 2003-07-01
283      8  2003      0.476646 2003-08-01
284      9  2003      1.584296 2003-09-01
285     10  2003     -0.107711 2003-10-01
286     11  2003      1.425786 2003-11-01
287     12  2003      0.268160 2003-12-01
288      1  2004      0.220363 2004-01-01
There are enough months in the past
Target period: 05-2003 to 01-2004
Target period includes two years

Year: 2004 - End-Month of observation: 2
Forecast Year: 2004 -  Forecast Month: 5
Dropping year: 2004  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
281      6  2003      1.084724 2003-06-01
282      7  2003      0.506555 2003-07-01
283      8  2003      0.476646 2003-08-01
284      9  2003      1.584296 2003-09-01
285     10  2003     -0.107711 2003-10-01
286     11  2003      1.425786 2003-11-01
287     12  2003      0.268160 2003-12-01
288      1  2004      0.220363 2004-01-01
289      2  2004     -0.386063 2004-02-01
There are enough months in the past
Target period: 06-2003 to 02-2004
Target period includes two years

Year: 2004 - End-Month of observation: 3
Forecast Year: 2004 -  Forecast Month: 6
Dropping year: 2004  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
282      7  2003      0.506555 2003-07-01
283      8  2003      0.476646 2003-08-01
284      9  2003      1.584296 2003-09-01
285     10  2003     -0.107711 2003-10-01
286     11  2003      1.425786 2003-11-01
287     12  2003      0.268160 2003-12-01
288      1  2004      0.220363 2004-01-01
289      2  2004     -0.386063 2004-02-01
290      3  2004     -0.607739 2004-03-01
There are enough months in the past
Target period: 07-2003 to 03-2004
Target period includes two years

Year: 2004 - End-Month of observation: 4
Forecast Year: 2004 -  Forecast Month: 7
Dropping year: 2004  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
283      8  2003      0.476646 2003-08-01
284      9  2003      1.584296 2003-09-01
285     10  2003     -0.107711 2003-10-01
286     11  2003      1.425786 2003-11-01
287     12  2003      0.268160 2003-12-01
288      1  2004      0.220363 2004-01-01
289      2  2004     -0.386063 2004-02-01
290      3  2004     -0.607739 2004-03-01
291      4  2004     -0.127231 2004-04-01
There are enough months in the past
Target period: 08-2003 to 04-2004
Target period includes two years

Year: 2004 - End-Month of observation: 5
Forecast Year: 2004 -  Forecast Month: 8
Dropping year: 2004  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
284      9  2003      1.584296 2003-09-01
285     10  2003     -0.107711 2003-10-01
286     11  2003      1.425786 2003-11-01
287     12  2003      0.268160 2003-12-01
288      1  2004      0.220363 2004-01-01
289      2  2004     -0.386063 2004-02-01
290      3  2004     -0.607739 2004-03-01
291      4  2004     -0.127231 2004-04-01
292      5  2004      0.324343 2004-05-01
There are enough months in the past
Target period: 09-2003 to 05-2004
Target period includes two years

Year: 2004 - End-Month of observation: 6
Forecast Year: 2004 -  Forecast Month: 9
Dropping year: 2004  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
285     10  2003     -0.107711 2003-10-01
286     11  2003      1.425786 2003-11-01
287     12  2003      0.268160 2003-12-01
288      1  2004      0.220363 2004-01-01
289      2  2004     -0.386063 2004-02-01
290      3  2004     -0.607739 2004-03-01
291      4  2004     -0.127231 2004-04-01
292      5  2004      0.324343 2004-05-01
293      6  2004     -0.109196 2004-06-01
There are enough months in the past
Target period: 10-2003 to 06-2004
Target period includes two years

Year: 2004 - End-Month of observation: 7
Forecast Year: 2004 -  Forecast Month: 10
Dropping year: 2004  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
286     11  2003      1.425786 2003-11-01
287     12  2003      0.268160 2003-12-01
288      1  2004      0.220363 2004-01-01
289      2  2004     -0.386063 2004-02-01
290      3  2004     -0.607739 2004-03-01
291      4  2004     -0.127231 2004-04-01
292      5  2004      0.324343 2004-05-01
293      6  2004     -0.109196 2004-06-01
294      7  2004     -0.236939 2004-07-01
There are enough months in the past
Target period: 11-2003 to 07-2004
Target period includes two years

Year: 2004 - End-Month of observation: 8
Forecast Year: 2004 -  Forecast Month: 11
Dropping year: 2004  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
287     12  2003      0.268160 2003-12-01
288      1  2004      0.220363 2004-01-01
289      2  2004     -0.386063 2004-02-01
290      3  2004     -0.607739 2004-03-01
291      4  2004     -0.127231 2004-04-01
292      5  2004      0.324343 2004-05-01
293      6  2004     -0.109196 2004-06-01
294      7  2004     -0.236939 2004-07-01
295      8  2004     -0.759065 2004-08-01
There are enough months in the past
Target period: 12-2003 to 08-2004
Target period includes two years

Year: 2004 - End-Month of observation: 9
Forecast Year: 2004 -  Forecast Month: 12
Dropping year: 2004  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
288      1  2004      0.220363 2004-01-01
289      2  2004     -0.386063 2004-02-01
290      3  2004     -0.607739 2004-03-01
291      4  2004     -0.127231 2004-04-01
292      5  2004      0.324343 2004-05-01
293      6  2004     -0.109196 2004-06-01
294      7  2004     -0.236939 2004-07-01
295      8  2004     -0.759065 2004-08-01
296      9  2004      0.270234 2004-09-01
There are enough months in the past
Target period: 01-2004 to 09-2004
Target period includes only one year

Year: 2004 - End-Month of observation: 10
Forecast Year: 2005 -  Forecast Month: 1
Dropping year: 2004  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
289      2  2004     -0.386063 2004-02-01
290      3  2004     -0.607739 2004-03-01
291      4  2004     -0.127231 2004-04-01
292      5  2004      0.324343 2004-05-01
293      6  2004     -0.109196 2004-06-01
294      7  2004     -0.236939 2004-07-01
295      8  2004     -0.759065 2004-08-01
296      9  2004      0.270234 2004-09-01
297     10  2004      0.927208 2004-10-01
There are enough months in the past
Target period: 02-2004 to 10-2004
Target period includes only one year

Year: 2004 - End-Month of observation: 11
Forecast Year: 2005 -  Forecast Month: 2
Dropping year: 2004  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
290      3  2004     -0.607739 2004-03-01
291      4  2004     -0.127231 2004-04-01
292      5  2004      0.324343 2004-05-01
293      6  2004     -0.109196 2004-06-01
294      7  2004     -0.236939 2004-07-01
295      8  2004     -0.759065 2004-08-01
296      9  2004      0.270234 2004-09-01
297     10  2004      0.927208 2004-10-01
298     11  2004      0.165456 2004-11-01
There are enough months in the past
Target period: 03-2004 to 11-2004
Target period includes only one year

Year: 2004 - End-Month of observation: 12
Forecast Year: 2005 -  Forecast Month: 3
Dropping year: 2004  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
291      4  2004     -0.127231 2004-04-01
292      5  2004      0.324343 2004-05-01
293      6  2004     -0.109196 2004-06-01
294      7  2004     -0.236939 2004-07-01
295      8  2004     -0.759065 2004-08-01
296      9  2004      0.270234 2004-09-01
297     10  2004      0.927208 2004-10-01
298     11  2004      0.165456 2004-11-01
299     12  2004     -0.251580 2004-12-01
There are enough months in the past
Target period: 04-2004 to 12-2004
Target period includes only one year

Year: 2005 - End-Month of observation: 1
Forecast Year: 2005 -  Forecast Month: 4
Dropping year: 2005  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
292      5  2004      0.324343 2004-05-01
293      6  2004     -0.109196 2004-06-01
294      7  2004     -0.236939 2004-07-01
295      8  2004     -0.759065 2004-08-01
296      9  2004      0.270234 2004-09-01
297     10  2004      0.927208 2004-10-01
298     11  2004      0.165456 2004-11-01
299     12  2004     -0.251580 2004-12-01
300      1  2005      0.214728 2005-01-01
There are enough months in the past
Target period: 05-2004 to 01-2005
Target period includes two years

Year: 2005 - End-Month of observation: 2
Forecast Year: 2005 -  Forecast Month: 5
Dropping year: 2005  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
293      6  2004     -0.109196 2004-06-01
294      7  2004     -0.236939 2004-07-01
295      8  2004     -0.759065 2004-08-01
296      9  2004      0.270234 2004-09-01
297     10  2004      0.927208 2004-10-01
298     11  2004      0.165456 2004-11-01
299     12  2004     -0.251580 2004-12-01
300      1  2005      0.214728 2005-01-01
301      2  2005      0.492906 2005-02-01
There are enough months in the past
Target period: 06-2004 to 02-2005
Target period includes two years

Year: 2005 - End-Month of observation: 3
Forecast Year: 2005 -  Forecast Month: 6
Dropping year: 2005  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
294      7  2004     -0.236939 2004-07-01
295      8  2004     -0.759065 2004-08-01
296      9  2004      0.270234 2004-09-01
297     10  2004      0.927208 2004-10-01
298     11  2004      0.165456 2004-11-01
299     12  2004     -0.251580 2004-12-01
300      1  2005      0.214728 2005-01-01
301      2  2005      0.492906 2005-02-01
302      3  2005     -0.278698 2005-03-01
There are enough months in the past
Target period: 07-2004 to 03-2005
Target period includes two years

Year: 2005 - End-Month of observation: 4
Forecast Year: 2005 -  Forecast Month: 7
Dropping year: 2005  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
295      8  2004     -0.759065 2004-08-01
296      9  2004      0.270234 2004-09-01
297     10  2004      0.927208 2004-10-01
298     11  2004      0.165456 2004-11-01
299     12  2004     -0.251580 2004-12-01
300      1  2005      0.214728 2005-01-01
301      2  2005      0.492906 2005-02-01
302      3  2005     -0.278698 2005-03-01
303      4  2005      1.688282 2005-04-01
There are enough months in the past
Target period: 08-2004 to 04-2005
Target period includes two years

Year: 2005 - End-Month of observation: 5
Forecast Year: 2005 -  Forecast Month: 8
Dropping year: 2005  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
296      9  2004      0.270234 2004-09-01
297     10  2004      0.927208 2004-10-01
298     11  2004      0.165456 2004-11-01
299     12  2004     -0.251580 2004-12-01
300      1  2005      0.214728 2005-01-01
301      2  2005      0.492906 2005-02-01
302      3  2005     -0.278698 2005-03-01
303      4  2005      1.688282 2005-04-01
304      5  2005      1.216989 2005-05-01
There are enough months in the past
Target period: 09-2004 to 05-2005
Target period includes two years

Year: 2005 - End-Month of observation: 6
Forecast Year: 2005 -  Forecast Month: 9
Dropping year: 2005  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
297     10  2004      0.927208 2004-10-01
298     11  2004      0.165456 2004-11-01
299     12  2004     -0.251580 2004-12-01
300      1  2005      0.214728 2005-01-01
301      2  2005      0.492906 2005-02-01
302      3  2005     -0.278698 2005-03-01
303      4  2005      1.688282 2005-04-01
304      5  2005      1.216989 2005-05-01
305      6  2005      1.533202 2005-06-01
There are enough months in the past
Target period: 10-2004 to 06-2005
Target period includes two years

Year: 2005 - End-Month of observation: 7
Forecast Year: 2005 -  Forecast Month: 10
Dropping year: 2005  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
298     11  2004      0.165456 2004-11-01
299     12  2004     -0.251580 2004-12-01
300      1  2005      0.214728 2005-01-01
301      2  2005      0.492906 2005-02-01
302      3  2005     -0.278698 2005-03-01
303      4  2005      1.688282 2005-04-01
304      5  2005      1.216989 2005-05-01
305      6  2005      1.533202 2005-06-01
306      7  2005      0.311917 2005-07-01
There are enough months in the past
Target period: 11-2004 to 07-2005
Target period includes two years

Year: 2005 - End-Month of observation: 8
Forecast Year: 2005 -  Forecast Month: 11
Dropping year: 2005  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
299     12  2004     -0.251580 2004-12-01
300      1  2005      0.214728 2005-01-01
301      2  2005      0.492906 2005-02-01
302      3  2005     -0.278698 2005-03-01
303      4  2005      1.688282 2005-04-01
304      5  2005      1.216989 2005-05-01
305      6  2005      1.533202 2005-06-01
306      7  2005      0.311917 2005-07-01
307      8  2005     -1.105045 2005-08-01
There are enough months in the past
Target period: 12-2004 to 08-2005
Target period includes two years

Year: 2005 - End-Month of observation: 9
Forecast Year: 2005 -  Forecast Month: 12
Dropping year: 2005  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
300      1  2005      0.214728 2005-01-01
301      2  2005      0.492906 2005-02-01
302      3  2005     -0.278698 2005-03-01
303      4  2005      1.688282 2005-04-01
304      5  2005      1.216989 2005-05-01
305      6  2005      1.533202 2005-06-01
306      7  2005      0.311917 2005-07-01
307      8  2005     -1.105045 2005-08-01
308      9  2005     -0.408260 2005-09-01
There are enough months in the past
Target period: 01-2005 to 09-2005
Target period includes only one year

Year: 2005 - End-Month of observation: 10
Forecast Year: 2006 -  Forecast Month: 1
Dropping year: 2005  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
301      2  2005      0.492906 2005-02-01
302      3  2005     -0.278698 2005-03-01
303      4  2005      1.688282 2005-04-01
304      5  2005      1.216989 2005-05-01
305      6  2005      1.533202 2005-06-01
306      7  2005      0.311917 2005-07-01
307      8  2005     -1.105045 2005-08-01
308      9  2005     -0.408260 2005-09-01
309     10  2005     -0.666348 2005-10-01
There are enough months in the past
Target period: 02-2005 to 10-2005
Target period includes only one year

Year: 2005 - End-Month of observation: 11
Forecast Year: 2006 -  Forecast Month: 2
Dropping year: 2005  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
302      3  2005     -0.278698 2005-03-01
303      4  2005      1.688282 2005-04-01
304      5  2005      1.216989 2005-05-01
305      6  2005      1.533202 2005-06-01
306      7  2005      0.311917 2005-07-01
307      8  2005     -1.105045 2005-08-01
308      9  2005     -0.408260 2005-09-01
309     10  2005     -0.666348 2005-10-01
310     11  2005     -0.857427 2005-11-01
There are enough months in the past
Target period: 03-2005 to 11-2005
Target period includes only one year

Year: 2005 - End-Month of observation: 12
Forecast Year: 2006 -  Forecast Month: 3
Dropping year: 2005  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
303      4  2005      1.688282 2005-04-01
304      5  2005      1.216989 2005-05-01
305      6  2005      1.533202 2005-06-01
306      7  2005      0.311917 2005-07-01
307      8  2005     -1.105045 2005-08-01
308      9  2005     -0.408260 2005-09-01
309     10  2005     -0.666348 2005-10-01
310     11  2005     -0.857427 2005-11-01
311     12  2005     -0.263708 2005-12-01
There are enough months in the past
Target period: 04-2005 to 12-2005
Target period includes only one year

Year: 2006 - End-Month of observation: 1
Forecast Year: 2006 -  Forecast Month: 4
Dropping year: 2006  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
304      5  2005      1.216989 2005-05-01
305      6  2005      1.533202 2005-06-01
306      7  2005      0.311917 2005-07-01
307      8  2005     -1.105045 2005-08-01
308      9  2005     -0.408260 2005-09-01
309     10  2005     -0.666348 2005-10-01
310     11  2005     -0.857427 2005-11-01
311     12  2005     -0.263708 2005-12-01
312      1  2006      2.427332 2006-01-01
There are enough months in the past
Target period: 05-2005 to 01-2006
Target period includes two years

Year: 2006 - End-Month of observation: 2
Forecast Year: 2006 -  Forecast Month: 5
Dropping year: 2006  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
305      6  2005      1.533202 2005-06-01
306      7  2005      0.311917 2005-07-01
307      8  2005     -1.105045 2005-08-01
308      9  2005     -0.408260 2005-09-01
309     10  2005     -0.666348 2005-10-01
310     11  2005     -0.857427 2005-11-01
311     12  2005     -0.263708 2005-12-01
312      1  2006      2.427332 2006-01-01
313      2  2006     -0.137558 2006-02-01
There are enough months in the past
Target period: 06-2005 to 02-2006
Target period includes two years

Year: 2006 - End-Month of observation: 3
Forecast Year: 2006 -  Forecast Month: 6
Dropping year: 2006  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
306      7  2005      0.311917 2005-07-01
307      8  2005     -1.105045 2005-08-01
308      9  2005     -0.408260 2005-09-01
309     10  2005     -0.666348 2005-10-01
310     11  2005     -0.857427 2005-11-01
311     12  2005     -0.263708 2005-12-01
312      1  2006      2.427332 2006-01-01
313      2  2006     -0.137558 2006-02-01
314      3  2006      0.094414 2006-03-01
There are enough months in the past
Target period: 07-2005 to 03-2006
Target period includes two years

Year: 2006 - End-Month of observation: 4
Forecast Year: 2006 -  Forecast Month: 7
Dropping year: 2006  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
307      8  2005     -1.105045 2005-08-01
308      9  2005     -0.408260 2005-09-01
309     10  2005     -0.666348 2005-10-01
310     11  2005     -0.857427 2005-11-01
311     12  2005     -0.263708 2005-12-01
312      1  2006      2.427332 2006-01-01
313      2  2006     -0.137558 2006-02-01
314      3  2006      0.094414 2006-03-01
315      4  2006     -0.487829 2006-04-01
There are enough months in the past
Target period: 08-2005 to 04-2006
Target period includes two years

Year: 2006 - End-Month of observation: 5
Forecast Year: 2006 -  Forecast Month: 8
Dropping year: 2006  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
308      9  2005     -0.408260 2005-09-01
309     10  2005     -0.666348 2005-10-01
310     11  2005     -0.857427 2005-11-01
311     12  2005     -0.263708 2005-12-01
312      1  2006      2.427332 2006-01-01
313      2  2006     -0.137558 2006-02-01
314      3  2006      0.094414 2006-03-01
315      4  2006     -0.487829 2006-04-01
316      5  2006     -0.986345 2006-05-01
There are enough months in the past
Target period: 09-2005 to 05-2006
Target period includes two years

Year: 2006 - End-Month of observation: 6
Forecast Year: 2006 -  Forecast Month: 9
Dropping year: 2006  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
309     10  2005     -0.666348 2005-10-01
310     11  2005     -0.857427 2005-11-01
311     12  2005     -0.263708 2005-12-01
312      1  2006      2.427332 2006-01-01
313      2  2006     -0.137558 2006-02-01
314      3  2006      0.094414 2006-03-01
315      4  2006     -0.487829 2006-04-01
316      5  2006     -0.986345 2006-05-01
317      6  2006      1.317109 2006-06-01
There are enough months in the past
Target period: 10-2005 to 06-2006
Target period includes two years

Year: 2006 - End-Month of observation: 7
Forecast Year: 2006 -  Forecast Month: 10
Dropping year: 2006  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
310     11  2005     -0.857427 2005-11-01
311     12  2005     -0.263708 2005-12-01
312      1  2006      2.427332 2006-01-01
313      2  2006     -0.137558 2006-02-01
314      3  2006      0.094414 2006-03-01
315      4  2006     -0.487829 2006-04-01
316      5  2006     -0.986345 2006-05-01
317      6  2006      1.317109 2006-06-01
318      7  2006      0.214526 2006-07-01
There are enough months in the past
Target period: 11-2005 to 07-2006
Target period includes two years

Year: 2006 - End-Month of observation: 8
Forecast Year: 2006 -  Forecast Month: 11
Dropping year: 2006  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
311     12  2005     -0.263708 2005-12-01
312      1  2006      2.427332 2006-01-01
313      2  2006     -0.137558 2006-02-01
314      3  2006      0.094414 2006-03-01
315      4  2006     -0.487829 2006-04-01
316      5  2006     -0.986345 2006-05-01
317      6  2006      1.317109 2006-06-01
318      7  2006      0.214526 2006-07-01
319      8  2006      0.331471 2006-08-01
There are enough months in the past
Target period: 12-2005 to 08-2006
Target period includes two years

Year: 2006 - End-Month of observation: 9
Forecast Year: 2006 -  Forecast Month: 12
Dropping year: 2006  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
312      1  2006      2.427332 2006-01-01
313      2  2006     -0.137558 2006-02-01
314      3  2006      0.094414 2006-03-01
315      4  2006     -0.487829 2006-04-01
316      5  2006     -0.986345 2006-05-01
317      6  2006      1.317109 2006-06-01
318      7  2006      0.214526 2006-07-01
319      8  2006      0.331471 2006-08-01
320      9  2006     -1.201608 2006-09-01
There are enough months in the past
Target period: 01-2006 to 09-2006
Target period includes only one year

Year: 2006 - End-Month of observation: 10
Forecast Year: 2007 -  Forecast Month: 1
Dropping year: 2006  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
313      2  2006     -0.137558 2006-02-01
314      3  2006      0.094414 2006-03-01
315      4  2006     -0.487829 2006-04-01
316      5  2006     -0.986345 2006-05-01
317      6  2006      1.317109 2006-06-01
318      7  2006      0.214526 2006-07-01
319      8  2006      0.331471 2006-08-01
320      9  2006     -1.201608 2006-09-01
321     10  2006     -0.124688 2006-10-01
There are enough months in the past
Target period: 02-2006 to 10-2006
Target period includes only one year

Year: 2006 - End-Month of observation: 11
Forecast Year: 2007 -  Forecast Month: 2
Dropping year: 2006  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
314      3  2006      0.094414 2006-03-01
315      4  2006     -0.487829 2006-04-01
316      5  2006     -0.986345 2006-05-01
317      6  2006      1.317109 2006-06-01
318      7  2006      0.214526 2006-07-01
319      8  2006      0.331471 2006-08-01
320      9  2006     -1.201608 2006-09-01
321     10  2006     -0.124688 2006-10-01
322     11  2006      0.686729 2006-11-01
There are enough months in the past
Target period: 03-2006 to 11-2006
Target period includes only one year

Year: 2006 - End-Month of observation: 12
Forecast Year: 2007 -  Forecast Month: 3
Dropping year: 2006  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
315      4  2006     -0.487829 2006-04-01
316      5  2006     -0.986345 2006-05-01
317      6  2006      1.317109 2006-06-01
318      7  2006      0.214526 2006-07-01
319      8  2006      0.331471 2006-08-01
320      9  2006     -1.201608 2006-09-01
321     10  2006     -0.124688 2006-10-01
322     11  2006      0.686729 2006-11-01
323     12  2006     -0.120632 2006-12-01
There are enough months in the past
Target period: 04-2006 to 12-2006
Target period includes only one year

Year: 2007 - End-Month of observation: 1
Forecast Year: 2007 -  Forecast Month: 4
Dropping year: 2007  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
316      5  2006     -0.986345 2006-05-01
317      6  2006      1.317109 2006-06-01
318      7  2006      0.214526 2006-07-01
319      8  2006      0.331471 2006-08-01
320      9  2006     -1.201608 2006-09-01
321     10  2006     -0.124688 2006-10-01
322     11  2006      0.686729 2006-11-01
323     12  2006     -0.120632 2006-12-01
324      1  2007     -0.405921 2007-01-01
There are enough months in the past
Target period: 05-2006 to 01-2007
Target period includes two years

Year: 2007 - End-Month of observation: 2
Forecast Year: 2007 -  Forecast Month: 5
Dropping year: 2007  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
317      6  2006      1.317109 2006-06-01
318      7  2006      0.214526 2006-07-01
319      8  2006      0.331471 2006-08-01
320      9  2006     -1.201608 2006-09-01
321     10  2006     -0.124688 2006-10-01
322     11  2006      0.686729 2006-11-01
323     12  2006     -0.120632 2006-12-01
324      1  2007     -0.405921 2007-01-01
325      2  2007     -0.672549 2007-02-01
There are enough months in the past
Target period: 06-2006 to 02-2007
Target period includes two years

Year: 2007 - End-Month of observation: 3
Forecast Year: 2007 -  Forecast Month: 6
Dropping year: 2007  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
318      7  2006      0.214526 2006-07-01
319      8  2006      0.331471 2006-08-01
320      9  2006     -1.201608 2006-09-01
321     10  2006     -0.124688 2006-10-01
322     11  2006      0.686729 2006-11-01
323     12  2006     -0.120632 2006-12-01
324      1  2007     -0.405921 2007-01-01
325      2  2007     -0.672549 2007-02-01
326      3  2007      2.332151 2007-03-01
There are enough months in the past
Target period: 07-2006 to 03-2007
Target period includes two years

Year: 2007 - End-Month of observation: 4
Forecast Year: 2007 -  Forecast Month: 7
Dropping year: 2007  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
319      8  2006      0.331471 2006-08-01
320      9  2006     -1.201608 2006-09-01
321     10  2006     -0.124688 2006-10-01
322     11  2006      0.686729 2006-11-01
323     12  2006     -0.120632 2006-12-01
324      1  2007     -0.405921 2007-01-01
325      2  2007     -0.672549 2007-02-01
326      3  2007      2.332151 2007-03-01
327      4  2007      1.956936 2007-04-01
There are enough months in the past
Target period: 08-2006 to 04-2007
Target period includes two years

Year: 2007 - End-Month of observation: 5
Forecast Year: 2007 -  Forecast Month: 8
Dropping year: 2007  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
320      9  2006     -1.201608 2006-09-01
321     10  2006     -0.124688 2006-10-01
322     11  2006      0.686729 2006-11-01
323     12  2006     -0.120632 2006-12-01
324      1  2007     -0.405921 2007-01-01
325      2  2007     -0.672549 2007-02-01
326      3  2007      2.332151 2007-03-01
327      4  2007      1.956936 2007-04-01
328      5  2007      1.713232 2007-05-01
There are enough months in the past
Target period: 09-2006 to 05-2007
Target period includes two years

Year: 2007 - End-Month of observation: 6
Forecast Year: 2007 -  Forecast Month: 9
Dropping year: 2007  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
321     10  2006     -0.124688 2006-10-01
322     11  2006      0.686729 2006-11-01
323     12  2006     -0.120632 2006-12-01
324      1  2007     -0.405921 2007-01-01
325      2  2007     -0.672549 2007-02-01
326      3  2007      2.332151 2007-03-01
327      4  2007      1.956936 2007-04-01
328      5  2007      1.713232 2007-05-01
329      6  2007     -0.217848 2007-06-01
There are enough months in the past
Target period: 10-2006 to 06-2007
Target period includes two years

Year: 2007 - End-Month of observation: 7
Forecast Year: 2007 -  Forecast Month: 10
Dropping year: 2007  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
322     11  2006      0.686729 2006-11-01
323     12  2006     -0.120632 2006-12-01
324      1  2007     -0.405921 2007-01-01
325      2  2007     -0.672549 2007-02-01
326      3  2007      2.332151 2007-03-01
327      4  2007      1.956936 2007-04-01
328      5  2007      1.713232 2007-05-01
329      6  2007     -0.217848 2007-06-01
330      7  2007     -1.384830 2007-07-01
There are enough months in the past
Target period: 11-2006 to 07-2007
Target period includes two years

Year: 2007 - End-Month of observation: 8
Forecast Year: 2007 -  Forecast Month: 11
Dropping year: 2007  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
323     12  2006     -0.120632 2006-12-01
324      1  2007     -0.405921 2007-01-01
325      2  2007     -0.672549 2007-02-01
326      3  2007      2.332151 2007-03-01
327      4  2007      1.956936 2007-04-01
328      5  2007      1.713232 2007-05-01
329      6  2007     -0.217848 2007-06-01
330      7  2007     -1.384830 2007-07-01
331      8  2007     -0.278306 2007-08-01
There are enough months in the past
Target period: 12-2006 to 08-2007
Target period includes two years

Year: 2007 - End-Month of observation: 9
Forecast Year: 2007 -  Forecast Month: 12
Dropping year: 2007  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
324      1  2007     -0.405921 2007-01-01
325      2  2007     -0.672549 2007-02-01
326      3  2007      2.332151 2007-03-01
327      4  2007      1.956936 2007-04-01
328      5  2007      1.713232 2007-05-01
329      6  2007     -0.217848 2007-06-01
330      7  2007     -1.384830 2007-07-01
331      8  2007     -0.278306 2007-08-01
332      9  2007      1.047919 2007-09-01
There are enough months in the past
Target period: 01-2007 to 09-2007
Target period includes only one year

Year: 2007 - End-Month of observation: 10
Forecast Year: 2008 -  Forecast Month: 1
Dropping year: 2007  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
325      2  2007     -0.672549 2007-02-01
326      3  2007      2.332151 2007-03-01
327      4  2007      1.956936 2007-04-01
328      5  2007      1.713232 2007-05-01
329      6  2007     -0.217848 2007-06-01
330      7  2007     -1.384830 2007-07-01
331      8  2007     -0.278306 2007-08-01
332      9  2007      1.047919 2007-09-01
333     10  2007      1.285197 2007-10-01
There are enough months in the past
Target period: 02-2007 to 10-2007
Target period includes only one year

Year: 2007 - End-Month of observation: 11
Forecast Year: 2008 -  Forecast Month: 2
Dropping year: 2007  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
326      3  2007      2.332151 2007-03-01
327      4  2007      1.956936 2007-04-01
328      5  2007      1.713232 2007-05-01
329      6  2007     -0.217848 2007-06-01
330      7  2007     -1.384830 2007-07-01
331      8  2007     -0.278306 2007-08-01
332      9  2007      1.047919 2007-09-01
333     10  2007      1.285197 2007-10-01
334     11  2007     -0.685761 2007-11-01
There are enough months in the past
Target period: 03-2007 to 11-2007
Target period includes only one year

Year: 2007 - End-Month of observation: 12
Forecast Year: 2008 -  Forecast Month: 3
Dropping year: 2007  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
327      4  2007      1.956936 2007-04-01
328      5  2007      1.713232 2007-05-01
329      6  2007     -0.217848 2007-06-01
330      7  2007     -1.384830 2007-07-01
331      8  2007     -0.278306 2007-08-01
332      9  2007      1.047919 2007-09-01
333     10  2007      1.285197 2007-10-01
334     11  2007     -0.685761 2007-11-01
335     12  2007     -0.485044 2007-12-01
There are enough months in the past
Target period: 04-2007 to 12-2007
Target period includes only one year

Year: 2008 - End-Month of observation: 1
Forecast Year: 2008 -  Forecast Month: 4
Dropping year: 2008  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
328      5  2007      1.713232 2007-05-01
329      6  2007     -0.217848 2007-06-01
330      7  2007     -1.384830 2007-07-01
331      8  2007     -0.278306 2007-08-01
332      9  2007      1.047919 2007-09-01
333     10  2007      1.285197 2007-10-01
334     11  2007     -0.685761 2007-11-01
335     12  2007     -0.485044 2007-12-01
336      1  2008     -0.069919 2008-01-01
There are enough months in the past
Target period: 05-2007 to 01-2008
Target period includes two years

Year: 2008 - End-Month of observation: 2
Forecast Year: 2008 -  Forecast Month: 5
Dropping year: 2008  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
329      6  2007     -0.217848 2007-06-01
330      7  2007     -1.384830 2007-07-01
331      8  2007     -0.278306 2007-08-01
332      9  2007      1.047919 2007-09-01
333     10  2007      1.285197 2007-10-01
334     11  2007     -0.685761 2007-11-01
335     12  2007     -0.485044 2007-12-01
336      1  2008     -0.069919 2008-01-01
337      2  2008     -0.303736 2008-02-01
There are enough months in the past
Target period: 06-2007 to 02-2008
Target period includes two years

Year: 2008 - End-Month of observation: 3
Forecast Year: 2008 -  Forecast Month: 6
Dropping year: 2008  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
330      7  2007     -1.384830 2007-07-01
331      8  2007     -0.278306 2007-08-01
332      9  2007      1.047919 2007-09-01
333     10  2007      1.285197 2007-10-01
334     11  2007     -0.685761 2007-11-01
335     12  2007     -0.485044 2007-12-01
336      1  2008     -0.069919 2008-01-01
337      2  2008     -0.303736 2008-02-01
338      3  2008      0.803340 2008-03-01
There are enough months in the past
Target period: 07-2007 to 03-2008
Target period includes two years

Year: 2008 - End-Month of observation: 4
Forecast Year: 2008 -  Forecast Month: 7
Dropping year: 2008  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
331      8  2007     -0.278306 2007-08-01
332      9  2007      1.047919 2007-09-01
333     10  2007      1.285197 2007-10-01
334     11  2007     -0.685761 2007-11-01
335     12  2007     -0.485044 2007-12-01
336      1  2008     -0.069919 2008-01-01
337      2  2008     -0.303736 2008-02-01
338      3  2008      0.803340 2008-03-01
339      4  2008     -0.653459 2008-04-01
There are enough months in the past
Target period: 08-2007 to 04-2008
Target period includes two years

Year: 2008 - End-Month of observation: 5
Forecast Year: 2008 -  Forecast Month: 8
Dropping year: 2008  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
332      9  2007      1.047919 2007-09-01
333     10  2007      1.285197 2007-10-01
334     11  2007     -0.685761 2007-11-01
335     12  2007     -0.485044 2007-12-01
336      1  2008     -0.069919 2008-01-01
337      2  2008     -0.303736 2008-02-01
338      3  2008      0.803340 2008-03-01
339      4  2008     -0.653459 2008-04-01
340      5  2008     -0.864665 2008-05-01
There are enough months in the past
Target period: 09-2007 to 05-2008
Target period includes two years

Year: 2008 - End-Month of observation: 6
Forecast Year: 2008 -  Forecast Month: 9
Dropping year: 2008  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
333     10  2007      1.285197 2007-10-01
334     11  2007     -0.685761 2007-11-01
335     12  2007     -0.485044 2007-12-01
336      1  2008     -0.069919 2008-01-01
337      2  2008     -0.303736 2008-02-01
338      3  2008      0.803340 2008-03-01
339      4  2008     -0.653459 2008-04-01
340      5  2008     -0.864665 2008-05-01
341      6  2008     -0.893280 2008-06-01
There are enough months in the past
Target period: 10-2007 to 06-2008
Target period includes two years

Year: 2008 - End-Month of observation: 7
Forecast Year: 2008 -  Forecast Month: 10
Dropping year: 2008  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
334     11  2007     -0.685761 2007-11-01
335     12  2007     -0.485044 2007-12-01
336      1  2008     -0.069919 2008-01-01
337      2  2008     -0.303736 2008-02-01
338      3  2008      0.803340 2008-03-01
339      4  2008     -0.653459 2008-04-01
340      5  2008     -0.864665 2008-05-01
341      6  2008     -0.893280 2008-06-01
342      7  2008     -0.367381 2008-07-01
There are enough months in the past
Target period: 11-2007 to 07-2008
Target period includes two years

Year: 2008 - End-Month of observation: 8
Forecast Year: 2008 -  Forecast Month: 11
Dropping year: 2008  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
335     12  2007     -0.485044 2007-12-01
336      1  2008     -0.069919 2008-01-01
337      2  2008     -0.303736 2008-02-01
338      3  2008      0.803340 2008-03-01
339      4  2008     -0.653459 2008-04-01
340      5  2008     -0.864665 2008-05-01
341      6  2008     -0.893280 2008-06-01
342      7  2008     -0.367381 2008-07-01
343      8  2008     -1.034313 2008-08-01
There are enough months in the past
Target period: 12-2007 to 08-2008
Target period includes two years

Year: 2008 - End-Month of observation: 9
Forecast Year: 2008 -  Forecast Month: 12
Dropping year: 2008  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
336      1  2008     -0.069919 2008-01-01
337      2  2008     -0.303736 2008-02-01
338      3  2008      0.803340 2008-03-01
339      4  2008     -0.653459 2008-04-01
340      5  2008     -0.864665 2008-05-01
341      6  2008     -0.893280 2008-06-01
342      7  2008     -0.367381 2008-07-01
343      8  2008     -1.034313 2008-08-01
344      9  2008     -0.988840 2008-09-01
There are enough months in the past
Target period: 01-2008 to 09-2008
Target period includes only one year

Year: 2008 - End-Month of observation: 10
Forecast Year: 2009 -  Forecast Month: 1
Dropping year: 2008  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
337      2  2008     -0.303736 2008-02-01
338      3  2008      0.803340 2008-03-01
339      4  2008     -0.653459 2008-04-01
340      5  2008     -0.864665 2008-05-01
341      6  2008     -0.893280 2008-06-01
342      7  2008     -0.367381 2008-07-01
343      8  2008     -1.034313 2008-08-01
344      9  2008     -0.988840 2008-09-01
345     10  2008     -1.163935 2008-10-01
There are enough months in the past
Target period: 02-2008 to 10-2008
Target period includes only one year

Year: 2008 - End-Month of observation: 11
Forecast Year: 2009 -  Forecast Month: 2
Dropping year: 2008  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
338      3  2008      0.803340 2008-03-01
339      4  2008     -0.653459 2008-04-01
340      5  2008     -0.864665 2008-05-01
341      6  2008     -0.893280 2008-06-01
342      7  2008     -0.367381 2008-07-01
343      8  2008     -1.034313 2008-08-01
344      9  2008     -0.988840 2008-09-01
345     10  2008     -1.163935 2008-10-01
346     11  2008     -1.384777 2008-11-01
There are enough months in the past
Target period: 03-2008 to 11-2008
Target period includes only one year

Year: 2008 - End-Month of observation: 12
Forecast Year: 2009 -  Forecast Month: 3
Dropping year: 2008  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
339      4  2008     -0.653459 2008-04-01
340      5  2008     -0.864665 2008-05-01
341      6  2008     -0.893280 2008-06-01
342      7  2008     -0.367381 2008-07-01
343      8  2008     -1.034313 2008-08-01
344      9  2008     -0.988840 2008-09-01
345     10  2008     -1.163935 2008-10-01
346     11  2008     -1.384777 2008-11-01
347     12  2008     -0.710303 2008-12-01
There are enough months in the past
Target period: 04-2008 to 12-2008
Target period includes only one year

Year: 2009 - End-Month of observation: 1
Forecast Year: 2009 -  Forecast Month: 4
Dropping year: 2009  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
340      5  2008     -0.864665 2008-05-01
341      6  2008     -0.893280 2008-06-01
342      7  2008     -0.367381 2008-07-01
343      8  2008     -1.034313 2008-08-01
344      9  2008     -0.988840 2008-09-01
345     10  2008     -1.163935 2008-10-01
346     11  2008     -1.384777 2008-11-01
347     12  2008     -0.710303 2008-12-01
348      1  2009     -0.275124 2009-01-01
There are enough months in the past
Target period: 05-2008 to 01-2009
Target period includes two years

Year: 2009 - End-Month of observation: 2
Forecast Year: 2009 -  Forecast Month: 5
Dropping year: 2009  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
341      6  2008     -0.893280 2008-06-01
342      7  2008     -0.367381 2008-07-01
343      8  2008     -1.034313 2008-08-01
344      9  2008     -0.988840 2008-09-01
345     10  2008     -1.163935 2008-10-01
346     11  2008     -1.384777 2008-11-01
347     12  2008     -0.710303 2008-12-01
348      1  2009     -0.275124 2009-01-01
349      2  2009      0.213084 2009-02-01
There are enough months in the past
Target period: 06-2008 to 02-2009
Target period includes two years

Year: 2009 - End-Month of observation: 3
Forecast Year: 2009 -  Forecast Month: 6
Dropping year: 2009  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
342      7  2008     -0.367381 2008-07-01
343      8  2008     -1.034313 2008-08-01
344      9  2008     -0.988840 2008-09-01
345     10  2008     -1.163935 2008-10-01
346     11  2008     -1.384777 2008-11-01
347     12  2008     -0.710303 2008-12-01
348      1  2009     -0.275124 2009-01-01
349      2  2009      0.213084 2009-02-01
350      3  2009      0.482773 2009-03-01
There are enough months in the past
Target period: 07-2008 to 03-2009
Target period includes two years

Year: 2009 - End-Month of observation: 4
Forecast Year: 2009 -  Forecast Month: 7
Dropping year: 2009  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
343      8  2008     -1.034313 2008-08-01
344      9  2008     -0.988840 2008-09-01
345     10  2008     -1.163935 2008-10-01
346     11  2008     -1.384777 2008-11-01
347     12  2008     -0.710303 2008-12-01
348      1  2009     -0.275124 2009-01-01
349      2  2009      0.213084 2009-02-01
350      3  2009      0.482773 2009-03-01
351      4  2009     -0.651857 2009-04-01
There are enough months in the past
Target period: 08-2008 to 04-2009
Target period includes two years

Year: 2009 - End-Month of observation: 5
Forecast Year: 2009 -  Forecast Month: 8
Dropping year: 2009  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
344      9  2008     -0.988840 2008-09-01
345     10  2008     -1.163935 2008-10-01
346     11  2008     -1.384777 2008-11-01
347     12  2008     -0.710303 2008-12-01
348      1  2009     -0.275124 2009-01-01
349      2  2009      0.213084 2009-02-01
350      3  2009      0.482773 2009-03-01
351      4  2009     -0.651857 2009-04-01
352      5  2009     -1.028210 2009-05-01
There are enough months in the past
Target period: 09-2008 to 05-2009
Target period includes two years

Year: 2009 - End-Month of observation: 6
Forecast Year: 2009 -  Forecast Month: 9
Dropping year: 2009  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
345     10  2008     -1.163935 2008-10-01
346     11  2008     -1.384777 2008-11-01
347     12  2008     -0.710303 2008-12-01
348      1  2009     -0.275124 2009-01-01
349      2  2009      0.213084 2009-02-01
350      3  2009      0.482773 2009-03-01
351      4  2009     -0.651857 2009-04-01
352      5  2009     -1.028210 2009-05-01
353      6  2009     -0.582289 2009-06-01
There are enough months in the past
Target period: 10-2008 to 06-2009
Target period includes two years

Year: 2009 - End-Month of observation: 7
Forecast Year: 2009 -  Forecast Month: 10
Dropping year: 2009  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
346     11  2008     -1.384777 2008-11-01
347     12  2008     -0.710303 2008-12-01
348      1  2009     -0.275124 2009-01-01
349      2  2009      0.213084 2009-02-01
350      3  2009      0.482773 2009-03-01
351      4  2009     -0.651857 2009-04-01
352      5  2009     -1.028210 2009-05-01
353      6  2009     -0.582289 2009-06-01
354      7  2009      1.067286 2009-07-01
There are enough months in the past
Target period: 11-2008 to 07-2009
Target period includes two years

Year: 2009 - End-Month of observation: 8
Forecast Year: 2009 -  Forecast Month: 11
Dropping year: 2009  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
347     12  2008     -0.710303 2008-12-01
348      1  2009     -0.275124 2009-01-01
349      2  2009      0.213084 2009-02-01
350      3  2009      0.482773 2009-03-01
351      4  2009     -0.651857 2009-04-01
352      5  2009     -1.028210 2009-05-01
353      6  2009     -0.582289 2009-06-01
354      7  2009      1.067286 2009-07-01
355      8  2009     -0.365984 2009-08-01
There are enough months in the past
Target period: 12-2008 to 08-2009
Target period includes two years

Year: 2009 - End-Month of observation: 9
Forecast Year: 2009 -  Forecast Month: 12
Dropping year: 2009  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
348      1  2009     -0.275124 2009-01-01
349      2  2009      0.213084 2009-02-01
350      3  2009      0.482773 2009-03-01
351      4  2009     -0.651857 2009-04-01
352      5  2009     -1.028210 2009-05-01
353      6  2009     -0.582289 2009-06-01
354      7  2009      1.067286 2009-07-01
355      8  2009     -0.365984 2009-08-01
356      9  2009     -0.336547 2009-09-01
There are enough months in the past
Target period: 01-2009 to 09-2009
Target period includes only one year

Year: 2009 - End-Month of observation: 10
Forecast Year: 2010 -  Forecast Month: 1
Dropping year: 2009  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
349      2  2009      0.213084 2009-02-01
350      3  2009      0.482773 2009-03-01
351      4  2009     -0.651857 2009-04-01
352      5  2009     -1.028210 2009-05-01
353      6  2009     -0.582289 2009-06-01
354      7  2009      1.067286 2009-07-01
355      8  2009     -0.365984 2009-08-01
356      9  2009     -0.336547 2009-09-01
357     10  2009      1.371299 2009-10-01
There are enough months in the past
Target period: 02-2009 to 10-2009
Target period includes only one year

Year: 2009 - End-Month of observation: 11
Forecast Year: 2010 -  Forecast Month: 2
Dropping year: 2009  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
350      3  2009      0.482773 2009-03-01
351      4  2009     -0.651857 2009-04-01
352      5  2009     -1.028210 2009-05-01
353      6  2009     -0.582289 2009-06-01
354      7  2009      1.067286 2009-07-01
355      8  2009     -0.365984 2009-08-01
356      9  2009     -0.336547 2009-09-01
357     10  2009      1.371299 2009-10-01
358     11  2009      1.296561 2009-11-01
There are enough months in the past
Target period: 03-2009 to 11-2009
Target period includes only one year

Year: 2009 - End-Month of observation: 12
Forecast Year: 2010 -  Forecast Month: 3
Dropping year: 2009  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
351      4  2009     -0.651857 2009-04-01
352      5  2009     -1.028210 2009-05-01
353      6  2009     -0.582289 2009-06-01
354      7  2009      1.067286 2009-07-01
355      8  2009     -0.365984 2009-08-01
356      9  2009     -0.336547 2009-09-01
357     10  2009      1.371299 2009-10-01
358     11  2009      1.296561 2009-11-01
359     12  2009      0.747505 2009-12-01
There are enough months in the past
Target period: 04-2009 to 12-2009
Target period includes only one year

Year: 2010 - End-Month of observation: 1
Forecast Year: 2010 -  Forecast Month: 4
Dropping year: 2010  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
352      5  2009     -1.028210 2009-05-01
353      6  2009     -0.582289 2009-06-01
354      7  2009      1.067286 2009-07-01
355      8  2009     -0.365984 2009-08-01
356      9  2009     -0.336547 2009-09-01
357     10  2009      1.371299 2009-10-01
358     11  2009      1.296561 2009-11-01
359     12  2009      0.747505 2009-12-01
360      1  2010      1.082403 2010-01-01
There are enough months in the past
Target period: 05-2009 to 01-2010
Target period includes two years

Year: 2010 - End-Month of observation: 2
Forecast Year: 2010 -  Forecast Month: 5
Dropping year: 2010  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
353      6  2009     -0.582289 2009-06-01
354      7  2009      1.067286 2009-07-01
355      8  2009     -0.365984 2009-08-01
356      9  2009     -0.336547 2009-09-01
357     10  2009      1.371299 2009-10-01
358     11  2009      1.296561 2009-11-01
359     12  2009      0.747505 2009-12-01
360      1  2010      1.082403 2010-01-01
361      2  2010      2.828374 2010-02-01
There are enough months in the past
Target period: 06-2009 to 02-2010
Target period includes two years

Year: 2010 - End-Month of observation: 3
Forecast Year: 2010 -  Forecast Month: 6
Dropping year: 2010  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
354      7  2009      1.067286 2009-07-01
355      8  2009     -0.365984 2009-08-01
356      9  2009     -0.336547 2009-09-01
357     10  2009      1.371299 2009-10-01
358     11  2009      1.296561 2009-11-01
359     12  2009      0.747505 2009-12-01
360      1  2010      1.082403 2010-01-01
361      2  2010      2.828374 2010-02-01
362      3  2010      0.549333 2010-03-01
There are enough months in the past
Target period: 07-2009 to 03-2010
Target period includes two years

Year: 2010 - End-Month of observation: 4
Forecast Year: 2010 -  Forecast Month: 7
Dropping year: 2010  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
355      8  2009     -0.365984 2009-08-01
356      9  2009     -0.336547 2009-09-01
357     10  2009      1.371299 2009-10-01
358     11  2009      1.296561 2009-11-01
359     12  2009      0.747505 2009-12-01
360      1  2010      1.082403 2010-01-01
361      2  2010      2.828374 2010-02-01
362      3  2010      0.549333 2010-03-01
363      4  2010      0.446257 2010-04-01
There are enough months in the past
Target period: 08-2009 to 04-2010
Target period includes two years

Year: 2010 - End-Month of observation: 5
Forecast Year: 2010 -  Forecast Month: 8
Dropping year: 2010  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
356      9  2009     -0.336547 2009-09-01
357     10  2009      1.371299 2009-10-01
358     11  2009      1.296561 2009-11-01
359     12  2009      0.747505 2009-12-01
360      1  2010      1.082403 2010-01-01
361      2  2010      2.828374 2010-02-01
362      3  2010      0.549333 2010-03-01
363      4  2010      0.446257 2010-04-01
364      5  2010     -0.305526 2010-05-01
There are enough months in the past
Target period: 09-2009 to 05-2010
Target period includes two years

Year: 2010 - End-Month of observation: 6
Forecast Year: 2010 -  Forecast Month: 9
Dropping year: 2010  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
357     10  2009      1.371299 2009-10-01
358     11  2009      1.296561 2009-11-01
359     12  2009      0.747505 2009-12-01
360      1  2010      1.082403 2010-01-01
361      2  2010      2.828374 2010-02-01
362      3  2010      0.549333 2010-03-01
363      4  2010      0.446257 2010-04-01
364      5  2010     -0.305526 2010-05-01
365      6  2010      0.612672 2010-06-01
There are enough months in the past
Target period: 10-2009 to 06-2010
Target period includes two years

Year: 2010 - End-Month of observation: 7
Forecast Year: 2010 -  Forecast Month: 10
Dropping year: 2010  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
358     11  2009      1.296561 2009-11-01
359     12  2009      0.747505 2009-12-01
360      1  2010      1.082403 2010-01-01
361      2  2010      2.828374 2010-02-01
362      3  2010      0.549333 2010-03-01
363      4  2010      0.446257 2010-04-01
364      5  2010     -0.305526 2010-05-01
365      6  2010      0.612672 2010-06-01
366      7  2010      1.057527 2010-07-01
There are enough months in the past
Target period: 11-2009 to 07-2010
Target period includes two years

Year: 2010 - End-Month of observation: 8
Forecast Year: 2010 -  Forecast Month: 11
Dropping year: 2010  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
359     12  2009      0.747505 2009-12-01
360      1  2010      1.082403 2010-01-01
361      2  2010      2.828374 2010-02-01
362      3  2010      0.549333 2010-03-01
363      4  2010      0.446257 2010-04-01
364      5  2010     -0.305526 2010-05-01
365      6  2010      0.612672 2010-06-01
366      7  2010      1.057527 2010-07-01
367      8  2010      0.993314 2010-08-01
There are enough months in the past
Target period: 12-2009 to 08-2010
Target period includes two years

Year: 2010 - End-Month of observation: 9
Forecast Year: 2010 -  Forecast Month: 12
Dropping year: 2010  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
360      1  2010      1.082403 2010-01-01
361      2  2010      2.828374 2010-02-01
362      3  2010      0.549333 2010-03-01
363      4  2010      0.446257 2010-04-01
364      5  2010     -0.305526 2010-05-01
365      6  2010      0.612672 2010-06-01
366      7  2010      1.057527 2010-07-01
367      8  2010      0.993314 2010-08-01
368      9  2010      1.746241 2010-09-01
There are enough months in the past
Target period: 01-2010 to 09-2010
Target period includes only one year

Year: 2010 - End-Month of observation: 10
Forecast Year: 2011 -  Forecast Month: 1
Dropping year: 2010  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
361      2  2010      2.828374 2010-02-01
362      3  2010      0.549333 2010-03-01
363      4  2010      0.446257 2010-04-01
364      5  2010     -0.305526 2010-05-01
365      6  2010      0.612672 2010-06-01
366      7  2010      1.057527 2010-07-01
367      8  2010      0.993314 2010-08-01
368      9  2010      1.746241 2010-09-01
369     10  2010     -0.691464 2010-10-01
There are enough months in the past
Target period: 02-2010 to 10-2010
Target period includes only one year

Year: 2010 - End-Month of observation: 11
Forecast Year: 2011 -  Forecast Month: 2
Dropping year: 2010  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
362      3  2010      0.549333 2010-03-01
363      4  2010      0.446257 2010-04-01
364      5  2010     -0.305526 2010-05-01
365      6  2010      0.612672 2010-06-01
366      7  2010      1.057527 2010-07-01
367      8  2010      0.993314 2010-08-01
368      9  2010      1.746241 2010-09-01
369     10  2010     -0.691464 2010-10-01
370     11  2010     -0.749862 2010-11-01
There are enough months in the past
Target period: 03-2010 to 11-2010
Target period includes only one year

Year: 2010 - End-Month of observation: 12
Forecast Year: 2011 -  Forecast Month: 3
Dropping year: 2010  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
363      4  2010      0.446257 2010-04-01
364      5  2010     -0.305526 2010-05-01
365      6  2010      0.612672 2010-06-01
366      7  2010      1.057527 2010-07-01
367      8  2010      0.993314 2010-08-01
368      9  2010      1.746241 2010-09-01
369     10  2010     -0.691464 2010-10-01
370     11  2010     -0.749862 2010-11-01
371     12  2010     -0.606681 2010-12-01
There are enough months in the past
Target period: 04-2010 to 12-2010
Target period includes only one year

Year: 2011 - End-Month of observation: 1
Forecast Year: 2011 -  Forecast Month: 4
Dropping year: 2011  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
364      5  2010     -0.305526 2010-05-01
365      6  2010      0.612672 2010-06-01
366      7  2010      1.057527 2010-07-01
367      8  2010      0.993314 2010-08-01
368      9  2010      1.746241 2010-09-01
369     10  2010     -0.691464 2010-10-01
370     11  2010     -0.749862 2010-11-01
371     12  2010     -0.606681 2010-12-01
372      1  2011     -0.171486 2011-01-01
There are enough months in the past
Target period: 05-2010 to 01-2011
Target period includes two years

Year: 2011 - End-Month of observation: 2
Forecast Year: 2011 -  Forecast Month: 5
Dropping year: 2011  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
365      6  2010      0.612672 2010-06-01
366      7  2010      1.057527 2010-07-01
367      8  2010      0.993314 2010-08-01
368      9  2010      1.746241 2010-09-01
369     10  2010     -0.691464 2010-10-01
370     11  2010     -0.749862 2010-11-01
371     12  2010     -0.606681 2010-12-01
372      1  2011     -0.171486 2011-01-01
373      2  2011     -0.399055 2011-02-01
There are enough months in the past
Target period: 06-2010 to 02-2011
Target period includes two years

Year: 2011 - End-Month of observation: 3
Forecast Year: 2011 -  Forecast Month: 6
Dropping year: 2011  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
366      7  2010      1.057527 2010-07-01
367      8  2010      0.993314 2010-08-01
368      9  2010      1.746241 2010-09-01
369     10  2010     -0.691464 2010-10-01
370     11  2010     -0.749862 2010-11-01
371     12  2010     -0.606681 2010-12-01
372      1  2011     -0.171486 2011-01-01
373      2  2011     -0.399055 2011-02-01
374      3  2011     -0.536844 2011-03-01
There are enough months in the past
Target period: 07-2010 to 03-2011
Target period includes two years

Year: 2011 - End-Month of observation: 4
Forecast Year: 2011 -  Forecast Month: 7
Dropping year: 2011  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
367      8  2010      0.993314 2010-08-01
368      9  2010      1.746241 2010-09-01
369     10  2010     -0.691464 2010-10-01
370     11  2010     -0.749862 2010-11-01
371     12  2010     -0.606681 2010-12-01
372      1  2011     -0.171486 2011-01-01
373      2  2011     -0.399055 2011-02-01
374      3  2011     -0.536844 2011-03-01
375      4  2011     -0.679586 2011-04-01
There are enough months in the past
Target period: 08-2010 to 04-2011
Target period includes two years

Year: 2011 - End-Month of observation: 5
Forecast Year: 2011 -  Forecast Month: 8
Dropping year: 2011  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
368      9  2010      1.746241 2010-09-01
369     10  2010     -0.691464 2010-10-01
370     11  2010     -0.749862 2010-11-01
371     12  2010     -0.606681 2010-12-01
372      1  2011     -0.171486 2011-01-01
373      2  2011     -0.399055 2011-02-01
374      3  2011     -0.536844 2011-03-01
375      4  2011     -0.679586 2011-04-01
376      5  2011     -0.990349 2011-05-01
There are enough months in the past
Target period: 09-2010 to 05-2011
Target period includes two years

Year: 2011 - End-Month of observation: 6
Forecast Year: 2011 -  Forecast Month: 9
Dropping year: 2011  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
369     10  2010     -0.691464 2010-10-01
370     11  2010     -0.749862 2010-11-01
371     12  2010     -0.606681 2010-12-01
372      1  2011     -0.171486 2011-01-01
373      2  2011     -0.399055 2011-02-01
374      3  2011     -0.536844 2011-03-01
375      4  2011     -0.679586 2011-04-01
376      5  2011     -0.990349 2011-05-01
377      6  2011           NaN 2011-06-01
There are enough months in the past
Target period: 10-2010 to 06-2011
Target period includes two years

Year: 2011 - End-Month of observation: 7
Forecast Year: 2011 -  Forecast Month: 10
Dropping year: 2011  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
370     11  2010     -0.749862 2010-11-01
371     12  2010     -0.606681 2010-12-01
372      1  2011     -0.171486 2011-01-01
373      2  2011     -0.399055 2011-02-01
374      3  2011     -0.536844 2011-03-01
375      4  2011     -0.679586 2011-04-01
376      5  2011     -0.990349 2011-05-01
377      6  2011           NaN 2011-06-01
378      7  2011           NaN 2011-07-01
There are enough months in the past
Target period: 11-2010 to 07-2011
Target period includes two years

Year: 2011 - End-Month of observation: 8
Forecast Year: 2011 -  Forecast Month: 11
Dropping year: 2011  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
371     12  2010     -0.606681 2010-12-01
372      1  2011     -0.171486 2011-01-01
373      2  2011     -0.399055 2011-02-01
374      3  2011     -0.536844 2011-03-01
375      4  2011     -0.679586 2011-04-01
376      5  2011     -0.990349 2011-05-01
377      6  2011           NaN 2011-06-01
378      7  2011           NaN 2011-07-01
379      8  2011           NaN 2011-08-01
There are enough months in the past
Target period: 12-2010 to 08-2011
Target period includes two years

Year: 2011 - End-Month of observation: 9
Forecast Year: 2011 -  Forecast Month: 12
Dropping year: 2011  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
372      1  2011     -0.171486 2011-01-01
373      2  2011     -0.399055 2011-02-01
374      3  2011     -0.536844 2011-03-01
375      4  2011     -0.679586 2011-04-01
376      5  2011     -0.990349 2011-05-01
377      6  2011           NaN 2011-06-01
378      7  2011           NaN 2011-07-01
379      8  2011           NaN 2011-08-01
380      9  2011           NaN 2011-09-01
There are enough months in the past
Target period: 01-2011 to 09-2011
Target period includes only one year

Year: 2011 - End-Month of observation: 10
Forecast Year: 2012 -  Forecast Month: 1
Dropping year: 2011  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
373      2  2011     -0.399055 2011-02-01
374      3  2011     -0.536844 2011-03-01
375      4  2011     -0.679586 2011-04-01
376      5  2011     -0.990349 2011-05-01
377      6  2011           NaN 2011-06-01
378      7  2011           NaN 2011-07-01
379      8  2011           NaN 2011-08-01
380      9  2011           NaN 2011-09-01
381     10  2011           NaN 2011-10-01
There are enough months in the past
Target period: 02-2011 to 10-2011
Target period includes only one year

Year: 2011 - End-Month of observation: 11
Forecast Year: 2012 -  Forecast Month: 2
Dropping year: 2011  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
374      3  2011     -0.536844 2011-03-01
375      4  2011     -0.679586 2011-04-01
376      5  2011     -0.990349 2011-05-01
377      6  2011           NaN 2011-06-01
378      7  2011           NaN 2011-07-01
379      8  2011           NaN 2011-08-01
380      9  2011           NaN 2011-09-01
381     10  2011           NaN 2011-10-01
382     11  2011           NaN 2011-11-01
There are enough months in the past
Target period: 03-2011 to 11-2011
Target period includes only one year

Year: 2011 - End-Month of observation: 12
Forecast Year: 2012 -  Forecast Month: 3
Dropping year: 2011  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
375      4  2011     -0.679586 2011-04-01
376      5  2011     -0.990349 2011-05-01
377      6  2011           NaN 2011-06-01
378      7  2011           NaN 2011-07-01
379      8  2011           NaN 2011-08-01
380      9  2011           NaN 2011-09-01
381     10  2011           NaN 2011-10-01
382     11  2011           NaN 2011-11-01
383     12  2011           NaN 2011-12-01
There are enough months in the past
Target period: 04-2011 to 12-2011
Target period includes only one year

Year: 2012 - End-Month of observation: 1
Forecast Year: 2012 -  Forecast Month: 4
Dropping year: 2012  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
376      5  2011     -0.990349 2011-05-01
377      6  2011           NaN 2011-06-01
378      7  2011           NaN 2011-07-01
379      8  2011           NaN 2011-08-01
380      9  2011           NaN 2011-09-01
381     10  2011           NaN 2011-10-01
382     11  2011           NaN 2011-11-01
383     12  2011           NaN 2011-12-01
384      1  2012           NaN 2012-01-01
There are enough months in the past
Target period: 05-2011 to 01-2012
Target period includes two years

Year: 2012 - End-Month of observation: 2
Forecast Year: 2012 -  Forecast Month: 5
Dropping year: 2012  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
377      6  2011           NaN 2011-06-01
378      7  2011           NaN 2011-07-01
379      8  2011           NaN 2011-08-01
380      9  2011           NaN 2011-09-01
381     10  2011           NaN 2011-10-01
382     11  2011           NaN 2011-11-01
383     12  2011           NaN 2011-12-01
384      1  2012           NaN 2012-01-01
385      2  2012           NaN 2012-02-01
There are enough months in the past
Target period: 06-2011 to 02-2012
Target period includes two years

Year: 2012 - End-Month of observation: 3
Forecast Year: 2012 -  Forecast Month: 6
Dropping year: 2012  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
378      7  2011           NaN 2011-07-01
379      8  2011           NaN 2011-08-01
380      9  2011           NaN 2011-09-01
381     10  2011           NaN 2011-10-01
382     11  2011           NaN 2011-11-01
383     12  2011           NaN 2011-12-01
384      1  2012           NaN 2012-01-01
385      2  2012           NaN 2012-02-01
386      3  2012           NaN 2012-03-01
There are enough months in the past
Target period: 07-2011 to 03-2012
Target period includes two years

Year: 2012 - End-Month of observation: 4
Forecast Year: 2012 -  Forecast Month: 7
Dropping year: 2012  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
379      8  2011           NaN 2011-08-01
380      9  2011           NaN 2011-09-01
381     10  2011           NaN 2011-10-01
382     11  2011           NaN 2011-11-01
383     12  2011           NaN 2011-12-01
384      1  2012           NaN 2012-01-01
385      2  2012           NaN 2012-02-01
386      3  2012           NaN 2012-03-01
387      4  2012     -0.586552 2012-04-01
There are enough months in the past
Target period: 08-2011 to 04-2012
Target period includes two years

Year: 2012 - End-Month of observation: 5
Forecast Year: 2012 -  Forecast Month: 8
Dropping year: 2012  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
380      9  2011           NaN 2011-09-01
381     10  2011           NaN 2011-10-01
382     11  2011           NaN 2011-11-01
383     12  2011           NaN 2011-12-01
384      1  2012           NaN 2012-01-01
385      2  2012           NaN 2012-02-01
386      3  2012           NaN 2012-03-01
387      4  2012     -0.586552 2012-04-01
388      5  2012     -1.220725 2012-05-01
There are enough months in the past
Target period: 09-2011 to 05-2012
Target period includes two years

Year: 2012 - End-Month of observation: 6
Forecast Year: 2012 -  Forecast Month: 9
Dropping year: 2012  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
381     10  2011           NaN 2011-10-01
382     11  2011           NaN 2011-11-01
383     12  2011           NaN 2011-12-01
384      1  2012           NaN 2012-01-01
385      2  2012           NaN 2012-02-01
386      3  2012           NaN 2012-03-01
387      4  2012     -0.586552 2012-04-01
388      5  2012     -1.220725 2012-05-01
389      6  2012     -1.206965 2012-06-01
There are enough months in the past
Target period: 10-2011 to 06-2012
Target period includes two years

Year: 2012 - End-Month of observation: 7
Forecast Year: 2012 -  Forecast Month: 10
Dropping year: 2012  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
382     11  2011           NaN 2011-11-01
383     12  2011           NaN 2011-12-01
384      1  2012           NaN 2012-01-01
385      2  2012           NaN 2012-02-01
386      3  2012           NaN 2012-03-01
387      4  2012     -0.586552 2012-04-01
388      5  2012     -1.220725 2012-05-01
389      6  2012     -1.206965 2012-06-01
390      7  2012     -0.782419 2012-07-01
There are enough months in the past
Target period: 11-2011 to 07-2012
Target period includes two years

Year: 2012 - End-Month of observation: 8
Forecast Year: 2012 -  Forecast Month: 11
Dropping year: 2012  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
383     12  2011           NaN 2011-12-01
384      1  2012           NaN 2012-01-01
385      2  2012           NaN 2012-02-01
386      3  2012           NaN 2012-03-01
387      4  2012     -0.586552 2012-04-01
388      5  2012     -1.220725 2012-05-01
389      6  2012     -1.206965 2012-06-01
390      7  2012     -0.782419 2012-07-01
391      8  2012           NaN 2012-08-01
There are enough months in the past
Target period: 12-2011 to 08-2012
Target period includes two years

Year: 2012 - End-Month of observation: 9
Forecast Year: 2012 -  Forecast Month: 12
Dropping year: 2012  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
384      1  2012           NaN 2012-01-01
385      2  2012           NaN 2012-02-01
386      3  2012           NaN 2012-03-01
387      4  2012     -0.586552 2012-04-01
388      5  2012     -1.220725 2012-05-01
389      6  2012     -1.206965 2012-06-01
390      7  2012     -0.782419 2012-07-01
391      8  2012           NaN 2012-08-01
392      9  2012           NaN 2012-09-01
There are enough months in the past
Target period: 01-2012 to 09-2012
Target period includes only one year

Year: 2012 - End-Month of observation: 10
Forecast Year: 2013 -  Forecast Month: 1
Dropping year: 2012  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
385      2  2012           NaN 2012-02-01
386      3  2012           NaN 2012-03-01
387      4  2012     -0.586552 2012-04-01
388      5  2012     -1.220725 2012-05-01
389      6  2012     -1.206965 2012-06-01
390      7  2012     -0.782419 2012-07-01
391      8  2012           NaN 2012-08-01
392      9  2012           NaN 2012-09-01
393     10  2012      1.350655 2012-10-01
There are enough months in the past
Target period: 02-2012 to 10-2012
Target period includes only one year

Year: 2012 - End-Month of observation: 11
Forecast Year: 2013 -  Forecast Month: 2
Dropping year: 2012  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
386      3  2012           NaN 2012-03-01
387      4  2012     -0.586552 2012-04-01
388      5  2012     -1.220725 2012-05-01
389      6  2012     -1.206965 2012-06-01
390      7  2012     -0.782419 2012-07-01
391      8  2012           NaN 2012-08-01
392      9  2012           NaN 2012-09-01
393     10  2012      1.350655 2012-10-01
394     11  2012      1.056803 2012-11-01
There are enough months in the past
Target period: 03-2012 to 11-2012
Target period includes only one year

Year: 2012 - End-Month of observation: 12
Forecast Year: 2013 -  Forecast Month: 3
Dropping year: 2012  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
387      4  2012     -0.586552 2012-04-01
388      5  2012     -1.220725 2012-05-01
389      6  2012     -1.206965 2012-06-01
390      7  2012     -0.782419 2012-07-01
391      8  2012           NaN 2012-08-01
392      9  2012           NaN 2012-09-01
393     10  2012      1.350655 2012-10-01
394     11  2012      1.056803 2012-11-01
395     12  2012      2.099620 2012-12-01
There are enough months in the past
Target period: 04-2012 to 12-2012
Target period includes only one year

Year: 2013 - End-Month of observation: 1
Forecast Year: 2013 -  Forecast Month: 4
Dropping year: 2013  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
388      5  2012     -1.220725 2012-05-01
389      6  2012     -1.206965 2012-06-01
390      7  2012     -0.782419 2012-07-01
391      8  2012           NaN 2012-08-01
392      9  2012           NaN 2012-09-01
393     10  2012      1.350655 2012-10-01
394     11  2012      1.056803 2012-11-01
395     12  2012      2.099620 2012-12-01
396      1  2013      0.908379 2013-01-01
There are enough months in the past
Target period: 05-2012 to 01-2013
Target period includes two years

Year: 2013 - End-Month of observation: 2
Forecast Year: 2013 -  Forecast Month: 5
Dropping year: 2013  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
389      6  2012     -1.206965 2012-06-01
390      7  2012     -0.782419 2012-07-01
391      8  2012           NaN 2012-08-01
392      9  2012           NaN 2012-09-01
393     10  2012      1.350655 2012-10-01
394     11  2012      1.056803 2012-11-01
395     12  2012      2.099620 2012-12-01
396      1  2013      0.908379 2013-01-01
397      2  2013     -0.278387 2013-02-01
There are enough months in the past
Target period: 06-2012 to 02-2013
Target period includes two years

Year: 2013 - End-Month of observation: 3
Forecast Year: 2013 -  Forecast Month: 6
Dropping year: 2013  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
390      7  2012     -0.782419 2012-07-01
391      8  2012           NaN 2012-08-01
392      9  2012           NaN 2012-09-01
393     10  2012      1.350655 2012-10-01
394     11  2012      1.056803 2012-11-01
395     12  2012      2.099620 2012-12-01
396      1  2013      0.908379 2013-01-01
397      2  2013     -0.278387 2013-02-01
398      3  2013           NaN 2013-03-01
There are enough months in the past
Target period: 07-2012 to 03-2013
Target period includes two years

Year: 2013 - End-Month of observation: 4
Forecast Year: 2013 -  Forecast Month: 7
Dropping year: 2013  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
391      8  2012           NaN 2012-08-01
392      9  2012           NaN 2012-09-01
393     10  2012      1.350655 2012-10-01
394     11  2012      1.056803 2012-11-01
395     12  2012      2.099620 2012-12-01
396      1  2013      0.908379 2013-01-01
397      2  2013     -0.278387 2013-02-01
398      3  2013           NaN 2013-03-01
399      4  2013           NaN 2013-04-01
There are enough months in the past
Target period: 08-2012 to 04-2013
Target period includes two years

Year: 2013 - End-Month of observation: 5
Forecast Year: 2013 -  Forecast Month: 8
Dropping year: 2013  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
392      9  2012           NaN 2012-09-01
393     10  2012      1.350655 2012-10-01
394     11  2012      1.056803 2012-11-01
395     12  2012      2.099620 2012-12-01
396      1  2013      0.908379 2013-01-01
397      2  2013     -0.278387 2013-02-01
398      3  2013           NaN 2013-03-01
399      4  2013           NaN 2013-04-01
400      5  2013           NaN 2013-05-01
There are enough months in the past
Target period: 09-2012 to 05-2013
Target period includes two years

Year: 2013 - End-Month of observation: 6
Forecast Year: 2013 -  Forecast Month: 9
Dropping year: 2013  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
393     10  2012      1.350655 2012-10-01
394     11  2012      1.056803 2012-11-01
395     12  2012      2.099620 2012-12-01
396      1  2013      0.908379 2013-01-01
397      2  2013     -0.278387 2013-02-01
398      3  2013           NaN 2013-03-01
399      4  2013           NaN 2013-04-01
400      5  2013           NaN 2013-05-01
401      6  2013     -1.173551 2013-06-01
There are enough months in the past
Target period: 10-2012 to 06-2013
Target period includes two years

Year: 2013 - End-Month of observation: 7
Forecast Year: 2013 -  Forecast Month: 10
Dropping year: 2013  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
394     11  2012      1.056803 2012-11-01
395     12  2012      2.099620 2012-12-01
396      1  2013      0.908379 2013-01-01
397      2  2013     -0.278387 2013-02-01
398      3  2013           NaN 2013-03-01
399      4  2013           NaN 2013-04-01
400      5  2013           NaN 2013-05-01
401      6  2013     -1.173551 2013-06-01
402      7  2013           NaN 2013-07-01
There are enough months in the past
Target period: 11-2012 to 07-2013
Target period includes two years

Year: 2013 - End-Month of observation: 8
Forecast Year: 2013 -  Forecast Month: 11
Dropping year: 2013  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
395     12  2012      2.099620 2012-12-01
396      1  2013      0.908379 2013-01-01
397      2  2013     -0.278387 2013-02-01
398      3  2013           NaN 2013-03-01
399      4  2013           NaN 2013-04-01
400      5  2013           NaN 2013-05-01
401      6  2013     -1.173551 2013-06-01
402      7  2013           NaN 2013-07-01
403      8  2013           NaN 2013-08-01
There are enough months in the past
Target period: 12-2012 to 08-2013
Target period includes two years

Year: 2013 - End-Month of observation: 9
Forecast Year: 2013 -  Forecast Month: 12
Dropping year: 2013  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
396      1  2013      0.908379 2013-01-01
397      2  2013     -0.278387 2013-02-01
398      3  2013           NaN 2013-03-01
399      4  2013           NaN 2013-04-01
400      5  2013           NaN 2013-05-01
401      6  2013     -1.173551 2013-06-01
402      7  2013           NaN 2013-07-01
403      8  2013           NaN 2013-08-01
404      9  2013           NaN 2013-09-01
There are enough months in the past
Target period: 01-2013 to 09-2013
Target period includes only one year

Year: 2013 - End-Month of observation: 10
Forecast Year: 2014 -  Forecast Month: 1
Dropping year: 2013  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
397      2  2013     -0.278387 2013-02-01
398      3  2013           NaN 2013-03-01
399      4  2013           NaN 2013-04-01
400      5  2013           NaN 2013-05-01
401      6  2013     -1.173551 2013-06-01
402      7  2013           NaN 2013-07-01
403      8  2013           NaN 2013-08-01
404      9  2013           NaN 2013-09-01
405     10  2013     -0.529258 2013-10-01
There are enough months in the past
Target period: 02-2013 to 10-2013
Target period includes only one year

Year: 2013 - End-Month of observation: 11
Forecast Year: 2014 -  Forecast Month: 2
Dropping year: 2013  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
398      3  2013           NaN 2013-03-01
399      4  2013           NaN 2013-04-01
400      5  2013           NaN 2013-05-01
401      6  2013     -1.173551 2013-06-01
402      7  2013           NaN 2013-07-01
403      8  2013           NaN 2013-08-01
404      9  2013           NaN 2013-09-01
405     10  2013     -0.529258 2013-10-01
406     11  2013           NaN 2013-11-01
There are enough months in the past
Target period: 03-2013 to 11-2013
Target period includes only one year

Year: 2013 - End-Month of observation: 12
Forecast Year: 2014 -  Forecast Month: 3
Dropping year: 2013  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
399      4  2013           NaN 2013-04-01
400      5  2013           NaN 2013-05-01
401      6  2013     -1.173551 2013-06-01
402      7  2013           NaN 2013-07-01
403      8  2013           NaN 2013-08-01
404      9  2013           NaN 2013-09-01
405     10  2013     -0.529258 2013-10-01
406     11  2013           NaN 2013-11-01
407     12  2013           NaN 2013-12-01
There are enough months in the past
Target period: 04-2013 to 12-2013
Target period includes only one year

Year: 2014 - End-Month of observation: 1
Forecast Year: 2014 -  Forecast Month: 4
Dropping year: 2014  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
400      5  2013           NaN 2013-05-01
401      6  2013     -1.173551 2013-06-01
402      7  2013           NaN 2013-07-01
403      8  2013           NaN 2013-08-01
404      9  2013           NaN 2013-09-01
405     10  2013     -0.529258 2013-10-01
406     11  2013           NaN 2013-11-01
407     12  2013           NaN 2013-12-01
408      1  2014           NaN 2014-01-01
There are enough months in the past
Target period: 05-2013 to 01-2014
Target period includes two years

Year: 2014 - End-Month of observation: 2
Forecast Year: 2014 -  Forecast Month: 5
Dropping year: 2014  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
401      6  2013     -1.173551 2013-06-01
402      7  2013           NaN 2013-07-01
403      8  2013           NaN 2013-08-01
404      9  2013           NaN 2013-09-01
405     10  2013     -0.529258 2013-10-01
406     11  2013           NaN 2013-11-01
407     12  2013           NaN 2013-12-01
408      1  2014           NaN 2014-01-01
409      2  2014           NaN 2014-02-01
There are enough months in the past
Target period: 06-2013 to 02-2014
Target period includes two years

Year: 2014 - End-Month of observation: 3
Forecast Year: 2014 -  Forecast Month: 6
Dropping year: 2014  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
402      7  2013           NaN 2013-07-01
403      8  2013           NaN 2013-08-01
404      9  2013           NaN 2013-09-01
405     10  2013     -0.529258 2013-10-01
406     11  2013           NaN 2013-11-01
407     12  2013           NaN 2013-12-01
408      1  2014           NaN 2014-01-01
409      2  2014           NaN 2014-02-01
410      3  2014           NaN 2014-03-01
There are enough months in the past
Target period: 07-2013 to 03-2014
Target period includes two years

Year: 2014 - End-Month of observation: 4
Forecast Year: 2014 -  Forecast Month: 7
Dropping year: 2014  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
403      8  2013           NaN 2013-08-01
404      9  2013           NaN 2013-09-01
405     10  2013     -0.529258 2013-10-01
406     11  2013           NaN 2013-11-01
407     12  2013           NaN 2013-12-01
408      1  2014           NaN 2014-01-01
409      2  2014           NaN 2014-02-01
410      3  2014           NaN 2014-03-01
411      4  2014           NaN 2014-04-01
There are enough months in the past
Target period: 08-2013 to 04-2014
Target period includes two years

Year: 2014 - End-Month of observation: 5
Forecast Year: 2014 -  Forecast Month: 8
Dropping year: 2014  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
404      9  2013           NaN 2013-09-01
405     10  2013     -0.529258 2013-10-01
406     11  2013           NaN 2013-11-01
407     12  2013           NaN 2013-12-01
408      1  2014           NaN 2014-01-01
409      2  2014           NaN 2014-02-01
410      3  2014           NaN 2014-03-01
411      4  2014           NaN 2014-04-01
412      5  2014           NaN 2014-05-01
There are enough months in the past
Target period: 09-2013 to 05-2014
Target period includes two years

Year: 2014 - End-Month of observation: 6
Forecast Year: 2014 -  Forecast Month: 9
Dropping year: 2014  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
405     10  2013     -0.529258 2013-10-01
406     11  2013           NaN 2013-11-01
407     12  2013           NaN 2013-12-01
408      1  2014           NaN 2014-01-01
409      2  2014           NaN 2014-02-01
410      3  2014           NaN 2014-03-01
411      4  2014           NaN 2014-04-01
412      5  2014           NaN 2014-05-01
413      6  2014           NaN 2014-06-01
There are enough months in the past
Target period: 10-2013 to 06-2014
Target period includes two years

Year: 2014 - End-Month of observation: 7
Forecast Year: 2014 -  Forecast Month: 10
Dropping year: 2014  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
406     11  2013           NaN 2013-11-01
407     12  2013           NaN 2013-12-01
408      1  2014           NaN 2014-01-01
409      2  2014           NaN 2014-02-01
410      3  2014           NaN 2014-03-01
411      4  2014           NaN 2014-04-01
412      5  2014           NaN 2014-05-01
413      6  2014           NaN 2014-06-01
414      7  2014           NaN 2014-07-01
There are enough months in the past
Target period: 11-2013 to 07-2014
Target period includes two years

Year: 2014 - End-Month of observation: 8
Forecast Year: 2014 -  Forecast Month: 11
Dropping year: 2014  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
407     12  2013           NaN 2013-12-01
408      1  2014           NaN 2014-01-01
409      2  2014           NaN 2014-02-01
410      3  2014           NaN 2014-03-01
411      4  2014           NaN 2014-04-01
412      5  2014           NaN 2014-05-01
413      6  2014           NaN 2014-06-01
414      7  2014           NaN 2014-07-01
415      8  2014           NaN 2014-08-01
There are enough months in the past
Target period: 12-2013 to 08-2014
Target period includes two years

Year: 2014 - End-Month of observation: 9
Forecast Year: 2014 -  Forecast Month: 12
Dropping year: 2014  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
408      1  2014           NaN 2014-01-01
409      2  2014           NaN 2014-02-01
410      3  2014           NaN 2014-03-01
411      4  2014           NaN 2014-04-01
412      5  2014           NaN 2014-05-01
413      6  2014           NaN 2014-06-01
414      7  2014           NaN 2014-07-01
415      8  2014           NaN 2014-08-01
416      9  2014           NaN 2014-09-01
There are enough months in the past
Target period: 01-2014 to 09-2014
Target period includes only one year

Year: 2014 - End-Month of observation: 10
Forecast Year: 2015 -  Forecast Month: 1
Dropping year: 2014  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
409      2  2014           NaN 2014-02-01
410      3  2014           NaN 2014-03-01
411      4  2014           NaN 2014-04-01
412      5  2014           NaN 2014-05-01
413      6  2014           NaN 2014-06-01
414      7  2014           NaN 2014-07-01
415      8  2014           NaN 2014-08-01
416      9  2014           NaN 2014-09-01
417     10  2014           NaN 2014-10-01
There are enough months in the past
Target period: 02-2014 to 10-2014
Target period includes only one year

Year: 2014 - End-Month of observation: 11
Forecast Year: 2015 -  Forecast Month: 2
Dropping year: 2014  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
410      3  2014           NaN 2014-03-01
411      4  2014           NaN 2014-04-01
412      5  2014           NaN 2014-05-01
413      6  2014           NaN 2014-06-01
414      7  2014           NaN 2014-07-01
415      8  2014           NaN 2014-08-01
416      9  2014           NaN 2014-09-01
417     10  2014           NaN 2014-10-01
418     11  2014      1.227963 2014-11-01
There are enough months in the past
Target period: 03-2014 to 11-2014
Target period includes only one year

Year: 2014 - End-Month of observation: 12
Forecast Year: 2015 -  Forecast Month: 3
Dropping year: 2014  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
411      4  2014           NaN 2014-04-01
412      5  2014           NaN 2014-05-01
413      6  2014           NaN 2014-06-01
414      7  2014           NaN 2014-07-01
415      8  2014           NaN 2014-08-01
416      9  2014           NaN 2014-09-01
417     10  2014           NaN 2014-10-01
418     11  2014      1.227963 2014-11-01
419     12  2014           NaN 2014-12-01
There are enough months in the past
Target period: 04-2014 to 12-2014
Target period includes only one year

Year: 2015 - End-Month of observation: 1
Forecast Year: 2015 -  Forecast Month: 4
Dropping year: 2015  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
412      5  2014           NaN 2014-05-01
413      6  2014           NaN 2014-06-01
414      7  2014           NaN 2014-07-01
415      8  2014           NaN 2014-08-01
416      9  2014           NaN 2014-09-01
417     10  2014           NaN 2014-10-01
418     11  2014      1.227963 2014-11-01
419     12  2014           NaN 2014-12-01
420      1  2015      0.204800 2015-01-01
There are enough months in the past
Target period: 05-2014 to 01-2015
Target period includes two years

Year: 2015 - End-Month of observation: 2
Forecast Year: 2015 -  Forecast Month: 5
Dropping year: 2015  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
413      6  2014           NaN 2014-06-01
414      7  2014           NaN 2014-07-01
415      8  2014           NaN 2014-08-01
416      9  2014           NaN 2014-09-01
417     10  2014           NaN 2014-10-01
418     11  2014      1.227963 2014-11-01
419     12  2014           NaN 2014-12-01
420      1  2015      0.204800 2015-01-01
421      2  2015     -0.394508 2015-02-01
There are enough months in the past
Target period: 06-2014 to 02-2015
Target period includes two years

Year: 2015 - End-Month of observation: 3
Forecast Year: 2015 -  Forecast Month: 6
Dropping year: 2015  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
414      7  2014           NaN 2014-07-01
415      8  2014           NaN 2014-08-01
416      9  2014           NaN 2014-09-01
417     10  2014           NaN 2014-10-01
418     11  2014      1.227963 2014-11-01
419     12  2014           NaN 2014-12-01
420      1  2015      0.204800 2015-01-01
421      2  2015     -0.394508 2015-02-01
422      3  2015     -0.677517 2015-03-01
There are enough months in the past
Target period: 07-2014 to 03-2015
Target period includes two years

Year: 2015 - End-Month of observation: 4
Forecast Year: 2015 -  Forecast Month: 7
Dropping year: 2015  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
415      8  2014           NaN 2014-08-01
416      9  2014           NaN 2014-09-01
417     10  2014           NaN 2014-10-01
418     11  2014      1.227963 2014-11-01
419     12  2014           NaN 2014-12-01
420      1  2015      0.204800 2015-01-01
421      2  2015     -0.394508 2015-02-01
422      3  2015     -0.677517 2015-03-01
423      4  2015           NaN 2015-04-01
There are enough months in the past
Target period: 08-2014 to 04-2015
Target period includes two years

Year: 2015 - End-Month of observation: 5
Forecast Year: 2015 -  Forecast Month: 8
Dropping year: 2015  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
416      9  2014           NaN 2014-09-01
417     10  2014           NaN 2014-10-01
418     11  2014      1.227963 2014-11-01
419     12  2014           NaN 2014-12-01
420      1  2015      0.204800 2015-01-01
421      2  2015     -0.394508 2015-02-01
422      3  2015     -0.677517 2015-03-01
423      4  2015           NaN 2015-04-01
424      5  2015     -1.283716 2015-05-01
There are enough months in the past
Target period: 09-2014 to 05-2015
Target period includes two years

Year: 2015 - End-Month of observation: 6
Forecast Year: 2015 -  Forecast Month: 9
Dropping year: 2015  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
417     10  2014           NaN 2014-10-01
418     11  2014      1.227963 2014-11-01
419     12  2014           NaN 2014-12-01
420      1  2015      0.204800 2015-01-01
421      2  2015     -0.394508 2015-02-01
422      3  2015     -0.677517 2015-03-01
423      4  2015           NaN 2015-04-01
424      5  2015     -1.283716 2015-05-01
425      6  2015     -1.814261 2015-06-01
There are enough months in the past
Target period: 10-2014 to 06-2015
Target period includes two years

Year: 2015 - End-Month of observation: 7
Forecast Year: 2015 -  Forecast Month: 10
Dropping year: 2015  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
418     11  2014      1.227963 2014-11-01
419     12  2014           NaN 2014-12-01
420      1  2015      0.204800 2015-01-01
421      2  2015     -0.394508 2015-02-01
422      3  2015     -0.677517 2015-03-01
423      4  2015           NaN 2015-04-01
424      5  2015     -1.283716 2015-05-01
425      6  2015     -1.814261 2015-06-01
426      7  2015     -2.458694 2015-07-01
There are enough months in the past
Target period: 11-2014 to 07-2015
Target period includes two years

Year: 2015 - End-Month of observation: 8
Forecast Year: 2015 -  Forecast Month: 11
Dropping year: 2015  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
419     12  2014           NaN 2014-12-01
420      1  2015      0.204800 2015-01-01
421      2  2015     -0.394508 2015-02-01
422      3  2015     -0.677517 2015-03-01
423      4  2015           NaN 2015-04-01
424      5  2015     -1.283716 2015-05-01
425      6  2015     -1.814261 2015-06-01
426      7  2015     -2.458694 2015-07-01
427      8  2015      0.983076 2015-08-01
There are enough months in the past
Target period: 12-2014 to 08-2015
Target period includes two years

Year: 2015 - End-Month of observation: 9
Forecast Year: 2015 -  Forecast Month: 12
Dropping year: 2015  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
420      1  2015      0.204800 2015-01-01
421      2  2015     -0.394508 2015-02-01
422      3  2015     -0.677517 2015-03-01
423      4  2015           NaN 2015-04-01
424      5  2015     -1.283716 2015-05-01
425      6  2015     -1.814261 2015-06-01
426      7  2015     -2.458694 2015-07-01
427      8  2015      0.983076 2015-08-01
428      9  2015     -1.124536 2015-09-01
There are enough months in the past
Target period: 01-2015 to 09-2015
Target period includes only one year

Year: 2015 - End-Month of observation: 10
Forecast Year: 2016 -  Forecast Month: 1
Dropping year: 2015  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
421      2  2015     -0.394508 2015-02-01
422      3  2015     -0.677517 2015-03-01
423      4  2015           NaN 2015-04-01
424      5  2015     -1.283716 2015-05-01
425      6  2015     -1.814261 2015-06-01
426      7  2015     -2.458694 2015-07-01
427      8  2015      0.983076 2015-08-01
428      9  2015     -1.124536 2015-09-01
429     10  2015     -0.102707 2015-10-01
There are enough months in the past
Target period: 02-2015 to 10-2015
Target period includes only one year

Year: 2015 - End-Month of observation: 11
Forecast Year: 2016 -  Forecast Month: 2
Dropping year: 2015  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
422      3  2015     -0.677517 2015-03-01
423      4  2015           NaN 2015-04-01
424      5  2015     -1.283716 2015-05-01
425      6  2015     -1.814261 2015-06-01
426      7  2015     -2.458694 2015-07-01
427      8  2015      0.983076 2015-08-01
428      9  2015     -1.124536 2015-09-01
429     10  2015     -0.102707 2015-10-01
430     11  2015     -1.188595 2015-11-01
There are enough months in the past
Target period: 03-2015 to 11-2015
Target period includes only one year

Year: 2015 - End-Month of observation: 12
Forecast Year: 2016 -  Forecast Month: 3
Dropping year: 2015  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
423      4  2015           NaN 2015-04-01
424      5  2015     -1.283716 2015-05-01
425      6  2015     -1.814261 2015-06-01
426      7  2015     -2.458694 2015-07-01
427      8  2015      0.983076 2015-08-01
428      9  2015     -1.124536 2015-09-01
429     10  2015     -0.102707 2015-10-01
430     11  2015     -1.188595 2015-11-01
431     12  2015      0.400305 2015-12-01
There are enough months in the past
Target period: 04-2015 to 12-2015
Target period includes only one year

Year: 2016 - End-Month of observation: 1
Forecast Year: 2016 -  Forecast Month: 4
Dropping year: 2016  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
424      5  2015     -1.283716 2015-05-01
425      6  2015     -1.814261 2015-06-01
426      7  2015     -2.458694 2015-07-01
427      8  2015      0.983076 2015-08-01
428      9  2015     -1.124536 2015-09-01
429     10  2015     -0.102707 2015-10-01
430     11  2015     -1.188595 2015-11-01
431     12  2015      0.400305 2015-12-01
432      1  2016      0.814189 2016-01-01
There are enough months in the past
Target period: 05-2015 to 01-2016
Target period includes two years

Year: 2016 - End-Month of observation: 2
Forecast Year: 2016 -  Forecast Month: 5
Dropping year: 2016  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
425      6  2015     -1.814261 2015-06-01
426      7  2015     -2.458694 2015-07-01
427      8  2015      0.983076 2015-08-01
428      9  2015     -1.124536 2015-09-01
429     10  2015     -0.102707 2015-10-01
430     11  2015     -1.188595 2015-11-01
431     12  2015      0.400305 2015-12-01
432      1  2016      0.814189 2016-01-01
433      2  2016     -0.887051 2016-02-01
There are enough months in the past
Target period: 06-2015 to 02-2016
Target period includes two years

Year: 2016 - End-Month of observation: 3
Forecast Year: 2016 -  Forecast Month: 6
Dropping year: 2016  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
426      7  2015     -2.458694 2015-07-01
427      8  2015      0.983076 2015-08-01
428      9  2015     -1.124536 2015-09-01
429     10  2015     -0.102707 2015-10-01
430     11  2015     -1.188595 2015-11-01
431     12  2015      0.400305 2015-12-01
432      1  2016      0.814189 2016-01-01
433      2  2016     -0.887051 2016-02-01
434      3  2016     -1.096631 2016-03-01
There are enough months in the past
Target period: 07-2015 to 03-2016
Target period includes two years

Year: 2016 - End-Month of observation: 4
Forecast Year: 2016 -  Forecast Month: 7
Dropping year: 2016  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
427      8  2015      0.983076 2015-08-01
428      9  2015     -1.124536 2015-09-01
429     10  2015     -0.102707 2015-10-01
430     11  2015     -1.188595 2015-11-01
431     12  2015      0.400305 2015-12-01
432      1  2016      0.814189 2016-01-01
433      2  2016     -0.887051 2016-02-01
434      3  2016     -1.096631 2016-03-01
435      4  2016      2.118149 2016-04-01
There are enough months in the past
Target period: 08-2015 to 04-2016
Target period includes two years

Year: 2016 - End-Month of observation: 5
Forecast Year: 2016 -  Forecast Month: 8
Dropping year: 2016  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
428      9  2015     -1.124536 2015-09-01
429     10  2015     -0.102707 2015-10-01
430     11  2015     -1.188595 2015-11-01
431     12  2015      0.400305 2015-12-01
432      1  2016      0.814189 2016-01-01
433      2  2016     -0.887051 2016-02-01
434      3  2016     -1.096631 2016-03-01
435      4  2016      2.118149 2016-04-01
436      5  2016      0.049850 2016-05-01
There are enough months in the past
Target period: 09-2015 to 05-2016
Target period includes two years

Year: 2016 - End-Month of observation: 6
Forecast Year: 2016 -  Forecast Month: 9
Dropping year: 2016  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
429     10  2015     -0.102707 2015-10-01
430     11  2015     -1.188595 2015-11-01
431     12  2015      0.400305 2015-12-01
432      1  2016      0.814189 2016-01-01
433      2  2016     -0.887051 2016-02-01
434      3  2016     -1.096631 2016-03-01
435      4  2016      2.118149 2016-04-01
436      5  2016      0.049850 2016-05-01
437      6  2016     -0.301783 2016-06-01
There are enough months in the past
Target period: 10-2015 to 06-2016
Target period includes two years

Year: 2016 - End-Month of observation: 7
Forecast Year: 2016 -  Forecast Month: 10
Dropping year: 2016  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
430     11  2015     -1.188595 2015-11-01
431     12  2015      0.400305 2015-12-01
432      1  2016      0.814189 2016-01-01
433      2  2016     -0.887051 2016-02-01
434      3  2016     -1.096631 2016-03-01
435      4  2016      2.118149 2016-04-01
436      5  2016      0.049850 2016-05-01
437      6  2016     -0.301783 2016-06-01
438      7  2016      1.464433 2016-07-01
There are enough months in the past
Target period: 11-2015 to 07-2016
Target period includes two years

Year: 2016 - End-Month of observation: 8
Forecast Year: 2016 -  Forecast Month: 11
Dropping year: 2016  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
431     12  2015      0.400305 2015-12-01
432      1  2016      0.814189 2016-01-01
433      2  2016     -0.887051 2016-02-01
434      3  2016     -1.096631 2016-03-01
435      4  2016      2.118149 2016-04-01
436      5  2016      0.049850 2016-05-01
437      6  2016     -0.301783 2016-06-01
438      7  2016      1.464433 2016-07-01
439      8  2016      0.589616 2016-08-01
There are enough months in the past
Target period: 12-2015 to 08-2016
Target period includes two years

Year: 2016 - End-Month of observation: 9
Forecast Year: 2016 -  Forecast Month: 12
Dropping year: 2016  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
432      1  2016      0.814189 2016-01-01
433      2  2016     -0.887051 2016-02-01
434      3  2016     -1.096631 2016-03-01
435      4  2016      2.118149 2016-04-01
436      5  2016      0.049850 2016-05-01
437      6  2016     -0.301783 2016-06-01
438      7  2016      1.464433 2016-07-01
439      8  2016      0.589616 2016-08-01
440      9  2016      0.693663 2016-09-01
There are enough months in the past
Target period: 01-2016 to 09-2016
Target period includes only one year

Year: 2016 - End-Month of observation: 10
Forecast Year: 2017 -  Forecast Month: 1
Dropping year: 2016  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
433      2  2016     -0.887051 2016-02-01
434      3  2016     -1.096631 2016-03-01
435      4  2016      2.118149 2016-04-01
436      5  2016      0.049850 2016-05-01
437      6  2016     -0.301783 2016-06-01
438      7  2016      1.464433 2016-07-01
439      8  2016      0.589616 2016-08-01
440      9  2016      0.693663 2016-09-01
441     10  2016     -0.580942 2016-10-01
There are enough months in the past
Target period: 02-2016 to 10-2016
Target period includes only one year

Year: 2016 - End-Month of observation: 11
Forecast Year: 2017 -  Forecast Month: 2
Dropping year: 2016  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
434      3  2016     -1.096631 2016-03-01
435      4  2016      2.118149 2016-04-01
436      5  2016      0.049850 2016-05-01
437      6  2016     -0.301783 2016-06-01
438      7  2016      1.464433 2016-07-01
439      8  2016      0.589616 2016-08-01
440      9  2016      0.693663 2016-09-01
441     10  2016     -0.580942 2016-10-01
442     11  2016     -0.514190 2016-11-01
There are enough months in the past
Target period: 03-2016 to 11-2016
Target period includes only one year

Year: 2016 - End-Month of observation: 12
Forecast Year: 2017 -  Forecast Month: 3
Dropping year: 2016  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
435      4  2016      2.118149 2016-04-01
436      5  2016      0.049850 2016-05-01
437      6  2016     -0.301783 2016-06-01
438      7  2016      1.464433 2016-07-01
439      8  2016      0.589616 2016-08-01
440      9  2016      0.693663 2016-09-01
441     10  2016     -0.580942 2016-10-01
442     11  2016     -0.514190 2016-11-01
443     12  2016     -0.312370 2016-12-01
There are enough months in the past
Target period: 04-2016 to 12-2016
Target period includes only one year

Year: 2017 - End-Month of observation: 1
Forecast Year: 2017 -  Forecast Month: 4
Dropping year: 2017  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
436      5  2016      0.049850 2016-05-01
437      6  2016     -0.301783 2016-06-01
438      7  2016      1.464433 2016-07-01
439      8  2016      0.589616 2016-08-01
440      9  2016      0.693663 2016-09-01
441     10  2016     -0.580942 2016-10-01
442     11  2016     -0.514190 2016-11-01
443     12  2016     -0.312370 2016-12-01
444      1  2017      0.200969 2017-01-01
There are enough months in the past
Target period: 05-2016 to 01-2017
Target period includes two years

Year: 2017 - End-Month of observation: 2
Forecast Year: 2017 -  Forecast Month: 5
Dropping year: 2017  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
437      6  2016     -0.301783 2016-06-01
438      7  2016      1.464433 2016-07-01
439      8  2016      0.589616 2016-08-01
440      9  2016      0.693663 2016-09-01
441     10  2016     -0.580942 2016-10-01
442     11  2016     -0.514190 2016-11-01
443     12  2016     -0.312370 2016-12-01
444      1  2017      0.200969 2017-01-01
445      2  2017      0.577828 2017-02-01
There are enough months in the past
Target period: 06-2016 to 02-2017
Target period includes two years

Year: 2017 - End-Month of observation: 3
Forecast Year: 2017 -  Forecast Month: 6
Dropping year: 2017  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
438      7  2016      1.464433 2016-07-01
439      8  2016      0.589616 2016-08-01
440      9  2016      0.693663 2016-09-01
441     10  2016     -0.580942 2016-10-01
442     11  2016     -0.514190 2016-11-01
443     12  2016     -0.312370 2016-12-01
444      1  2017      0.200969 2017-01-01
445      2  2017      0.577828 2017-02-01
446      3  2017     -0.545900 2017-03-01
There are enough months in the past
Target period: 07-2016 to 03-2017
Target period includes two years

Year: 2017 - End-Month of observation: 4
Forecast Year: 2017 -  Forecast Month: 7
Dropping year: 2017  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
439      8  2016      0.589616 2016-08-01
440      9  2016      0.693663 2016-09-01
441     10  2016     -0.580942 2016-10-01
442     11  2016     -0.514190 2016-11-01
443     12  2016     -0.312370 2016-12-01
444      1  2017      0.200969 2017-01-01
445      2  2017      0.577828 2017-02-01
446      3  2017     -0.545900 2017-03-01
447      4  2017     -0.969378 2017-04-01
There are enough months in the past
Target period: 08-2016 to 04-2017
Target period includes two years

Year: 2017 - End-Month of observation: 5
Forecast Year: 2017 -  Forecast Month: 8
Dropping year: 2017  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
440      9  2016      0.693663 2016-09-01
441     10  2016     -0.580942 2016-10-01
442     11  2016     -0.514190 2016-11-01
443     12  2016     -0.312370 2016-12-01
444      1  2017      0.200969 2017-01-01
445      2  2017      0.577828 2017-02-01
446      3  2017     -0.545900 2017-03-01
447      4  2017     -0.969378 2017-04-01
448      5  2017      0.107734 2017-05-01
There are enough months in the past
Target period: 09-2016 to 05-2017
Target period includes two years

Year: 2017 - End-Month of observation: 6
Forecast Year: 2017 -  Forecast Month: 9
Dropping year: 2017  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
441     10  2016     -0.580942 2016-10-01
442     11  2016     -0.514190 2016-11-01
443     12  2016     -0.312370 2016-12-01
444      1  2017      0.200969 2017-01-01
445      2  2017      0.577828 2017-02-01
446      3  2017     -0.545900 2017-03-01
447      4  2017     -0.969378 2017-04-01
448      5  2017      0.107734 2017-05-01
449      6  2017     -0.850826 2017-06-01
There are enough months in the past
Target period: 10-2016 to 06-2017
Target period includes two years

Year: 2017 - End-Month of observation: 7
Forecast Year: 2017 -  Forecast Month: 10
Dropping year: 2017  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
442     11  2016     -0.514190 2016-11-01
443     12  2016     -0.312370 2016-12-01
444      1  2017      0.200969 2017-01-01
445      2  2017      0.577828 2017-02-01
446      3  2017     -0.545900 2017-03-01
447      4  2017     -0.969378 2017-04-01
448      5  2017      0.107734 2017-05-01
449      6  2017     -0.850826 2017-06-01
450      7  2017      0.166312 2017-07-01
There are enough months in the past
Target period: 11-2016 to 07-2017
Target period includes two years

Year: 2017 - End-Month of observation: 8
Forecast Year: 2017 -  Forecast Month: 11
Dropping year: 2017  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
443     12  2016     -0.312370 2016-12-01
444      1  2017      0.200969 2017-01-01
445      2  2017      0.577828 2017-02-01
446      3  2017     -0.545900 2017-03-01
447      4  2017     -0.969378 2017-04-01
448      5  2017      0.107734 2017-05-01
449      6  2017     -0.850826 2017-06-01
450      7  2017      0.166312 2017-07-01
451      8  2017      1.700595 2017-08-01
There are enough months in the past
Target period: 12-2016 to 08-2017
Target period includes two years

Year: 2017 - End-Month of observation: 9
Forecast Year: 2017 -  Forecast Month: 12
Dropping year: 2017  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
444      1  2017      0.200969 2017-01-01
445      2  2017      0.577828 2017-02-01
446      3  2017     -0.545900 2017-03-01
447      4  2017     -0.969378 2017-04-01
448      5  2017      0.107734 2017-05-01
449      6  2017     -0.850826 2017-06-01
450      7  2017      0.166312 2017-07-01
451      8  2017      1.700595 2017-08-01
452      9  2017      1.629718 2017-09-01
There are enough months in the past
Target period: 01-2017 to 09-2017
Target period includes only one year

Year: 2017 - End-Month of observation: 10
Forecast Year: 2018 -  Forecast Month: 1
Dropping year: 2017  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
445      2  2017      0.577828 2017-02-01
446      3  2017     -0.545900 2017-03-01
447      4  2017     -0.969378 2017-04-01
448      5  2017      0.107734 2017-05-01
449      6  2017     -0.850826 2017-06-01
450      7  2017      0.166312 2017-07-01
451      8  2017      1.700595 2017-08-01
452      9  2017      1.629718 2017-09-01
453     10  2017     -0.108481 2017-10-01
There are enough months in the past
Target period: 02-2017 to 10-2017
Target period includes only one year

Year: 2017 - End-Month of observation: 11
Forecast Year: 2018 -  Forecast Month: 2
Dropping year: 2017  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
446      3  2017     -0.545900 2017-03-01
447      4  2017     -0.969378 2017-04-01
448      5  2017      0.107734 2017-05-01
449      6  2017     -0.850826 2017-06-01
450      7  2017      0.166312 2017-07-01
451      8  2017      1.700595 2017-08-01
452      9  2017      1.629718 2017-09-01
453     10  2017     -0.108481 2017-10-01
454     11  2017     -0.337047 2017-11-01
There are enough months in the past
Target period: 03-2017 to 11-2017
Target period includes only one year

Year: 2017 - End-Month of observation: 12
Forecast Year: 2018 -  Forecast Month: 3
Dropping year: 2017  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
447      4  2017     -0.969378 2017-04-01
448      5  2017      0.107734 2017-05-01
449      6  2017     -0.850826 2017-06-01
450      7  2017      0.166312 2017-07-01
451      8  2017      1.700595 2017-08-01
452      9  2017      1.629718 2017-09-01
453     10  2017     -0.108481 2017-10-01
454     11  2017     -0.337047 2017-11-01
455     12  2017     -0.803140 2017-12-01
There are enough months in the past
Target period: 04-2017 to 12-2017
Target period includes only one year

Year: 2018 - End-Month of observation: 1
Forecast Year: 2018 -  Forecast Month: 4
Dropping year: 2018  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
448      5  2017      0.107734 2017-05-01
449      6  2017     -0.850826 2017-06-01
450      7  2017      0.166312 2017-07-01
451      8  2017      1.700595 2017-08-01
452      9  2017      1.629718 2017-09-01
453     10  2017     -0.108481 2017-10-01
454     11  2017     -0.337047 2017-11-01
455     12  2017     -0.803140 2017-12-01
456      1  2018      0.324539 2018-01-01
There are enough months in the past
Target period: 05-2017 to 01-2018
Target period includes two years

Year: 2018 - End-Month of observation: 2
Forecast Year: 2018 -  Forecast Month: 5
Dropping year: 2018  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
449      6  2017     -0.850826 2017-06-01
450      7  2017      0.166312 2017-07-01
451      8  2017      1.700595 2017-08-01
452      9  2017      1.629718 2017-09-01
453     10  2017     -0.108481 2017-10-01
454     11  2017     -0.337047 2017-11-01
455     12  2017     -0.803140 2017-12-01
456      1  2018      0.324539 2018-01-01
457      2  2018     -0.659732 2018-02-01
There are enough months in the past
Target period: 06-2017 to 02-2018
Target period includes two years

Year: 2018 - End-Month of observation: 3
Forecast Year: 2018 -  Forecast Month: 6
Dropping year: 2018  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
450      7  2017      0.166312 2017-07-01
451      8  2017      1.700595 2017-08-01
452      9  2017      1.629718 2017-09-01
453     10  2017     -0.108481 2017-10-01
454     11  2017     -0.337047 2017-11-01
455     12  2017     -0.803140 2017-12-01
456      1  2018      0.324539 2018-01-01
457      2  2018     -0.659732 2018-02-01
458      3  2018      0.112274 2018-03-01
There are enough months in the past
Target period: 07-2017 to 03-2018
Target period includes two years

Year: 2018 - End-Month of observation: 4
Forecast Year: 2018 -  Forecast Month: 7
Dropping year: 2018  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
451      8  2017      1.700595 2017-08-01
452      9  2017      1.629718 2017-09-01
453     10  2017     -0.108481 2017-10-01
454     11  2017     -0.337047 2017-11-01
455     12  2017     -0.803140 2017-12-01
456      1  2018      0.324539 2018-01-01
457      2  2018     -0.659732 2018-02-01
458      3  2018      0.112274 2018-03-01
459      4  2018     -0.979009 2018-04-01
There are enough months in the past
Target period: 08-2017 to 04-2018
Target period includes two years

Year: 2018 - End-Month of observation: 5
Forecast Year: 2018 -  Forecast Month: 8
Dropping year: 2018  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
452      9  2017      1.629718 2017-09-01
453     10  2017     -0.108481 2017-10-01
454     11  2017     -0.337047 2017-11-01
455     12  2017     -0.803140 2017-12-01
456      1  2018      0.324539 2018-01-01
457      2  2018     -0.659732 2018-02-01
458      3  2018      0.112274 2018-03-01
459      4  2018     -0.979009 2018-04-01
460      5  2018     -0.537679 2018-05-01
There are enough months in the past
Target period: 09-2017 to 05-2018
Target period includes two years

Year: 2018 - End-Month of observation: 6
Forecast Year: 2018 -  Forecast Month: 9
Dropping year: 2018  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
453     10  2017     -0.108481 2017-10-01
454     11  2017     -0.337047 2017-11-01
455     12  2017     -0.803140 2017-12-01
456      1  2018      0.324539 2018-01-01
457      2  2018     -0.659732 2018-02-01
458      3  2018      0.112274 2018-03-01
459      4  2018     -0.979009 2018-04-01
460      5  2018     -0.537679 2018-05-01
461      6  2018     -0.520173 2018-06-01
There are enough months in the past
Target period: 10-2017 to 06-2018
Target period includes two years

Year: 2018 - End-Month of observation: 7
Forecast Year: 2018 -  Forecast Month: 10
Dropping year: 2018  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
454     11  2017     -0.337047 2017-11-01
455     12  2017     -0.803140 2017-12-01
456      1  2018      0.324539 2018-01-01
457      2  2018     -0.659732 2018-02-01
458      3  2018      0.112274 2018-03-01
459      4  2018     -0.979009 2018-04-01
460      5  2018     -0.537679 2018-05-01
461      6  2018     -0.520173 2018-06-01
462      7  2018      0.883619 2018-07-01
There are enough months in the past
Target period: 11-2017 to 07-2018
Target period includes two years

Year: 2018 - End-Month of observation: 8
Forecast Year: 2018 -  Forecast Month: 11
Dropping year: 2018  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
455     12  2017     -0.803140 2017-12-01
456      1  2018      0.324539 2018-01-01
457      2  2018     -0.659732 2018-02-01
458      3  2018      0.112274 2018-03-01
459      4  2018     -0.979009 2018-04-01
460      5  2018     -0.537679 2018-05-01
461      6  2018     -0.520173 2018-06-01
462      7  2018      0.883619 2018-07-01
463      8  2018           NaN 2018-08-01
There are enough months in the past
Target period: 12-2017 to 08-2018
Target period includes two years

Year: 2018 - End-Month of observation: 9
Forecast Year: 2018 -  Forecast Month: 12
Dropping year: 2018  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
456      1  2018      0.324539 2018-01-01
457      2  2018     -0.659732 2018-02-01
458      3  2018      0.112274 2018-03-01
459      4  2018     -0.979009 2018-04-01
460      5  2018     -0.537679 2018-05-01
461      6  2018     -0.520173 2018-06-01
462      7  2018      0.883619 2018-07-01
463      8  2018           NaN 2018-08-01
464      9  2018           NaN 2018-09-01
There are enough months in the past
Target period: 01-2018 to 09-2018
Target period includes only one year

Year: 2018 - End-Month of observation: 10
Forecast Year: 2019 -  Forecast Month: 1
Dropping year: 2018  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
457      2  2018     -0.659732 2018-02-01
458      3  2018      0.112274 2018-03-01
459      4  2018     -0.979009 2018-04-01
460      5  2018     -0.537679 2018-05-01
461      6  2018     -0.520173 2018-06-01
462      7  2018      0.883619 2018-07-01
463      8  2018           NaN 2018-08-01
464      9  2018           NaN 2018-09-01
465     10  2018           NaN 2018-10-01
There are enough months in the past
Target period: 02-2018 to 10-2018
Target period includes only one year

Year: 2018 - End-Month of observation: 11
Forecast Year: 2019 -  Forecast Month: 2
Dropping year: 2018  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
458      3  2018      0.112274 2018-03-01
459      4  2018     -0.979009 2018-04-01
460      5  2018     -0.537679 2018-05-01
461      6  2018     -0.520173 2018-06-01
462      7  2018      0.883619 2018-07-01
463      8  2018           NaN 2018-08-01
464      9  2018           NaN 2018-09-01
465     10  2018           NaN 2018-10-01
466     11  2018           NaN 2018-11-01
There are enough months in the past
Target period: 03-2018 to 11-2018
Target period includes only one year

Year: 2018 - End-Month of observation: 12
Forecast Year: 2019 -  Forecast Month: 3
Dropping year: 2018  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
459      4  2018     -0.979009 2018-04-01
460      5  2018     -0.537679 2018-05-01
461      6  2018     -0.520173 2018-06-01
462      7  2018      0.883619 2018-07-01
463      8  2018           NaN 2018-08-01
464      9  2018           NaN 2018-09-01
465     10  2018           NaN 2018-10-01
466     11  2018           NaN 2018-11-01
467     12  2018           NaN 2018-12-01
There are enough months in the past
Target period: 04-2018 to 12-2018
Target period includes only one year

Year: 2019 - End-Month of observation: 1
Forecast Year: 2019 -  Forecast Month: 4
Dropping year: 2019  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
460      5  2018     -0.537679 2018-05-01
461      6  2018     -0.520173 2018-06-01
462      7  2018      0.883619 2018-07-01
463      8  2018           NaN 2018-08-01
464      9  2018           NaN 2018-09-01
465     10  2018           NaN 2018-10-01
466     11  2018           NaN 2018-11-01
467     12  2018           NaN 2018-12-01
468      1  2019           NaN 2019-01-01
There are enough months in the past
Target period: 05-2018 to 01-2019
Target period includes two years

Year: 2019 - End-Month of observation: 2
Forecast Year: 2019 -  Forecast Month: 5
Dropping year: 2019  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
461      6  2018     -0.520173 2018-06-01
462      7  2018      0.883619 2018-07-01
463      8  2018           NaN 2018-08-01
464      9  2018           NaN 2018-09-01
465     10  2018           NaN 2018-10-01
466     11  2018           NaN 2018-11-01
467     12  2018           NaN 2018-12-01
468      1  2019           NaN 2019-01-01
469      2  2019           NaN 2019-02-01
There are enough months in the past
Target period: 06-2018 to 02-2019
Target period includes two years

Year: 2019 - End-Month of observation: 3
Forecast Year: 2019 -  Forecast Month: 6
Dropping year: 2019  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
462      7  2018      0.883619 2018-07-01
463      8  2018           NaN 2018-08-01
464      9  2018           NaN 2018-09-01
465     10  2018           NaN 2018-10-01
466     11  2018           NaN 2018-11-01
467     12  2018           NaN 2018-12-01
468      1  2019           NaN 2019-01-01
469      2  2019           NaN 2019-02-01
470      3  2019     -0.449993 2019-03-01
There are enough months in the past
Target period: 07-2018 to 03-2019
Target period includes two years

Year: 2019 - End-Month of observation: 4
Forecast Year: 2019 -  Forecast Month: 7
Dropping year: 2019  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
463      8  2018           NaN 2018-08-01
464      9  2018           NaN 2018-09-01
465     10  2018           NaN 2018-10-01
466     11  2018           NaN 2018-11-01
467     12  2018           NaN 2018-12-01
468      1  2019           NaN 2019-01-01
469      2  2019           NaN 2019-02-01
470      3  2019     -0.449993 2019-03-01
471      4  2019     -1.319303 2019-04-01
There are enough months in the past
Target period: 08-2018 to 04-2019
Target period includes two years

Year: 2019 - End-Month of observation: 5
Forecast Year: 2019 -  Forecast Month: 8
Dropping year: 2019  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
464      9  2018           NaN 2018-09-01
465     10  2018           NaN 2018-10-01
466     11  2018           NaN 2018-11-01
467     12  2018           NaN 2018-12-01
468      1  2019           NaN 2019-01-01
469      2  2019           NaN 2019-02-01
470      3  2019     -0.449993 2019-03-01
471      4  2019     -1.319303 2019-04-01
472      5  2019      0.053286 2019-05-01
There are enough months in the past
Target period: 09-2018 to 05-2019
Target period includes two years

Year: 2019 - End-Month of observation: 6
Forecast Year: 2019 -  Forecast Month: 9
Dropping year: 2019  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
465     10  2018           NaN 2018-10-01
466     11  2018           NaN 2018-11-01
467     12  2018           NaN 2018-12-01
468      1  2019           NaN 2019-01-01
469      2  2019           NaN 2019-02-01
470      3  2019     -0.449993 2019-03-01
471      4  2019     -1.319303 2019-04-01
472      5  2019      0.053286 2019-05-01
473      6  2019      1.715769 2019-06-01
There are enough months in the past
Target period: 10-2018 to 06-2019
Target period includes two years

Year: 2019 - End-Month of observation: 7
Forecast Year: 2019 -  Forecast Month: 10
Dropping year: 2019  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
466     11  2018           NaN 2018-11-01
467     12  2018           NaN 2018-12-01
468      1  2019           NaN 2019-01-01
469      2  2019           NaN 2019-02-01
470      3  2019     -0.449993 2019-03-01
471      4  2019     -1.319303 2019-04-01
472      5  2019      0.053286 2019-05-01
473      6  2019      1.715769 2019-06-01
474      7  2019     -0.018995 2019-07-01
There are enough months in the past
Target period: 11-2018 to 07-2019
Target period includes two years

Year: 2019 - End-Month of observation: 8
Forecast Year: 2019 -  Forecast Month: 11
Dropping year: 2019  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
467     12  2018           NaN 2018-12-01
468      1  2019           NaN 2019-01-01
469      2  2019           NaN 2019-02-01
470      3  2019     -0.449993 2019-03-01
471      4  2019     -1.319303 2019-04-01
472      5  2019      0.053286 2019-05-01
473      6  2019      1.715769 2019-06-01
474      7  2019     -0.018995 2019-07-01
475      8  2019      0.098847 2019-08-01
There are enough months in the past
Target period: 12-2018 to 08-2019
Target period includes two years

Year: 2019 - End-Month of observation: 9
Forecast Year: 2019 -  Forecast Month: 12
Dropping year: 2019  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
468      1  2019           NaN 2019-01-01
469      2  2019           NaN 2019-02-01
470      3  2019     -0.449993 2019-03-01
471      4  2019     -1.319303 2019-04-01
472      5  2019      0.053286 2019-05-01
473      6  2019      1.715769 2019-06-01
474      7  2019     -0.018995 2019-07-01
475      8  2019      0.098847 2019-08-01
476      9  2019      0.482405 2019-09-01
There are enough months in the past
Target period: 01-2019 to 09-2019
Target period includes only one year

Year: 2019 - End-Month of observation: 10
Forecast Year: 2020 -  Forecast Month: 1
Dropping year: 2019  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
469      2  2019           NaN 2019-02-01
470      3  2019     -0.449993 2019-03-01
471      4  2019     -1.319303 2019-04-01
472      5  2019      0.053286 2019-05-01
473      6  2019      1.715769 2019-06-01
474      7  2019     -0.018995 2019-07-01
475      8  2019      0.098847 2019-08-01
476      9  2019      0.482405 2019-09-01
477     10  2019      1.729348 2019-10-01
There are enough months in the past
Target period: 02-2019 to 10-2019
Target period includes only one year

Year: 2019 - End-Month of observation: 11
Forecast Year: 2020 -  Forecast Month: 2
Dropping year: 2019  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
470      3  2019     -0.449993 2019-03-01
471      4  2019     -1.319303 2019-04-01
472      5  2019      0.053286 2019-05-01
473      6  2019      1.715769 2019-06-01
474      7  2019     -0.018995 2019-07-01
475      8  2019      0.098847 2019-08-01
476      9  2019      0.482405 2019-09-01
477     10  2019      1.729348 2019-10-01
478     11  2019     -0.157611 2019-11-01
There are enough months in the past
Target period: 03-2019 to 11-2019
Target period includes only one year

Year: 2019 - End-Month of observation: 12
Forecast Year: 2020 -  Forecast Month: 3
Dropping year: 2019  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
471      4  2019     -1.319303 2019-04-01
472      5  2019      0.053286 2019-05-01
473      6  2019      1.715769 2019-06-01
474      7  2019     -0.018995 2019-07-01
475      8  2019      0.098847 2019-08-01
476      9  2019      0.482405 2019-09-01
477     10  2019      1.729348 2019-10-01
478     11  2019     -0.157611 2019-11-01
479     12  2019     -0.782450 2019-12-01
There are enough months in the past
Target period: 04-2019 to 12-2019
Target period includes only one year

Year: 2020 - End-Month of observation: 1
Forecast Year: 2020 -  Forecast Month: 4
Dropping year: 2020  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
472      5  2019      0.053286 2019-05-01
473      6  2019      1.715769 2019-06-01
474      7  2019     -0.018995 2019-07-01
475      8  2019      0.098847 2019-08-01
476      9  2019      0.482405 2019-09-01
477     10  2019      1.729348 2019-10-01
478     11  2019     -0.157611 2019-11-01
479     12  2019     -0.782450 2019-12-01
480      1  2020     -0.385739 2020-01-01
There are enough months in the past
Target period: 05-2019 to 01-2020
Target period includes two years

Year: 2020 - End-Month of observation: 2
Forecast Year: 2020 -  Forecast Month: 5
Dropping year: 2020  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
473      6  2019      1.715769 2019-06-01
474      7  2019     -0.018995 2019-07-01
475      8  2019      0.098847 2019-08-01
476      9  2019      0.482405 2019-09-01
477     10  2019      1.729348 2019-10-01
478     11  2019     -0.157611 2019-11-01
479     12  2019     -0.782450 2019-12-01
480      1  2020     -0.385739 2020-01-01
481      2  2020     -0.742382 2020-02-01
There are enough months in the past
Target period: 06-2019 to 02-2020
Target period includes two years

Year: 2020 - End-Month of observation: 3
Forecast Year: 2020 -  Forecast Month: 6
Dropping year: 2020  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
474      7  2019     -0.018995 2019-07-01
475      8  2019      0.098847 2019-08-01
476      9  2019      0.482405 2019-09-01
477     10  2019      1.729348 2019-10-01
478     11  2019     -0.157611 2019-11-01
479     12  2019     -0.782450 2019-12-01
480      1  2020     -0.385739 2020-01-01
481      2  2020     -0.742382 2020-02-01
482      3  2020     -1.059530 2020-03-01
There are enough months in the past
Target period: 07-2019 to 03-2020
Target period includes two years

Year: 2020 - End-Month of observation: 4
Forecast Year: 2020 -  Forecast Month: 7
Dropping year: 2020  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
475      8  2019      0.098847 2019-08-01
476      9  2019      0.482405 2019-09-01
477     10  2019      1.729348 2019-10-01
478     11  2019     -0.157611 2019-11-01
479     12  2019     -0.782450 2019-12-01
480      1  2020     -0.385739 2020-01-01
481      2  2020     -0.742382 2020-02-01
482      3  2020     -1.059530 2020-03-01
483      4  2020     -1.188353 2020-04-01
There are enough months in the past
Target period: 08-2019 to 04-2020
Target period includes two years

Year: 2020 - End-Month of observation: 5
Forecast Year: 2020 -  Forecast Month: 8
Dropping year: 2020  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
476      9  2019      0.482405 2019-09-01
477     10  2019      1.729348 2019-10-01
478     11  2019     -0.157611 2019-11-01
479     12  2019     -0.782450 2019-12-01
480      1  2020     -0.385739 2020-01-01
481      2  2020     -0.742382 2020-02-01
482      3  2020     -1.059530 2020-03-01
483      4  2020     -1.188353 2020-04-01
484      5  2020     -1.607545 2020-05-01
There are enough months in the past
Target period: 09-2019 to 05-2020
Target period includes two years

Year: 2020 - End-Month of observation: 6
Forecast Year: 2020 -  Forecast Month: 9
Dropping year: 2020  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
477     10  2019      1.729348 2019-10-01
478     11  2019     -0.157611 2019-11-01
479     12  2019     -0.782450 2019-12-01
480      1  2020     -0.385739 2020-01-01
481      2  2020     -0.742382 2020-02-01
482      3  2020     -1.059530 2020-03-01
483      4  2020     -1.188353 2020-04-01
484      5  2020     -1.607545 2020-05-01
485      6  2020      0.585062 2020-06-01
There are enough months in the past
Target period: 10-2019 to 06-2020
Target period includes two years

Year: 2020 - End-Month of observation: 7
Forecast Year: 2020 -  Forecast Month: 10
Dropping year: 2020  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
478     11  2019     -0.157611 2019-11-01
479     12  2019     -0.782450 2019-12-01
480      1  2020     -0.385739 2020-01-01
481      2  2020     -0.742382 2020-02-01
482      3  2020     -1.059530 2020-03-01
483      4  2020     -1.188353 2020-04-01
484      5  2020     -1.607545 2020-05-01
485      6  2020      0.585062 2020-06-01
486      7  2020     -0.531656 2020-07-01
There are enough months in the past
Target period: 11-2019 to 07-2020
Target period includes two years

Year: 2020 - End-Month of observation: 8
Forecast Year: 2020 -  Forecast Month: 11
Dropping year: 2020  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
479     12  2019     -0.782450 2019-12-01
480      1  2020     -0.385739 2020-01-01
481      2  2020     -0.742382 2020-02-01
482      3  2020     -1.059530 2020-03-01
483      4  2020     -1.188353 2020-04-01
484      5  2020     -1.607545 2020-05-01
485      6  2020      0.585062 2020-06-01
486      7  2020     -0.531656 2020-07-01
487      8  2020     -0.737193 2020-08-01
There are enough months in the past
Target period: 12-2019 to 08-2020
Target period includes two years

Year: 2020 - End-Month of observation: 9
Forecast Year: 2020 -  Forecast Month: 12
Dropping year: 2020  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
480      1  2020     -0.385739 2020-01-01
481      2  2020     -0.742382 2020-02-01
482      3  2020     -1.059530 2020-03-01
483      4  2020     -1.188353 2020-04-01
484      5  2020     -1.607545 2020-05-01
485      6  2020      0.585062 2020-06-01
486      7  2020     -0.531656 2020-07-01
487      8  2020     -0.737193 2020-08-01
488      9  2020      0.104265 2020-09-01
There are enough months in the past
Target period: 01-2020 to 09-2020
Target period includes only one year

Year: 2020 - End-Month of observation: 10
Forecast Year: 2021 -  Forecast Month: 1
Dropping year: 2020  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
481      2  2020     -0.742382 2020-02-01
482      3  2020     -1.059530 2020-03-01
483      4  2020     -1.188353 2020-04-01
484      5  2020     -1.607545 2020-05-01
485      6  2020      0.585062 2020-06-01
486      7  2020     -0.531656 2020-07-01
487      8  2020     -0.737193 2020-08-01
488      9  2020      0.104265 2020-09-01
489     10  2020     -0.961647 2020-10-01
There are enough months in the past
Target period: 02-2020 to 10-2020
Target period includes only one year

Year: 2020 - End-Month of observation: 11
Forecast Year: 2021 -  Forecast Month: 2
Dropping year: 2020  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
482      3  2020     -1.059530 2020-03-01
483      4  2020     -1.188353 2020-04-01
484      5  2020     -1.607545 2020-05-01
485      6  2020      0.585062 2020-06-01
486      7  2020     -0.531656 2020-07-01
487      8  2020     -0.737193 2020-08-01
488      9  2020      0.104265 2020-09-01
489     10  2020     -0.961647 2020-10-01
490     11  2020     -1.797352 2020-11-01
There are enough months in the past
Target period: 03-2020 to 11-2020
Target period includes only one year

Year: 2020 - End-Month of observation: 12
Forecast Year: 2021 -  Forecast Month: 3
Dropping year: 2020  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
483      4  2020     -1.188353 2020-04-01
484      5  2020     -1.607545 2020-05-01
485      6  2020      0.585062 2020-06-01
486      7  2020     -0.531656 2020-07-01
487      8  2020     -0.737193 2020-08-01
488      9  2020      0.104265 2020-09-01
489     10  2020     -0.961647 2020-10-01
490     11  2020     -1.797352 2020-11-01
491     12  2020     -1.398219 2020-12-01
There are enough months in the past
Target period: 04-2020 to 12-2020
Target period includes only one year

Year: 2021 - End-Month of observation: 1
Forecast Year: 2021 -  Forecast Month: 4
Dropping year: 2021  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
484      5  2020     -1.607545 2020-05-01
485      6  2020      0.585062 2020-06-01
486      7  2020     -0.531656 2020-07-01
487      8  2020     -0.737193 2020-08-01
488      9  2020      0.104265 2020-09-01
489     10  2020     -0.961647 2020-10-01
490     11  2020     -1.797352 2020-11-01
491     12  2020     -1.398219 2020-12-01
492      1  2021     -0.230398 2021-01-01
There are enough months in the past
Target period: 05-2020 to 01-2021
Target period includes two years

Year: 2021 - End-Month of observation: 2
Forecast Year: 2021 -  Forecast Month: 5
Dropping year: 2021  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
485      6  2020      0.585062 2020-06-01
486      7  2020     -0.531656 2020-07-01
487      8  2020     -0.737193 2020-08-01
488      9  2020      0.104265 2020-09-01
489     10  2020     -0.961647 2020-10-01
490     11  2020     -1.797352 2020-11-01
491     12  2020     -1.398219 2020-12-01
492      1  2021     -0.230398 2021-01-01
493      2  2021      0.860497 2021-02-01
There are enough months in the past
Target period: 06-2020 to 02-2021
Target period includes two years

Year: 2021 - End-Month of observation: 3
Forecast Year: 2021 -  Forecast Month: 6
Dropping year: 2021  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
486      7  2020     -0.531656 2020-07-01
487      8  2020     -0.737193 2020-08-01
488      9  2020      0.104265 2020-09-01
489     10  2020     -0.961647 2020-10-01
490     11  2020     -1.797352 2020-11-01
491     12  2020     -1.398219 2020-12-01
492      1  2021     -0.230398 2021-01-01
493      2  2021      0.860497 2021-02-01
494      3  2021      0.710564 2021-03-01
There are enough months in the past
Target period: 07-2020 to 03-2021
Target period includes two years

Year: 2021 - End-Month of observation: 4
Forecast Year: 2021 -  Forecast Month: 7
Dropping year: 2021  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
487      8  2020     -0.737193 2020-08-01
488      9  2020      0.104265 2020-09-01
489     10  2020     -0.961647 2020-10-01
490     11  2020     -1.797352 2020-11-01
491     12  2020     -1.398219 2020-12-01
492      1  2021     -0.230398 2021-01-01
493      2  2021      0.860497 2021-02-01
494      3  2021      0.710564 2021-03-01
495      4  2021      0.670950 2021-04-01
There are enough months in the past
Target period: 08-2020 to 04-2021
Target period includes two years

Year: 2021 - End-Month of observation: 5
Forecast Year: 2021 -  Forecast Month: 8
Dropping year: 2021  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
488      9  2020      0.104265 2020-09-01
489     10  2020     -0.961647 2020-10-01
490     11  2020     -1.797352 2020-11-01
491     12  2020     -1.398219 2020-12-01
492      1  2021     -0.230398 2021-01-01
493      2  2021      0.860497 2021-02-01
494      3  2021      0.710564 2021-03-01
495      4  2021      0.670950 2021-04-01
496      5  2021     -0.087954 2021-05-01
There are enough months in the past
Target period: 09-2020 to 05-2021
Target period includes two years

Year: 2021 - End-Month of observation: 6
Forecast Year: 2021 -  Forecast Month: 9
Dropping year: 2021  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
489     10  2020     -0.961647 2020-10-01
490     11  2020     -1.797352 2020-11-01
491     12  2020     -1.398219 2020-12-01
492      1  2021     -0.230398 2021-01-01
493      2  2021      0.860497 2021-02-01
494      3  2021      0.710564 2021-03-01
495      4  2021      0.670950 2021-04-01
496      5  2021     -0.087954 2021-05-01
497      6  2021      1.115231 2021-06-01
There are enough months in the past
Target period: 10-2020 to 06-2021
Target period includes two years

Year: 2021 - End-Month of observation: 7
Forecast Year: 2021 -  Forecast Month: 10
Dropping year: 2021  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
490     11  2020     -1.797352 2020-11-01
491     12  2020     -1.398219 2020-12-01
492      1  2021     -0.230398 2021-01-01
493      2  2021      0.860497 2021-02-01
494      3  2021      0.710564 2021-03-01
495      4  2021      0.670950 2021-04-01
496      5  2021     -0.087954 2021-05-01
497      6  2021      1.115231 2021-06-01
498      7  2021     -0.129605 2021-07-01
There are enough months in the past
Target period: 11-2020 to 07-2021
Target period includes two years

Year: 2021 - End-Month of observation: 8
Forecast Year: 2021 -  Forecast Month: 11
Dropping year: 2021  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
491     12  2020     -1.398219 2020-12-01
492      1  2021     -0.230398 2021-01-01
493      2  2021      0.860497 2021-02-01
494      3  2021      0.710564 2021-03-01
495      4  2021      0.670950 2021-04-01
496      5  2021     -0.087954 2021-05-01
497      6  2021      1.115231 2021-06-01
498      7  2021     -0.129605 2021-07-01
499      8  2021     -0.005090 2021-08-01
There are enough months in the past
Target period: 12-2020 to 08-2021
Target period includes two years

Year: 2021 - End-Month of observation: 9
Forecast Year: 2021 -  Forecast Month: 12
Dropping year: 2021  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
492      1  2021     -0.230398 2021-01-01
493      2  2021      0.860497 2021-02-01
494      3  2021      0.710564 2021-03-01
495      4  2021      0.670950 2021-04-01
496      5  2021     -0.087954 2021-05-01
497      6  2021      1.115231 2021-06-01
498      7  2021     -0.129605 2021-07-01
499      8  2021     -0.005090 2021-08-01
500      9  2021      0.059747 2021-09-01
There are enough months in the past
Target period: 01-2021 to 09-2021
Target period includes only one year

Year: 2021 - End-Month of observation: 10
Forecast Year: 2022 -  Forecast Month: 1
Dropping year: 2021  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
493      2  2021      0.860497 2021-02-01
494      3  2021      0.710564 2021-03-01
495      4  2021      0.670950 2021-04-01
496      5  2021     -0.087954 2021-05-01
497      6  2021      1.115231 2021-06-01
498      7  2021     -0.129605 2021-07-01
499      8  2021     -0.005090 2021-08-01
500      9  2021      0.059747 2021-09-01
501     10  2021     -1.006693 2021-10-01
There are enough months in the past
Target period: 02-2021 to 10-2021
Target period includes only one year

Year: 2021 - End-Month of observation: 11
Forecast Year: 2022 -  Forecast Month: 2
Dropping year: 2021  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
494      3  2021      0.710564 2021-03-01
495      4  2021      0.670950 2021-04-01
496      5  2021     -0.087954 2021-05-01
497      6  2021      1.115231 2021-06-01
498      7  2021     -0.129605 2021-07-01
499      8  2021     -0.005090 2021-08-01
500      9  2021      0.059747 2021-09-01
501     10  2021     -1.006693 2021-10-01
502     11  2021     -1.153155 2021-11-01
There are enough months in the past
Target period: 03-2021 to 11-2021
Target period includes only one year

Year: 2021 - End-Month of observation: 12
Forecast Year: 2022 -  Forecast Month: 3
Dropping year: 2021  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
495      4  2021      0.670950 2021-04-01
496      5  2021     -0.087954 2021-05-01
497      6  2021      1.115231 2021-06-01
498      7  2021     -0.129605 2021-07-01
499      8  2021     -0.005090 2021-08-01
500      9  2021      0.059747 2021-09-01
501     10  2021     -1.006693 2021-10-01
502     11  2021     -1.153155 2021-11-01
503     12  2021     -1.154836 2021-12-01
There are enough months in the past
Target period: 04-2021 to 12-2021
Target period includes only one year

Year: 2022 - End-Month of observation: 1
Forecast Year: 2022 -  Forecast Month: 4
Dropping year: 2022  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
496      5  2021     -0.087954 2021-05-01
497      6  2021      1.115231 2021-06-01
498      7  2021     -0.129605 2021-07-01
499      8  2021     -0.005090 2021-08-01
500      9  2021      0.059747 2021-09-01
501     10  2021     -1.006693 2021-10-01
502     11  2021     -1.153155 2021-11-01
503     12  2021     -1.154836 2021-12-01
504      1  2022      1.141266 2022-01-01
There are enough months in the past
Target period: 05-2021 to 01-2022
Target period includes two years

Year: 2022 - End-Month of observation: 2
Forecast Year: 2022 -  Forecast Month: 5
Dropping year: 2022  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
497      6  2021      1.115231 2021-06-01
498      7  2021     -0.129605 2021-07-01
499      8  2021     -0.005090 2021-08-01
500      9  2021      0.059747 2021-09-01
501     10  2021     -1.006693 2021-10-01
502     11  2021     -1.153155 2021-11-01
503     12  2021     -1.154836 2021-12-01
504      1  2022      1.141266 2022-01-01
505      2  2022     -0.252152 2022-02-01
There are enough months in the past
Target period: 06-2021 to 02-2022
Target period includes two years

Year: 2022 - End-Month of observation: 3
Forecast Year: 2022 -  Forecast Month: 6
Dropping year: 2022  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
498      7  2021     -0.129605 2021-07-01
499      8  2021     -0.005090 2021-08-01
500      9  2021      0.059747 2021-09-01
501     10  2021     -1.006693 2021-10-01
502     11  2021     -1.153155 2021-11-01
503     12  2021     -1.154836 2021-12-01
504      1  2022      1.141266 2022-01-01
505      2  2022     -0.252152 2022-02-01
506      3  2022     -0.389803 2022-03-01
There are enough months in the past
Target period: 07-2021 to 03-2022
Target period includes two years

Year: 2022 - End-Month of observation: 4
Forecast Year: 2022 -  Forecast Month: 7
Dropping year: 2022  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
499      8  2021     -0.005090 2021-08-01
500      9  2021      0.059747 2021-09-01
501     10  2021     -1.006693 2021-10-01
502     11  2021     -1.153155 2021-11-01
503     12  2021     -1.154836 2021-12-01
504      1  2022      1.141266 2022-01-01
505      2  2022     -0.252152 2022-02-01
506      3  2022     -0.389803 2022-03-01
507      4  2022     -0.613546 2022-04-01
There are enough months in the past
Target period: 08-2021 to 04-2022
Target period includes two years

Year: 2022 - End-Month of observation: 5
Forecast Year: 2022 -  Forecast Month: 8
Dropping year: 2022  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
500      9  2021      0.059747 2021-09-01
501     10  2021     -1.006693 2021-10-01
502     11  2021     -1.153155 2021-11-01
503     12  2021     -1.154836 2021-12-01
504      1  2022      1.141266 2022-01-01
505      2  2022     -0.252152 2022-02-01
506      3  2022     -0.389803 2022-03-01
507      4  2022     -0.613546 2022-04-01
508      5  2022     -0.178636 2022-05-01
There are enough months in the past
Target period: 09-2021 to 05-2022
Target period includes two years

Year: 2022 - End-Month of observation: 6
Forecast Year: 2022 -  Forecast Month: 9
Dropping year: 2022  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
501     10  2021     -1.006693 2021-10-01
502     11  2021     -1.153155 2021-11-01
503     12  2021     -1.154836 2021-12-01
504      1  2022      1.141266 2022-01-01
505      2  2022     -0.252152 2022-02-01
506      3  2022     -0.389803 2022-03-01
507      4  2022     -0.613546 2022-04-01
508      5  2022     -0.178636 2022-05-01
509      6  2022     -1.331390 2022-06-01
There are enough months in the past
Target period: 10-2021 to 06-2022
Target period includes two years

Year: 2022 - End-Month of observation: 7
Forecast Year: 2022 -  Forecast Month: 10
Dropping year: 2022  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
502     11  2021     -1.153155 2021-11-01
503     12  2021     -1.154836 2021-12-01
504      1  2022      1.141266 2022-01-01
505      2  2022     -0.252152 2022-02-01
506      3  2022     -0.389803 2022-03-01
507      4  2022     -0.613546 2022-04-01
508      5  2022     -0.178636 2022-05-01
509      6  2022     -1.331390 2022-06-01
510      7  2022      0.197415 2022-07-01
There are enough months in the past
Target period: 11-2021 to 07-2022
Target period includes two years

Year: 2022 - End-Month of observation: 8
Forecast Year: 2022 -  Forecast Month: 11
Dropping year: 2022  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
503     12  2021     -1.154836 2021-12-01
504      1  2022      1.141266 2022-01-01
505      2  2022     -0.252152 2022-02-01
506      3  2022     -0.389803 2022-03-01
507      4  2022     -0.613546 2022-04-01
508      5  2022     -0.178636 2022-05-01
509      6  2022     -1.331390 2022-06-01
510      7  2022      0.197415 2022-07-01
511      8  2022     -1.282212 2022-08-01
There are enough months in the past
Target period: 12-2021 to 08-2022
Target period includes two years

Year: 2022 - End-Month of observation: 9
Forecast Year: 2022 -  Forecast Month: 12
Dropping year: 2022  - get series for analysis.
     Month  Year  Anomaly_Qlog       DATE
504      1  2022      1.141266 2022-01-01
505      2  2022     -0.252152 2022-02-01
506      3  2022     -0.389803 2022-03-01
507      4  2022     -0.613546 2022-04-01
508      5  2022     -0.178636 2022-05-01
509      6  2022     -1.331390 2022-06-01
510      7  2022      0.197415 2022-07-01
511      8  2022     -1.282212 2022-08-01
512      9  2022     -1.975643 2022-09-01
There are enough months in the past
Target period: 01-2022 to 09-2022
Target period includes only one year

Year: 2022 - End-Month of observation: 10
Forecast Year: 2023 -  Forecast Month: 1
Forecast Year out of range

In [41]:
RESULTS = pd.DataFrame()
RESULTS['MONTH_PRED'] = MON_PRED
RESULTS['YEAR_PRED'] = ANO_PRED
RESULTS['MONTH_TARG'] = MON_TARG
RESULTS['YEAR_TARG'] = ANO_TARG
RESULTS['RMSE'] = RMSE
RESULTS['TARG'] = TARG
RESULTS['PRED'] = PRED
RESULTS['OBS_ANOM'] = OBS_ANOM
RESULTS['MEAN_ANOM_HIND'] = MEAN_ANOM_HIND
RESULTS['STD_ANOM_HIND'] = STD_ANOM_HIND
RESULTS['Q1_ANOM_HIND'] = Q1_ANOM_HIND
RESULTS['Q3_ANOM_HIND'] = Q3_ANOM_HIND

In [42]:
RESULTS.iloc[66:80]

,MONTH_PRED,YEAR_PRED,MONTH_TARG,YEAR_TARG,RMSE,TARG,PRED,OBS_ANOM,MEAN_ANOM_HIND,STD_ANOM_HIND,Q1_ANOM_HIND,Q3_ANOM_HIND
66,1,1981,"[2, 3, 4, 5, 6, 7, 8, 9, 10]",2005-2005,0.9126,"[0.31691, 1.12085, 1.20088, 1.37364, 0.79624, ...","[0.49291, -0.2787, 1.68828, 1.21699, 1.5332, 0...",2.42733,0.029435,1.016292,-0.571864,0.582247
67,1,1981,"[2, 3, 4, 5, 6, 7, 8, 9, 10]",2006-2006,1.1219,"[0.31691, 1.12085, 1.20088, 1.37364, 0.79624, ...","[-0.13756, 0.09441, -0.48783, -0.98635, 1.3171...",-0.40592,0.029435,1.016292,-0.571864,0.582247
68,1,1981,"[2, 3, 4, 5, 6, 7, 8, 9, 10]",2007-2007,1.1491,"[0.31691, 1.12085, 1.20088, 1.37364, 0.79624, ...","[-0.67255, 2.33215, 1.95694, 1.71323, -0.21785...",-0.06992,0.029435,1.016292,-0.571864,0.582247
69,1,1981,"[2, 3, 4, 5, 6, 7, 8, 9, 10]",2008-2008,1.4531,"[0.31691, 1.12085, 1.20088, 1.37364, 0.79624, ...","[-0.30374, 0.80334, -0.65346, -0.86467, -0.893...",-0.27512,0.029435,1.016292,-0.571864,0.582247
70,1,1981,"[2, 3, 4, 5, 6, 7, 8, 9, 10]",2009-2009,1.2082,"[0.31691, 1.12085, 1.20088, 1.37364, 0.79624, ...","[0.21308, 0.48277, -0.65186, -1.02821, -0.5822...",1.08240,0.029435,1.016292,-0.571864,0.582247
71,1,1981,"[2, 3, 4, 5, 6, 7, 8, 9, 10]",2010-2010,1.3789,"[0.31691, 1.12085, 1.20088, 1.37364, 0.79624, ...","[2.82837, 0.54933, 0.44626, -0.30553, 0.61267,...",-0.17149,0.029435,1.016292,-0.571864,0.582247
72,1,1981,"[2, 3, 4, 5, 6, 7, 8, 9, 10]",2011-2011,NaN,"[0.31691, 1.12085, 1.20088, 1.37364, 0.79624, ...","[-0.39905, -0.53684, -0.67959, -0.99035, nan, ...",NaN,0.029435,1.016292,-0.571864,0.582247
73,1,1981,"[2, 3, 4, 5, 6, 7, 8, 9, 10]",2012-2012,NaN,"[0.31691, 1.12085, 1.20088, 1.37364, 0.79624, ...","[nan, nan, -0.58655, -1.22073, -1.20696, -0.78...",NaN,0.029435,1.016292,-0.571864,0.582247
74,1,1981,"[2, 3, 4, 5, 6, 7, 8, 9, 10]",2013-2013,NaN,"[0.31691, 1.12085, 1.20088, 1.37364, 0.79624, ...","[-0.27839, nan, nan, nan, -1.17355, nan, nan, ...",NaN,0.029435,1.016292,-0.571864,0.582247
75,1,1981,"[2, 3, 4, 5, 6, 7, 8, 9, 10]",2014-2014,NaN,"[0.31691, 1.12085, 1.20088, 1.37364, 0.79624, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan]",NaN,0.029435,1.016292,-0.571864,0.582247
76,1,1981,"[2, 3, 4, 5, 6, 7, 8, 9, 10]",2015-2015,NaN,"[0.31691, 1.12085, 1.20088, 1.37364, 0.79624, ...","[-0.39451, -0.67752, nan, -1.28372, -1.81426, ...",NaN,0.029435,1.016292,-0.571864,0.582247
77,1,1981,"[2, 3, 4, 5, 6, 7, 8, 9, 10]",2016-2016,1.2326,"[0.31691, 1.12085, 1.20088, 1.37364, 0.79624, ...","[-0.88705, -1.09663, 2.11815, 0.04985, -0.3017...",0.20097,0.029435,1.016292,-0.571864,0.582247
78,1,1981,"[2, 3, 4, 5, 6, 7, 8, 9, 10]",2017-2017,1.4294,"[0.31691, 1.12085, 1.20088, 1.37364, 0.79624, ...","[0.57783, -0.5459, -0.96938, 0.10773, -0.85083...",0.32454,0.029435,1.016292,-0.571864,0.582247
79,1,1981,"[2, 3, 4, 5, 6, 7, 8, 9, 10]",2018-2018,NaN,"[0.31691, 1.12085, 1.20088, 1.37364, 0.79624, ...","[-0.65973, 0.11227, -0.97901, -0.53768, -0.520...",NaN,0.029435,1.016292,-0.571864,0.582247

In [43]:
RESULTS.iloc[1230:1239]

,MONTH_PRED,YEAR_PRED,MONTH_TARG,YEAR_TARG,RMSE,TARG,PRED,OBS_ANOM,MEAN_ANOM_HIND,STD_ANOM_HIND,Q1_ANOM_HIND,Q3_ANOM_HIND
1230,5,1983,"[6, 7, 8, 9, 10, 11, 12, 1, 2]",2010-2011,0.7175,"[1.17573, 0.60522, 0.72602, 0.38415, nan, nan,...","[0.61267, 1.05753, 0.99331, 1.74624, -0.69146,...",-0.99035,0.018355,1.005721,-0.794718,0.727455
1231,5,1983,"[6, 7, 8, 9, 10, 11, 12, 1, 2]",2011-2012,NaN,"[1.17573, 0.60522, 0.72602, 0.38415, nan, nan,...","[nan, nan, nan, nan, nan, nan, nan, nan, nan]",NaN,0.018355,1.005721,-0.794718,0.727455
1232,5,1983,"[6, 7, 8, 9, 10, 11, 12, 1, 2]",2012-2013,NaN,"[1.17573, 0.60522, 0.72602, 0.38415, nan, nan,...","[-1.20696, -0.78242, nan, nan, 1.35065, 1.0568...",NaN,0.018355,1.005721,-0.794718,0.727455
1233,5,1983,"[6, 7, 8, 9, 10, 11, 12, 1, 2]",2013-2014,NaN,"[1.17573, 0.60522, 0.72602, 0.38415, nan, nan,...","[-1.17355, nan, nan, nan, -0.52926, nan, nan, ...",NaN,0.018355,1.005721,-0.794718,0.727455
1234,5,1983,"[6, 7, 8, 9, 10, 11, 12, 1, 2]",2014-2015,NaN,"[1.17573, 0.60522, 0.72602, 0.38415, nan, nan,...","[nan, nan, nan, nan, nan, 1.22796, nan, 0.2048...",NaN,0.018355,1.005721,-0.794718,0.727455
1235,5,1983,"[6, 7, 8, 9, 10, 11, 12, 1, 2]",2015-2016,2.0100,"[1.17573, 0.60522, 0.72602, 0.38415, nan, nan,...","[-1.81426, -2.45869, 0.98308, -1.12454, -0.102...",0.04985,0.018355,1.005721,-0.794718,0.727455
1236,5,1983,"[6, 7, 8, 9, 10, 11, 12, 1, 2]",2016-2017,0.8425,"[1.17573, 0.60522, 0.72602, 0.38415, nan, nan,...","[-0.30178, 1.46443, 0.58962, 0.69366, -0.58094...",0.10773,0.018355,1.005721,-0.794718,0.727455
1237,5,1983,"[6, 7, 8, 9, 10, 11, 12, 1, 2]",2017-2018,1.1998,"[1.17573, 0.60522, 0.72602, 0.38415, nan, nan,...","[-0.85083, 0.16631, 1.7006, 1.62972, -0.10848,...",-0.53768,0.018355,1.005721,-0.794718,0.727455
1238,5,1983,"[6, 7, 8, 9, 10, 11, 12, 1, 2]",2018-2019,NaN,"[1.17573, 0.60522, 0.72602, 0.38415, nan, nan,...","[-0.52017, 0.88362, nan, nan, nan, nan, nan, n...",NaN,0.018355,1.005721,-0.794718,0.727455

In [44]:
RESULTS.tail(10)

,MONTH_PRED,YEAR_PRED,MONTH_TARG,YEAR_TARG,RMSE,TARG,PRED,OBS_ANOM,MEAN_ANOM_HIND,STD_ANOM_HIND,Q1_ANOM_HIND,Q3_ANOM_HIND
20864,12,2022,"[1, 2, 3, 4, 5, 6, 7, 8, 9]",2012-2012,NaN,"[1.14127, -0.25215, -0.3898, -0.61355, -0.1786...","[nan, nan, nan, -0.58655, -1.22073, -1.20696, ...",NaN,0.029552,0.997665,-0.718383,0.508821
20865,12,2022,"[1, 2, 3, 4, 5, 6, 7, 8, 9]",2013-2013,NaN,"[1.14127, -0.25215, -0.3898, -0.61355, -0.1786...","[0.90838, -0.27839, nan, nan, nan, -1.17355, n...",NaN,0.029552,0.997665,-0.718383,0.508821
20866,12,2022,"[1, 2, 3, 4, 5, 6, 7, 8, 9]",2014-2014,NaN,"[1.14127, -0.25215, -0.3898, -0.61355, -0.1786...","[nan, nan, nan, nan, nan, nan, nan, nan, nan]",NaN,0.029552,0.997665,-0.718383,0.508821
20867,12,2022,"[1, 2, 3, 4, 5, 6, 7, 8, 9]",2015-2015,NaN,"[1.14127, -0.25215, -0.3898, -0.61355, -0.1786...","[0.2048, -0.39451, -0.67752, nan, -1.28372, -1...",NaN,0.029552,0.997665,-0.718383,0.508821
20868,12,2022,"[1, 2, 3, 4, 5, 6, 7, 8, 9]",2016-2016,1.5570,"[1.14127, -0.25215, -0.3898, -0.61355, -0.1786...","[0.81419, -0.88705, -1.09663, 2.11815, 0.04985...",-0.31237,0.029552,0.997665,-0.718383,0.508821
20869,12,2022,"[1, 2, 3, 4, 5, 6, 7, 8, 9]",2017-2017,1.6307,"[1.14127, -0.25215, -0.3898, -0.61355, -0.1786...","[0.20097, 0.57783, -0.5459, -0.96938, 0.10773,...",-0.80314,0.029552,0.997665,-0.718383,0.508821
20870,12,2022,"[1, 2, 3, 4, 5, 6, 7, 8, 9]",2018-2018,NaN,"[1.14127, -0.25215, -0.3898, -0.61355, -0.1786...","[0.32454, -0.65973, 0.11227, -0.97901, -0.5376...",NaN,0.029552,0.997665,-0.718383,0.508821
20871,12,2022,"[1, 2, 3, 4, 5, 6, 7, 8, 9]",2019-2019,NaN,"[1.14127, -0.25215, -0.3898, -0.61355, -0.1786...","[nan, nan, -0.44999, -1.3193, 0.05329, 1.71577...",NaN,0.029552,0.997665,-0.718383,0.508821
20872,12,2022,"[1, 2, 3, 4, 5, 6, 7, 8, 9]",2020-2020,1.2570,"[1.14127, -0.25215, -0.3898, -0.61355, -0.1786...","[-0.38574, -0.74238, -1.05953, -1.18835, -1.60...",-1.39822,0.029552,0.997665,-0.718383,0.508821
20873,12,2022,"[1, 2, 3, 4, 5, 6, 7, 8, 9]",2021-2021,1.4085,"[1.14127, -0.25215, -0.3898, -0.61355, -0.1786...","[-0.2304, 0.8605, 0.71056, 0.67095, -0.08795, ...",-1.15484,0.029552,0.997665,-0.718383,0.508821

In [45]:
TTT = pd.DataFrame()
TTT['DATE'] = pd.date_range(datetime.date.today().replace(year=RESULTS.iloc[0]['YEAR_PRED'], month=RESULTS.iloc[0]['MONTH_PRED'], day=1),datetime.date.today().replace(year=RESULTS.iloc[-1]['YEAR_PRED'], month=RESULTS.iloc[-1]['MONTH_PRED'], day=1),freq='MS')
TTT['MONTH_PRED'] = pd.date_range(datetime.date.today().replace(year=RESULTS.iloc[0]['YEAR_PRED'], month=RESULTS['MONTH_PRED'][0], day=1),datetime.date.today().replace(year=RESULTS.iloc[-1]['YEAR_PRED'], month=RESULTS.iloc[-1]['MONTH_PRED'], day=1),freq='MS').month
TTT['YEAR_PRED'] = pd.date_range(datetime.date.today().replace(year=RESULTS.iloc[0]['YEAR_PRED'], month=RESULTS['MONTH_PRED'][0], day=1),datetime.date.today().replace(year=RESULTS.iloc[-1]['YEAR_PRED'], month=RESULTS.iloc[-1]['MONTH_PRED'], day=1),freq='MS').year
TTT['MONTH_PRED_cal'] = TTT['MONTH_PRED'].apply(lambda x: calendar.month_abbr[x])

In [46]:
TTT.tail(5)

          DATE  MONTH_PRED  YEAR_PRED MONTH_PRED_cal
500 2022-08-01           8       2022            Aug
501 2022-09-01           9       2022            Sep
502 2022-10-01          10       2022            Oct
503 2022-11-01          11       2022            Nov
504 2022-12-01          12       2022            Dec

In [47]:
best_n = 5
INDEX_best_n = []
RMSE_best_n = []
w_best_n = []
OBS_ANOM_best_n = []

MEAN_ANOM_HIND_best_n = []
STD_ANOM_HIND_best_n = []
Q1_ANOM_HIND_best_n = []
Q3_ANOM_HIND_best_n = []

for y in np.sort(TTT['YEAR_PRED'].unique()):
    #print(y)
    for m in np.sort(TTT['MONTH_PRED'].unique()):
        
        ## Get index observerved anomaly value series best n RMSE sorted
        AUX_1 = RESULTS.query('MONTH_PRED == @m & YEAR_PRED == @y').sort_values(by=['RMSE']).head(best_n).index
        AUX_2 = AUX_1.values.tolist()
        if AUX_2:
            INDEX_best_n.append(AUX_2)
        else:
            pass
        
        ## Get predicted anomaly value series best n RMSE sorted
        AUX_3 = RESULTS.query('MONTH_PRED == @m & YEAR_PRED == @y').sort_values(by=['RMSE']).head(best_n)
        AUX_4 = AUX_3['RMSE'].values.tolist()
#         AUX_5 = AUX_3['OBS_ANOM'].values.tolist()
        if AUX_4:
            RMSE_best_n.append(AUX_4)
            #Calculation of weights
            w_best_n.append(((1/np.array(AUX_4)) / (1/np.array(AUX_4)).sum()).round(6))
        else:
            pass

        ## Get observerved anomaly value series best n RMSE sorted
        AUX_5 = AUX_3['OBS_ANOM'].values.tolist()
        if AUX_5:
            OBS_ANOM_best_n.append(AUX_5)    
        else:
            pass
        
        ## Get mean anomaly of hindcast series best n RMSE sorted
        AUX_6 = AUX_3['MEAN_ANOM_HIND'].values.tolist()              
        if AUX_6:
            MEAN_ANOM_HIND_best_n.append(AUX_6[0])    
        else:
            pass
        
        ## Get standard deviation anomaly of hindcast series best n RMSE sorted
        AUX_7 = AUX_3['STD_ANOM_HIND'].values.tolist()       
        if AUX_7:
            STD_ANOM_HIND_best_n.append(AUX_7[0])    
        else:
            pass        
        
        ## Get Q1 anomaly of hindcast series best n RMSE sorted
        AUX_8 = AUX_3['Q1_ANOM_HIND'].values.tolist()       
        if AUX_8:
            Q1_ANOM_HIND_best_n.append(AUX_8[0])    
        else:
            pass        

        ## Get Q3 anomaly of hindcast series best n RMSE sorted
        AUX_9 = AUX_3['Q3_ANOM_HIND'].values.tolist()       
        if AUX_8:
            Q3_ANOM_HIND_best_n.append(AUX_9[0])    
        else:
            pass

In [48]:
TTT['INDEX_sort_best_n'] = INDEX_best_n
TTT['RMSE_sort_best_n'] = RMSE_best_n
TTT['Weights_sort_best_n'] = w_best_n
TTT['OBS_ANOM_sort_best_n'] = OBS_ANOM_best_n
TTT['MEAN_ANOM_HIND_best_n'] = MEAN_ANOM_HIND_best_n
TTT['STD_ANOM_HIND_best_n'] = STD_ANOM_HIND_best_n
TTT['Q1_ANOM_HIND_best_n'] = Q1_ANOM_HIND_best_n
TTT['Q3_ANOM_HIND_best_n'] = Q3_ANOM_HIND_best_n

In [49]:
TTT.head(15)

,DATE,MONTH_PRED,YEAR_PRED,MONTH_PRED_cal,INDEX_sort_best_n,RMSE_sort_best_n,Weights_sort_best_n,OBS_ANOM_sort_best_n,MEAN_ANOM_HIND_best_n,STD_ANOM_HIND_best_n,Q1_ANOM_HIND_best_n,Q3_ANOM_HIND_best_n
0,1980-12-01,12,1980,Dec,"[4, 40, 21, 0, 14]","[0.7381, 0.9338, 0.9902, 1.0408, 1.081]","[0.254596, 0.201239, 0.189777, 0.180551, 0.173...","[-0.7507, -1.15484, 1.83201, 0.39842, -1.02869]",-0.026612,1.000810,-0.753450,0.419850
1,1981-01-01,1,1981,Jan,"[46, 63, 82, 66, 54]","[0.6793, 0.7116, 0.8805, 0.9126, 0.9566]","[0.239201, 0.228344, 0.184542, 0.178051, 0.169...","[-0.67026, 1.66245, 1.14127, 2.42733, 1.29785]",0.029435,1.016292,-0.571864,0.582247
2,1981-02-01,2,1981,Feb,"[88, 105, 87, 124, 108]","[0.4964, 0.704, 0.8979, 0.9295, 0.9444]","[0.30142, 0.212535, 0.166638, 0.160973, 0.158434]","[-0.37071, 0.95838, -1.25926, -0.25215, -0.13756]",0.011885,1.011422,-0.649781,0.233294
3,1981-03-01,3,1981,Mar,"[147, 130, 150, 139, 126]","[0.6006, 0.745, 0.9166, 0.9168, 0.9204]","[0.265317, 0.213892, 0.173849, 0.173811, 0.173...","[0.21482, -0.89846, 0.09441, -0.02834, -0.37581]",0.049073,0.991664,-0.619743,0.506735
4,1981-04-01,4,1981,Apr,"[178, 172, 179, 181, 189]","[0.6748, 0.7262, 0.8123, 0.8252, 0.8406]","[0.228287, 0.212129, 0.189644, 0.18668, 0.18326]","[-0.10971, -0.56918, 0.94189, 1.1429, -0.68975]",0.048082,0.987980,-0.638065,0.607177
5,1981-05-01,5,1981,May,"[219, 234, 229, 213, 232]","[0.5838, 0.7343, 0.7349, 0.7584, 0.8103]","[0.245117, 0.194878, 0.194719, 0.188686, 0.1766]","[0.89762, 1.71323, 1.45493, 0.31567, 1.21699]",-0.045121,0.969551,-0.794718,0.675120
6,1981-06-01,6,1981,Jun,"[260, 263, 273, 254, 285]","[0.5721, 0.6948, 0.7525, 0.7783, 0.7876]","[0.247212, 0.203555, 0.187947, 0.181716, 0.179...","[0.51762, 0.30984, 1.5332, 0.50837, -0.85083]",0.004089,1.012392,-0.585955,0.618781
7,1981-07-01,7,1981,Jul,"[301, 304, 326, 295, 291]","[0.5722, 0.7197, 0.7889, 0.7898, 0.8295]","[0.254151, 0.202064, 0.184339, 0.184129, 0.175...","[0.28514, 0.49932, 0.16631, 0.09568, 0.60522]",-0.008401,1.011642,-0.399261,0.610187
8,1981-08-01,8,1981,Aug,"[342, 355, 332, 343, 345]","[0.6404, 0.8326, 0.8717, 0.8958, 0.898]","[0.254334, 0.195622, 0.186848, 0.181821, 0.181...","[-0.70814, -1.10505, 0.72602, 0.02873, -1.40723]",-0.025762,1.001655,-0.576282,0.592820
9,1981-09-01,9,1981,Sep,"[383, 386, 384, 395, 377]","[0.5551, 0.7973, 0.8422, 0.8646, 0.9143]","[0.277431, 0.193155, 0.182857, 0.17812, 0.168437]","[0.5321, -1.77771, 0.6566, 0.27023, 0.92787]",-0.014555,1.010203,-0.642866,0.556999
10,1981-10-01,10,1981,Oct,"[424, 427, 449, 436, 425]","[0.5307, 0.7845, 0.8236, 0.849, 0.8731]","[0.281391, 0.190356, 0.181319, 0.175894, 0.171...","[0.27008, -0.46078, -0.10848, 0.92721, 1.33573]",0.020231,1.005879,-0.576807,0.782336
11,1981-11-01,11,1981,Nov,"[465, 464, 490, 477, 466]","[0.7561, 0.8187, 0.8523, 0.8807, 0.9221]","[0.222759, 0.205726, 0.197616, 0.191243, 0.182...","[0.01748, 0.14634, -0.33705, 0.16546, 1.56234]",0.032112,0.993733,-0.674494,0.682502
12,1981-12-01,12,1981,Dec,"[507, 508, 501, 506, 532]","[0.7443, 0.7488, 0.7777, 0.8206, 0.8264]","[0.210141, 0.208878, 0.201116, 0.190602, 0.189...","[-0.66184, 2.35254, 0.49803, 0.55902, -0.80314]",-0.011067,1.011884,-0.753450,0.508821
13,1982-01-01,1,1982,Jan,"[560, 549, 574, 543, 538]","[0.7764, 0.8165, 0.8365, 0.9472, 0.9651]","[0.222064, 0.211158, 0.20611, 0.182022, 0.178646]","[0.22036, -0.39185, 0.32454, -0.50441, -0.30818]",0.062142,0.983523,-0.468951,0.582247
14,1982-02-01,2,1982,Feb,"[593, 591, 616, 620, 609]","[0.8064, 0.8515, 0.883, 0.9677, 0.971]","[0.221039, 0.209332, 0.201864, 0.184195, 0.18357]","[0.08035, 1.70298, -0.65973, -0.25215, -0.39905]",0.019368,1.014139,-0.649781,0.308603

In [50]:
TTT.tail(15)

,DATE,MONTH_PRED,YEAR_PRED,MONTH_PRED_cal,INDEX_sort_best_n,RMSE_sort_best_n,Weights_sort_best_n,OBS_ANOM_sort_best_n,MEAN_ANOM_HIND_best_n,STD_ANOM_HIND_best_n,Q1_ANOM_HIND_best_n,Q3_ANOM_HIND_best_n
490,2021-10-01,10,2021,Oct,"[20263, 20266, 20282, 20278, 20281]","[0.8756, 0.9315, 0.9466, 1.0321, 1.0492]","[0.219882, 0.206687, 0.20339, 0.186541, 0.183501]","[0.0175, 1.33573, 1.3713, -0.66635, -1.16394]",0.027208,0.999433,-0.576807,0.782336
491,2021-11-01,11,2021,Nov,"[20307, 20319, 20299, 20323, 20318]","[0.7084, 0.8784, 0.928, 0.9443, 1.0087]","[0.248614, 0.200499, 0.189782, 0.186506, 0.174...","[1.56234, -0.85743, 0.63389, 1.29656, 0.16546]",0.031166,0.994908,-0.674494,0.682502
492,2021-12-01,12,2021,Dec,"[20349, 20361, 20348, 20360, 20341]","[0.6937, 0.8061, 0.8386, 0.845, 0.9216]","[0.234663, 0.201942, 0.194116, 0.192646, 0.176...","[2.35254, -0.26371, -0.66184, -0.25158, -0.7507]",0.032079,0.994690,-0.718383,0.508821
493,2022-01-01,1,2022,Jan,"[20403, 20404, 20401, 20378, 20397]","[0.8004, 0.8278, 0.8468, 0.8805, 0.8994]","[0.212266, 0.20524, 0.200635, 0.192956, 0.188902]","[2.42733, -0.40592, 0.22036, -0.30818, -0.75205]",-0.008709,1.000513,-0.571864,0.287036
494,2022-02-01,2,2022,Feb,"[20439, 20445, 20450, 20432, 20420]","[0.7586, 0.7971, 0.8089, 0.9191, 0.9295]","[0.220701, 0.210041, 0.206977, 0.18216, 0.180122]","[-1.08268, -0.13756, -0.39905, 1.70298, 0.5119]",0.032535,1.013679,-0.649781,0.310361
495,2022-03-01,3,2022,Mar,"[20481, 20487, 20474, 20492, 20502]","[0.707, 0.7841, 0.8213, 0.8275, 0.8959]","[0.226962, 0.204645, 0.195375, 0.193912, 0.179...","[-1.34189, 0.09441, -0.43461, -0.53684, 0.71056]",0.049761,0.991360,-0.619743,0.506735
496,2022-04-01,4,2022,Apr,"[20544, 20529, 20540, 20516, 20534]","[0.7922, 0.8268, 0.9133, 0.9317, 0.9331]","[0.221003, 0.211754, 0.191699, 0.187913, 0.187...","[0.67095, -0.48783, -0.96938, 0.94189, -0.67959]",0.059942,0.982513,-0.628347,0.607177
497,2022-05-01,5,2022,May,"[20570, 20585, 20575, 20581, 20564]","[0.7042, 0.7131, 0.9316, 0.9532, 0.9706]","[0.237658, 0.234692, 0.179647, 0.175576, 0.172...","[-0.98635, -0.08795, -0.99035, 0.10773, 2.06476]",0.004466,1.012325,-0.794718,0.727455
498,2022-06-01,6,2022,Jun,"[20611, 20614, 20626, 20622, 20623]","[0.7089, 0.78, 0.7822, 0.8295, 0.9512]","[0.2265, 0.205853, 0.205274, 0.193569, 0.168803]","[1.31711, -0.58229, 1.11523, -0.85083, -0.52017]",0.033285,0.989471,-0.525142,0.618781
499,2022-07-01,7,2022,Jul,"[20663, 20652, 20655, 20667, 20664]","[0.648, 0.6947, 0.776, 0.8816, 0.9539]","[0.23911, 0.223036, 0.199669, 0.175753, 0.162432]","[0.16631, 0.21453, 1.06729, -0.1296, 0.88362]",-0.005062,1.012553,-0.399261,0.610187
500,2022-08-01,8,2022,Aug,"[20704, 20693, 20696, 20708, 20684]","[0.6242, 0.6486, 0.7515, 0.8477, 0.8907]","[0.236399, 0.227506, 0.196355, 0.174072, 0.165...","[1.7006, 0.33147, -0.36598, -0.00509, -0.16317]",0.035617,0.990098,-0.401450,0.626634
501,2022-09-01,9,2022,Sep,"[20745, 20737, 20725, 20736, 20716]","[0.6088, 0.7106, 0.9544, 1.0262, 1.0834]","[0.273986, 0.234735, 0.174772, 0.162544, 0.153...","[1.62972, -0.33655, -1.23853, -0.98884, -1.1859]",0.054879,0.956010,-0.504781,0.556999
502,2022-10-01,10,2022,Oct,"[20786, 20777, 20778, 20757, 20775]","[0.5922, 0.7105, 0.7657, 0.9879, 1.0784]","[0.266276, 0.22194, 0.20594, 0.15962, 0.146224]","[-0.10848, -1.16394, 1.3713, -1.28033, -0.12469]",0.047641,0.969089,-0.576807,0.782336
503,2022-11-01,11,2022,Nov,"[20818, 20814, 20819, 20797, 20798]","[0.6981, 0.7734, 0.8207, 0.9875, 1.0369]","[0.241929, 0.218374, 0.205788, 0.171028, 0.16288]","[-1.38478, 0.16546, 1.29656, -0.41519, -0.54493]",0.029675,0.996687,-0.674494,0.682502
504,2022-12-01,12,2022,Dec,"[20850, 20860, 20839, 20856, 20861]","[0.6773, 0.7387, 0.9397, 0.9663, 0.9747]","[0.247927, 0.22732, 0.178696, 0.173777, 0.17228]","[0.55199, -0.7103, -0.41369, -0.25158, 0.74751]",0.029552,0.997665,-0.718383,0.508821

In [51]:
Pred_Anom = []
for i in TTT.index:
    Pred_Anom.append((TTT['Weights_sort_best_n'][i] * TTT['OBS_ANOM_sort_best_n'][i]).sum())
    
TTT['Frcst_Anom'] = Pred_Anom

In [52]:
TTT

,DATE,MONTH_PRED,YEAR_PRED,MONTH_PRED_cal,INDEX_sort_best_n,RMSE_sort_best_n,Weights_sort_best_n,OBS_ANOM_sort_best_n,MEAN_ANOM_HIND_best_n,STD_ANOM_HIND_best_n,Q1_ANOM_HIND_best_n,Q3_ANOM_HIND_best_n,Frcst_Anom
0,1980-12-01,12,1980,Dec,"[4, 40, 21, 0, 14]","[0.7381, 0.9338, 0.9902, 1.0408, 1.081]","[0.254596, 0.201239, 0.189777, 0.180551, 0.173...","[-0.7507, -1.15484, 1.83201, 0.39842, -1.02869]",-0.026612,1.000810,-0.753450,0.419850,-0.182740
1,1981-01-01,1,1981,Jan,"[46, 63, 82, 66, 54]","[0.6793, 0.7116, 0.8805, 0.9126, 0.9566]","[0.239201, 0.228344, 0.184542, 0.178051, 0.169...","[-0.67026, 1.66245, 1.14127, 2.42733, 1.29785]",0.029435,1.016292,-0.571864,0.582247,1.082539
2,1981-02-01,2,1981,Feb,"[88, 105, 87, 124, 108]","[0.4964, 0.704, 0.8979, 0.9295, 0.9444]","[0.30142, 0.212535, 0.166638, 0.160973, 0.158434]","[-0.37071, 0.95838, -1.25926, -0.25215, -0.13756]",0.011885,1.011422,-0.649781,0.233294,-0.180274
3,1981-03-01,3,1981,Mar,"[147, 130, 150, 139, 126]","[0.6006, 0.745, 0.9166, 0.9168, 0.9204]","[0.265317, 0.213892, 0.173849, 0.173811, 0.173...","[0.21482, -0.89846, 0.09441, -0.02834, -0.37581]",0.049073,0.991664,-0.619743,0.506735,-0.188755
4,1981-04-01,4,1981,Apr,"[178, 172, 179, 181, 189]","[0.6748, 0.7262, 0.8123, 0.8252, 0.8406]","[0.228287, 0.212129, 0.189644, 0.18668, 0.18326]","[-0.10971, -0.56918, 0.94189, 1.1429, -0.68975]",0.048082,0.987980,-0.638065,0.607177,0.119792
...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,2022-08-01,8,2022,Aug,"[20704, 20693, 20696, 20708, 20684]","[0.6242, 0.6486, 0.7515, 0.8477, 0.8907]","[0.236399, 0.227506, 0.196355, 0.174072, 0.165...","[1.7006, 0.33147, -0.36598, -0.00509, -0.16317]",0.035617,0.990098,-0.401450,0.626634,0.377651
501,2022-09-01,9,2022,Sep,"[20745, 20737, 20725, 20736, 20716]","[0.6088, 0.7106, 0.9544, 1.0262, 1.0834]","[0.273986, 0.234735, 0.174772, 0.162544, 0.153...","[1.62972, -0.33655, -1.23853, -0.98884, -1.1859]",0.054879,0.956010,-0.504781,0.556999,-0.192254
502,2022-10-01,10,2022,Oct,"[20786, 20777, 20778, 20757, 20775]","[0.5922, 0.7105, 0.7657, 0.9879, 1.0784]","[0.266276, 0.22194, 0.20594, 0.15962, 0.146224]","[-0.10848, -1.16394, 1.3713, -1.28033, -0.12469]",0.047641,0.969089,-0.576807,0.782336,-0.227404
503,2022-11-01,11,2022,Nov,"[20818, 20814, 20819, 20797, 20798]","[0.6981, 0.7734, 0.8207, 0.9875, 1.0369]","[0.241929, 0.218374, 0.205788, 0.171028, 0.16288]","[-1.38478, 0.16546, 1.29656, -0.41519, -0.54493]",0.029675,0.996687,-0.674494,0.682502,-0.191837
504,2022-12-01,12,2022,Dec,"[20850, 20860, 20839, 20856, 20861]","[0.6773, 0.7387, 0.9397, 0.9663, 0.9747]","[0.247927, 0.22732, 0.178696, 0.173777, 0.17228]","[0.55199, -0.7103, -0.41369, -0.25158, 0.74751]",0.029552,0.997665,-0.718383,0.508821,-0.013475

In [53]:
TTT['Frcst_Anom_Rest'] = ( TTT['Frcst_Anom'] - TTT['MEAN_ANOM_HIND_best_n'] ) / TTT['STD_ANOM_HIND_best_n']

In [54]:
HIND_FORECAST_ANALOGUE = pd.DataFrame()
HIND_FORECAST_ANALOGUE['DATE'] = TTT['DATE']
HIND_FORECAST_ANALOGUE['MONTH_PRED'] = TTT['MONTH_PRED']
HIND_FORECAST_ANALOGUE['YEAR_PRED'] = TTT['YEAR_PRED']
HIND_FORECAST_ANALOGUE['FORECAST'] = TTT['Frcst_Anom_Rest']

In [55]:
ANOMALY_ANALOGUE_TS

     Month  Year  Anomaly_Qlog       DATE
0        1  1980     -2.123750 1980-01-01
1        2  1980      0.316909 1980-02-01
2        3  1980      1.120851 1980-03-01
3        4  1980      1.200881 1980-04-01
4        5  1980      1.373637 1980-05-01
..     ...   ...           ...        ...
511      8  2022     -1.282212 2022-08-01
512      9  2022     -1.975643 2022-09-01
513     10  2022     -1.762722 2022-10-01
514     11  2022     -1.097971 2022-11-01
515     12  2022     -1.063870 2022-12-01

[516 rows x 4 columns]

In [56]:
HIND_FORECAST_ANALOGUE

          DATE  MONTH_PRED  YEAR_PRED  FORECAST
0   1980-12-01          12       1980 -0.156002
1   1981-01-01           1       1981  1.036221
2   1981-02-01           2       1981 -0.189989
3   1981-03-01           3       1981 -0.239827
4   1981-04-01           4       1981  0.072582
..         ...         ...        ...       ...
500 2022-08-01           8       2022  0.345455
501 2022-09-01           9       2022 -0.258504
502 2022-10-01          10       2022 -0.283818
503 2022-11-01          11       2022 -0.222248
504 2022-12-01          12       2022 -0.043127

[505 rows x 4 columns]

In [57]:
OBSERVED_AND_HIND_FORECAST_ANALOGUE = pd.merge(ANOMALY_ANALOGUE_TS, HIND_FORECAST_ANALOGUE[['DATE','FORECAST']], how='left', on='DATE')

In [58]:
OBSERVED_AND_HIND_FORECAST_ANALOGUE.head(31)

    Month  Year  Anomaly_Qlog       DATE  FORECAST
0       1  1980     -2.123750 1980-01-01       NaN
1       2  1980      0.316909 1980-02-01       NaN
2       3  1980      1.120851 1980-03-01       NaN
3       4  1980      1.200881 1980-04-01       NaN
4       5  1980      1.373637 1980-05-01       NaN
5       6  1980      0.796236 1980-06-01       NaN
6       7  1980      0.669569 1980-07-01       NaN
7       8  1980      0.585540 1980-08-01       NaN
8       9  1980     -0.481964 1980-09-01       NaN
9      10  1980      0.640823 1980-10-01       NaN
10     11  1980     -0.107321 1980-11-01       NaN
11     12  1980      0.958023 1980-12-01 -0.156002
12      1  1981     -0.308179 1981-01-01  1.036221
13      2  1981      0.511895 1981-02-01 -0.189989
14      3  1981     -0.362955 1981-03-01 -0.239827
15      4  1981     -0.162872 1981-04-01  0.072582
16      5  1981      1.804841 1981-05-01  1.193129
17      6  1981     -0.163576 1981-06-01  0.409621
18      7  1981      0.327620 1981-07-01  0.332276
19      8  1981      0.927440 1981-08-01 -0.484070
20      9  1981      0.523972 1981-09-01  0.141840
21     10  1981     -0.748537 1981-10-01  0.337951
22     11  1981     -1.188138 1981-11-01  0.253888
23     12  1981      0.398420 1981-12-01  0.413178
24      1  1982     -1.551073 1982-01-01 -0.178876
25      2  1982      0.235052 1982-02-01  0.100585
26      3  1982     -0.375811 1982-03-01 -0.295800
27      4  1982     -0.336847 1982-04-01  0.057308
28      5  1982      0.930711 1982-05-01  0.601903
29      6  1982      1.175735 1982-06-01  0.061651
30      7  1982      0.605223 1982-07-01  0.286067

In [59]:
OBSERVED_AND_HIND_FORECAST_ANALOGUE.iloc[45:55]

    Month  Year  Anomaly_Qlog       DATE  FORECAST
45     10  1983      1.573028 1983-10-01  0.525646
46     11  1983      1.199867 1983-11-01  0.254514
47     12  1983     -0.256680 1983-12-01 -0.152365
48      1  1984      0.727208 1984-01-01 -0.045369
49      2  1984      2.454052 1984-02-01 -0.615199
50      3  1984      1.193772 1984-03-01  0.274948
51      4  1984     -0.160803 1984-04-01  0.167929
52      5  1984      0.722645 1984-05-01  0.846196
53      6  1984      1.159690 1984-06-01  0.723420
54      7  1984      1.575762 1984-07-01  0.200414

In [60]:
OBSERVED_AND_HIND_FORECAST_ANALOGUE.tail(25)

     Month  Year  Anomaly_Qlog       DATE  FORECAST
491     12  2020     -1.398219 2020-12-01  0.580222
492      1  2021     -0.230398 2021-01-01  0.657106
493      2  2021      0.860497 2021-02-01  0.554389
494      3  2021      0.710564 2021-03-01 -0.129103
495      4  2021      0.670950 2021-04-01 -0.491532
496      5  2021     -0.087954 2021-05-01  0.421934
497      6  2021      1.115231 2021-06-01 -0.540535
498      7  2021     -0.129605 2021-07-01 -0.192798
499      8  2021     -0.005090 2021-08-01 -0.407103
500      9  2021      0.059747 2021-09-01  0.034922
501     10  2021     -1.006693 2021-10-01  0.193851
502     11  2021     -1.153155 2021-11-01  0.579296
503     12  2021     -1.154836 2021-12-01  0.158021
504      1  2022      1.141266 2022-01-01  0.283175
505      2  2022     -0.252152 2022-02-01  0.019186
506      3  2022     -0.389803 2022-03-01 -0.400202
507      4  2022     -0.613546 2022-04-01 -0.154001
508      5  2022     -0.178636 2022-05-01 -0.061736
509      6  2022     -1.331390 2022-06-01  0.122896
510      7  2022      0.197415 2022-07-01  0.421244
511      8  2022     -1.282212 2022-08-01  0.345455
512      9  2022     -1.975643 2022-09-01 -0.258504
513     10  2022     -1.762722 2022-10-01 -0.283818
514     11  2022     -1.097971 2022-11-01 -0.222248
515     12  2022     -1.063870 2022-12-01 -0.043127

### Save  OBSERVED_AND_HIND_FORECAST_ANALOGUE

In [61]:
filename_1 = 'santalucia_caudales_HINDCAST_ANALOGUE_abr2023' + '_FL_' + str(FORECAST_LENGTH) + '_DANA_' + str(DANA)

In [62]:
filename_1

'santalucia_caudales_HINDCAST_abr2023_FL_3_DANA_9'

In [63]:
OBSERVED_AND_HIND_FORECAST_ANALOGUE.to_csv('../data/' + filename_1 + '.csv', index = False)

In [64]:
filename_2 = 'santalucia_caudales_HINDCAST_ANALOGUE_des_abr2023' + '_FL_' + str(FORECAST_LENGTH) + '_DANA_' + str(DANA)

In [65]:
TTT.to_csv('../data/' + filename_2 + '.csv', index = False)

In [66]:
filename_3 = 'santalucia_caudales_HINDCAST_ANALOGUE_res_abr2023' + '_FL_' + str(FORECAST_LENGTH) + '_DANA_' + str(DANA)
RESULTS.to_csv('../data/' + filename_3 + '.csv', index = False)